### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by xnutsive** [fastai/fastpages#111]
Fastpages provides search features built with `lunr.js`, thanks @hamelsmu!

Following up on the initial version, Hamel asked if there's a way to improve it, and provided [Just the Docs repo](https://github.com/pmarsceill/just-the-docs) as an example. Here are a few things that would be great to improve:

- [ ] **Make sure site load speeds stay fast by decoupling search indexing from the layout.** 

Just the Docs, interestingly, doesn't build the index on every page, but provides a JSON with the site content that the site front-end can grab when the user say focuses the search field: https://github.com/pmarsceill/just-the-docs/blob/master/assets/js/search-data.json

- [ ] **Add excerpts highlighting in the search results page**. 

[Here's the Just the Docs version of this](https://github.com/pmarsceill/just-the-docs/blob/master/assets/js/just-the-docs.js#L178), it's pretty sophisticated. We don't need it to be _that_ fancy, but we want each search result to have the matched post title, and the paragraph (or part) with the matched words highlighted, rendered in the search results. If something in the code block got matched — than the corresponding code block, or it's reasonable part (indent-based?) should be rendered. 

Bonus points: 

- [ ] **Clean up, vendor, and make a clear guide on JS dependency management.** 

What libraries is fastpages using, how do we bundle them up, and should we maybe introduce a minimal JS bundler (parcel?) to manage the front-end deps?

**Comment by Briy09** [comment]
Here are 2 examples: Jekyll theme with instant full text search and have keyword highlighting and context. Hope this is useful.

https://simpleyyt.com/ ,search "is" for example.
https://github.com/simpleyyt/jekyll-theme-next

https://blog.tmaize.net/pages/search.html ,search "ssh" for example.
https://github.com/TMaize/tmaize-blog

![snipaste_20191230_113706](https://user-images.githubusercontent.com/49552463/71567561-f17e5380-2afa-11ea-8732-19a869669033.png)

**Comment by hamelsmu** [comment]
@Briy09 Thos examples are great, but would need some help with english translation as I don't know what to put in some places.  Would you be up for attempting a PR on this?

**Comment by hamelsmu** [comment]
@Briy09 : after some exploration, I don't think we can use those examples, because they involve idiosyncratic code that I don't understand, and would be hard to maintain.  It would be safer to build something on an open source framework for longevity, like lunr.js

Here are some resources on more robust lunr.js resoruces:

https://dnoneill.github.io/jekyll-lunr-js-custom-search/docs/quickstart/frontend.html

and This example https://pmarsceill.github.io/just-the-docs/docs/search/  (which is linked above)

**Comment by hamelsmu** [comment]
This has been closed by https://github.com/fastai/fastpages/pull/164
