### ISSUE TITLE
Clustering fastpages repo?

### ISSUE THREAD

**Issue by deep-diver** [fastai/fastpages#113]
I found that GitHub provides a repo with disk quota of `1GB`. 
- [What is my disk quota](https://help.github.com/en/github/managing-large-files/what-is-my-disk-quota)

Blogging sometimes requires a lot or disk spaces because of the long history (even people keep media files including images in a cloud). Also, some people want to keep media files in the repo as well.

There could be some solutions like..
- (short term) specify Google Drive account. Whenever a user uploads images to the `/images` folder, `fastpages` automatically uploads them to the Google Drive. Of course the link should be generated and replace the local reference from the blog post.
- (long term) clustering blog repos from fastpages to form one large blog. This could be somewhat related to pagination issue. For instance, one repo is for the year of `2020` and the other repo is for `2021`, then create links for each to switch back and forth.

This seems out of the scope for this project. I just wanted to hear what other people think about my idea.
Thank you

**Comment by xnutsive** [comment]
Thank you for the suggestion! ❤️

I was concerned about the 1gb limit as well. I feel like there are several approaches to working with the limit: 

1. Switch to another static site hosting platform if the website becomes too large for a free gh-pages. Netlify, Zeit, and others — by the time your blog is >1gb, it's easy to tweak your Github Action to push the generated site to another hosting platform ;-) 
2. Provide an integration with a cloud storage provider to store media and data. I'm assuming some folks will use fastpages to blog about ML, and some of those would want to store datasets, or pickled datasets after some preprocessing. Having a nice API and an authentication mechanism to seamlessly upload those to S3 or Google Cloud would be a neat feature. 

I don't know if Google Drive is fast enough to put images there and then reference them from a web page — did you try doing this in your projects?

**Comment by hamelsmu** [comment]
Agreed with @xnutsive .  Only other thought I have re: this problem is to host images on https://imgur.com/ (which is free) that way you don't have anything locally.  

I'll go ahead and close this issue, feel free to reopen if necessary

**Comment by byteshiva** [comment]
> Agreed with @xnutsive . Only other thought I have re: this problem is to host images on https://imgur.com/ (which is free) that way you don't have anything locally.

Imgur only allows video length less than 60 seconds in free version.

**Comment by hamelsmu** [comment]
What about YouTube?
