### ISSUE TITLE
Add a How-To section

### ISSUE THREAD

**Issue by ohmeow** [fastai/fastpages#114]
Would be nice to have an ever-growing how-to section added to the repo.  I'm familiar with jekyll but strugging to, for example, find out how to change the header of the page so I can replace my domain name with an image.  

Other examples may include:
- How to add your own favicon
- How to make your blog width 100%
...

**Comment by xnutsive** [comment]
I think as we get more and more questions here, [on the forums](https://forums.fast.ai/c/fastai-users/nbdev/48), and on Twitter, @hamelsmu and I can group the most popular ones into sections of the readme.md and development.md. 

Do let us know if you won't be able to figure anything out, we'll try to help you. I think the easiest way though would be through the forum thread.

**Comment by hamelsmu** [comment]
It is possible that we should host a docs site (will have to be in a seperate repo), only because too many markdown files etc. will become hard to read / search?  

Thoughts?

**Comment by xnutsive** [comment]
_If we rebuild fastpages as in nbdev — we'd have the docs site for free_.

**Comment by hamelsmu** [comment]
> If we rebuild fastpages as in nbdev — we'd have the docs site for free.

☝️ Unfortunately we would not be able to host it on github pages, because that real estate is already occupied on this repo for https://fastpages.fast.ai/, so we would have to use a different repo

Not sure nbdev is the best way to generate a docs site, when the repo is substantially non-python and is a collection of documents?  Could be adding too much uncessary overhead with no benefit?  I could be wrong

**Comment by hamelsmu** [comment]
Another solution to a How-To guide that is crowdsourced from the community that I discussed with @jph00 is to invite people to contribute blog posts to this page.  It sounds like a good idea, but I suppose we would have to create some rules, etc. to make the process more transparent and set expectations.  

If anyone has any thoughts let me know

**Comment by jph00** [comment]
I think it's mainly a matter of expectations. For contributions to fast.ai sites, we generally tell people to write stuff to host elsewhere, and then if they'd like it as, say a PR to some fast.ai project, submit it--but we can't promise to accept it in any form, and even if we do accept the idea we might well rewrite it. If we think what you've written is relevant and interesting and appropriate for us to include, then we will try to help you bring it up to a "fast.ai-worthy" level and make it fit with the rest of our pages and tools.

Most people don't follow through, and don't maintain their initial enthusiasm, so this avoids us wasting time on ideas that don't really go anywhere, but does allow tenacious and committed people to get involved.

**Comment by xnutsive** [comment]
> Another solution to a How-To guide that is crowdsourced from the community that I discussed with @jph00 is to invite people to contribute blog posts to this page. It sounds like a good idea, but I suppose we would have to create some rules, etc. to make the process more transparent and set expectations.

After sitting on this for a day, I believe I was wrong about _how good it would be to just port it to nbdev_, too excited about the idea. I think you're right that there's a ton of non-python infra that is core to the project. 

Crowdsourcing posts on fastpages repo itself and posting them to fastpages.fast.ai is a brilliant idea that I, to my embarasment, haven't thought about. 👏

**Comment by hamelsmu** [comment]
@ohmeow closing this, but feel free to write something up after you have collected some how-tos or tips.  

Also feel free to start a fastai forum thread on how tos if you don't want to be as formal as writing a blog post (but we encourage you to write one if you can)
