### ISSUE TITLE
Enable Creating and Organizing Series of Blog Posts

### ISSUE THREAD

**Issue by ncoop57** [fastai/fastpages#115]
Many people split their blog post into multiple parts as a series of tutorials or as an ongoing subject/topic. It would be nice to have `fastpages` automatically handle organizing series by grouping them together, linking previous parts to future parts, etc.

My initial thoughts are that this would not be too hard. The `front matter` markdown could just have another field called "series" where you place the name of the series like so:

```
# "Title
...
- series: Working with NLP
```

This series could then be treated as a special tag for blog posts where when a new post gets added with the identical series name, that new blog post is treated as the next part in the series and the previous posts will get updated with links to it. Using the series as special tags also has the benefit of easily searching for all of the parts associated with a topic.

Let me know what you think and thanks for the awesome repo!

**Comment by xnutsive** [comment]
What if you just used a category for this? Say you're doing a guide on GPT-2: 

```
categories: gpt2-explained
```

Then in the post, you can list all the posts in the same category and enumerate through them like (please don't quote me on this, pseudocoding on 4 hours of sleep): 

```
{% for post in site.categories.gpt2-explained %}
  <li>{{ post.tile }}
{% endfor %}
```

One trick that fastpages provides (well, it worked 3 weeks ago at least) is that if you write Liquid (Jekyll template) code in a markdown cell in your notebook, it'll still parse as Liquid. So the code above should work. I haven't tested it yet, but let me know if you'll dig in this direction and have any questions, I'd be happy to help.

**Comment by hamelsmu** [comment]
Agreed with @xnutsive that using the tagging feature that is already there is a good way to go about it.  You could link to the the tag category, for example here is a link to the Jupyter tag category on fastpages https://fastpages.fast.ai/categories/#jupyter

I hope that helps, and yes something like that code would work, I think if you wanted to force related posts to be shown, however, it might be a good idea to just manually put links on the top of your post and use the tagging category. 

Closing this issue for now, please reopen if closing is not appropriate.
