### ISSUE TITLE
User pages must be built from master branch

### ISSUE THREAD

**Issue by chekos** [fastai/fastpages#119]
Hi all! I'm super excited for this! I'm writing a quick tutorial on how to get started with `fastpages` in spanish. As part of that I wanted to start from zero and I created a new github account and used the template to create the blog repo. 

However, I cannot seem to change the Source from `master` to the `gh-pages` branch. The `gh-pages` branch is being built and published correctly, I just can't tell GitHub Pages to deploy from that branch instead of master and I get this message:

![Screenshot_2020-02-25 paco-el-chato paco-el-chato github io(1)](https://user-images.githubusercontent.com/28694175/75270307-30edb700-57af-11ea-94e4-31061740d754.png)

The repo is [paco-el-chato/paco-el-chato.github.io](https://github.com/paco-el-chato/paco-el-chato.github.io). I didn't have any problems doing this on my personal blog but (I think) that's because it was not deployed at chekos.github.io and it was not a user page. 

Does anyone know how I could fix this? or if it's even possible? 

Thanks in advance!

**Comment by hamelsmu** [comment]
@chekos fastpages currently doesn't support user pages, only project pages.  So you must name your repo something other than `paco-el-chato.github.io`, for example name your repo `blog`.

Hope that helps.  closing this issue for now, happy to keep discussing
