### ISSUE TITLE
[2020 Feb, 25]: [Jupyter Notebooks not showing up in blog form]

### ISSUE THREAD

**Issue by FReeshabh** [fastai/fastpages#122]
Regular Markdown posts posted in _posts show up correctly in the Blog. 
Jupyter Notebook Posts don't show up in the Blog , this includes the example Jupyter Notebook provided
![image](https://user-images.githubusercontent.com/18840982/75304329-afc30e00-5808-11ea-984d-8b75a2d347b9.png)

This is what shows up on the website (the one post there is made in regular markdown.
![image](https://user-images.githubusercontent.com/18840982/75304364-bd789380-5808-11ea-8b73-ab8916c56f95.png)

**Comment by nipunbatra** [comment]
I'd second that I face similar issues.

Repo link: https://github.com/nipunbatra/blog
The build completed without errors: https://github.com/nipunbatra/blog/runs/468760092

If I open  https://nipunbatra.github.io/blog/ it does not show the new notebook I created: https://github.com/nipunbatra/blog/blob/master/_notebooks/2019-08-20-Gaussian-Processes.ipynb

Further, the rendered page has missing assets: 
<img width="1440" alt="Screenshot 2020-02-26 08 30 25" src="https://user-images.githubusercontent.com/60985/75307793-9e165080-5872-11ea-911e-ecbad8015911.png">

**Comment by FReeshabh** [comment]
Hey @nipunbatra, I might be able to help with at least one of the issues! It looks like you didn't complete this step : https://github.com/nipunbatra/blog/pull/1

**Comment by xnutsive** [comment]
@nipunbatra, thanks for the detailed report! 

I do see the generated post on Gaussian Process in your `gh-pages` branch: https://github.com/nipunbatra/blog/blob/gh-pages/2020/02/25/2019-08-20-Gaussian-Processes.html — which makes me curious, did you setup Github Pages to use gh-pages branch? It's a setting in the repo settings: 

Here's a gif: https://share.getcloudapp.com/2NuBBXlg

**Comment by xnutsive** [comment]
@FReeshabh, checking out your repo and the action log, here's the step where it converted the post: https://github.com/FReeshabh/freeshabh.github.io/runs/468190387?check_suite_focus=true#step:6:7

And then here's the line where Jekyll picked it up and built the page: https://github.com/FReeshabh/freeshabh.github.io/runs/468190387?check_suite_focus=true#step:8:315 

And here's the built post in `gh-pages` branch: https://github.com/FReeshabh/freeshabh.github.io/tree/gh-pages/2020/02/25 

So if it doesn't show up in the published blog, and you've previously used `fast_template` — then could you please check and make sure the repo uses `gh-pages` branch in Settings for Github Pages? 

If not — it looks like we might need to add a notice about this behavior for folks upgrading from `fast_template`.  /cc @hamelsmu

**Comment by hamelsmu** [comment]
@FReeshabh fastpages does not support user pages, only project pages.  You must name your repo something other than freeshabh.github.io, because fastpages autopublishes to gh-pages.

@xnutsive - BTW fastpages automatically sets the branch for you as gh-pages users don't have to set this.

**Comment by hamelsmu** [comment]
I'll open a PR soon that opens an issue telling users they have named their repo incorrectly and telling them to start over again if this happens

**Comment by hamelsmu** [comment]
Closing this issue for now, since we have collectively identified all the problems here.  Feel free to reopen or open another issue if this is not the case.  

Thank you

**Comment by FReeshabh** [comment]
@hamelsmu Thanks! It works now. Just a minor question. Do I need to set up a redirect for freeshabh.github.io to go to freeshabh.github.io/blog ?

**Comment by hamelsmu** [comment]
I don't know if you can redirect or how to do that?  You can also check the section "Using Your Own Domain Name". https://www.fast.ai/2020/01/18/gitblog/

**Comment by hamelsmu** [comment]
@FReeshabh just leave your website url as is freeshabh.github.io/blog works fine

**Comment by IjeomaOdoko** [comment]
Hello, I used fastai pages to build a GitHub pages blog. I uploaded two python files as per instructions, but only one shows up as a post. The first created in Google Colab, the second created with local Jupyter notebook. Please advise. [blog repository](https://github.com/IjeomaOdoko/my-blog/tree/master/_notebooks)
![fastai pages issue 1](https://user-images.githubusercontent.com/50420658/95815423-da9b9d00-0cd9-11eb-8d66-bb52594f0a1c.PNG)

**Comment by hamelsmu** [comment]
Hello please open a separate issue and follow the troubleshooting instructions carefully before doing so

**Comment by SumitJha406** [comment]
> Hello, I used fastai pages to build a GitHub pages blog. I uploaded two python files as per instructions, but only one shows up as a post. The first created in Google Colab, the second created with local Jupyter notebook. Please advise. [blog repository](https://github.com/IjeomaOdoko/my-blog/tree/master/_notebooks)
> ![fastai pages issue 1](https://user-images.githubusercontent.com/50420658/95815423-da9b9d00-0cd9-11eb-8d66-bb52594f0a1c.PNG)

**Comment by SumitJha406** [comment]
> Hello, I used fastai pages to build a GitHub pages blog. I uploaded two python files as per instructions, but only one shows up as a post. The first created in Google Colab, the second created with local Jupyter notebook. Please advise. [blog repository](https://github.com/IjeomaOdoko/my-blog/tree/master/_notebooks)
> ![fastai pages issue 1](https://user-images.githubusercontent.com/50420658/95815423-da9b9d00-0cd9-11eb-8d66-bb52594f0a1c.PNG)

How you solved your issue , I am having same problem.

**Comment by hamelsmu** [comment]
I'm not sure Google Colab is compatible, it may not parse.

**Comment by SumitJha406** [comment]
> I'm not sure Google Colab is compatible, it may not parse.
Is kaggle notebook compatible?
