### ISSUE TITLE
Explore interactive notebook backends

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastpages#128]
> Also do you think it is possible to create fully interactive notebooks (not just Altair), perhaps using something like [Binder](https://mybinder.org) or [nbinteract ](https://www.nbinteract.com/)?

Other ideas people have told me about

- [viola](https://blog.jupyter.org/and-voil%C3%A0-f6a2c08a4a93)
- [ipympl](https://twitter.com/martinRenou/status/1233050336849518593?s=20)
- [Data Voyager/Draco](https://medium.com/@uwdata/draco-representing-applying-learning-visualization-design-guidelines-64ce20287e9d)

**Comment by epassaro** [comment]
Bokeh please!

**Comment by hamelsmu** [comment]
Implement nbinteract per https://forums.fast.ai/t/fastpages-github-pages-blog-using-nbdev/62828/166

> I made a simple example of getting a text input from a user in this repo 2:

> https://hiromis.github.io/experiment/2020-03-20-Text-Input.html 6

> I am not sure if it qualifies as a stand-alone because it probably needs that requirement.txt and .nbinteract.json file. But if this is something that can be hosted in fastpages, it would be amazing. And if there are other tools (like nbinteract) out there that would be easier to integrate with fastpages, then I have no problem switching to that tool as well!

**Comment by hamelsmu** [comment]
Not going to work on this at the moment, might revive this later on
