### ISSUE TITLE
[2020-02-27]: [Notebook conversion to blog post not showing up]

### ISSUE THREAD

**Issue by byteshiva** [fastai/fastpages#129]
## Prerequisites for filing a bug

- [ ] Did you run the local development server as indicated in the [development guide](https://github.com/fastai/fastpages/blob/master/DEVELOPMENT.md)?  
  - Please include any useful logs or error messages from that
- [x] Have you searched opened / closed issues on this repo for a similar problem?
- [ ] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

## Please include the following information

1. Steps to reproduce the problem
I placed 2020-0227-*.ipynb file in `_notebook` which has  791 KB capacity. It failed to show up in the blog page. Am I missing something here are there any limit to notebook capacity?

![image](https://user-images.githubusercontent.com/10637299/75383500-72db4200-5902-11ea-80e2-5656ac3f2c70.png)

![image](https://user-images.githubusercontent.com/10637299/75383551-8dadb680-5902-11ea-85c2-0cbe878c9de3.png)

I see that it has skipped because of future date, I have put the naming convention as per my local time IST. I guess the github action might be running in different time zone than mine. Any resolution for this ?
~~~
  Skipping: _posts/2020-02-27-Diagram-as-Code.md has a future date
~~~

Reference log
https://github.com/byteshiva/blog/runs/470708733?check_suite_focus=true

**Comment by hamelsmu** [comment]
@byteshiva can do me a favor

Set the following in your`_config.yml` file and let me know if it works

future: true

**Comment by hamelsmu** [comment]
This is fixed by https://github.com/fastai/fastpages/pull/130

**Comment by byteshiva** [comment]
> @byteshiva can do me a favor
> 
> Set the following in your`_config.yml` file and let me know if it works
> 
> ```
> future: true
> ```

Thanks @hamelsmu, it worked after settings `future: true` 

Ref:
https://github.com/byteshiva/blog/runs/470888228?check_suite_focus=true
