### ISSUE TITLE
[2020/02/27]: [Images not appearing in the web page]

### ISSUE THREAD

**Issue by FReeshabh** [fastai/fastpages#140]
After writing the blog, the image appears in GitHub preview when I open it up.
![image](https://user-images.githubusercontent.com/18840982/75511693-8ba43000-59b4-11ea-9e56-0509aad1ccd7.png)

However I don't see the image in the actual webpage
![image](https://user-images.githubusercontent.com/18840982/75511758-c908bd80-59b4-11ea-9698-3677061abb2d.png)

**Comment by hamelsmu** [comment]
@FReeshabh Please use the designated bug template for filing an issue

![image](https://user-images.githubusercontent.com/1483922/75522110-fefe6f80-59bd-11ea-95a9-4d122922421e.png)

You did not include enough information in this for me to troubleshoot.  Please open a new issue with the information filled out.

**Comment by hamelsmu** [comment]
@FReeshabh I sent you a pull request: https://github.com/FReeshabh/blog/pull/4

To fix your issue.
