### ISSUE TITLE
[03-01-2020]: Unable to setup from template

### ISSUE THREAD

**Issue by ncoop57** [fastai/fastpages#157]
I keep trying to get setup with `fastpages` using the setup guide and youtube video, but I fail at the first step. When I click the "Use this template' button and create a repository from the `fastpages` repo, I get the following GitHub action error during the setup procedure about some missing `README_TEMPLATE.md`:

![image](https://user-images.githubusercontent.com/7613470/75638849-ec717980-5bfb-11ea-8e1f-a927d0125b45.png)

I looked through the `fastpages` issues and the `fastai` forums for anyone experiencing the same issue and found #91, but it seems to be referencing a different error in the first PR. Any help would be appreciated as I am extremely excited to start using this awesome project for my own blog!

**Comment by hamelsmu** [comment]
@ncoop57  sorry about that, should be fixed now.  Please try it again

**Comment by ncoop57** [comment]
It is working now, thanks @hamelsmu!
