### ISSUE TITLE
Linking About to another website

### ISSUE THREAD

**Issue by KeAWang** [fastai/fastpages#169]
**Is your feature request related to a problem? Please describe.**
At the top of a fastpages website, there is an "About" button. The contents of the about site is controlled by _pages/about.md. However, sometimes we want to link it to another website, like a personal website.

**Describe the solution you'd like**
Add an option to link to another website instead of _pages/about.md

**Comment by hamelsmu** [comment]
You have to setup a redirect , and edit the HTML of your head if the page is the about page.  

Not going to add a feature to fastpages for this.  

Some hints to get you started.  You should do a tutorial on Jekyll

https://jekyllrb.com/docs/

 and understand _includes 

https://jekyllrb.com/docs/includes/

Then you can setup a redirect with HTML 

https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7

Hope that helps

**Comment by CongLiu-CN** [comment]
If I want to add a new navigation link to the right of the three existing links, for example: <a href="exampleDomain">Chinese</a>
So there would be [About Me] [Search] [Tags] [Chinese] on the home page.
How should I do that?

@hamelsmu Thanks in advance.
