### ISSUE TITLE
Can't automatically upgrade due to lack of assets/icons

### ISSUE THREAD

**Issue by KeAWang** [fastai/fastpages#170]
#### You must check both boxes

- [y ] Have you searched opened / closed issues on this repo for a similar problem?
- [y] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

Steps to reproduce:
1. Attempt to update a fastpages repo by making the fastpages template issue.

This results in failure by github actions. With the following errors in "copying new files":
```
Run # remove files you don't want to copy from current version of fastpages
copying Gemfile
copying Gemfile.lock
copying Makefile
copying _action_files
copying _fastpages_docs
copying _includes
copying _layouts
copying _pages
copying docker-compose.yml
cp: cannot stat 'assets/icons': No such file or directory
##[error]Process completed with exit code 1.
```
The culprit is the recent removal of the `assets/icons` directory in favor of the `images` directory.

Link to the github actions failure: https://github.com/KeAWang/lower-the-entropy/runs/482918372

**Comment by hamelsmu** [comment]
Thank you for reporting this!  Fixed this with https://github.com/fastai/fastpages/commit/f60c582e371e8db6b54a9c20bd44a9ed621431dc
