### ISSUE TITLE
Create conda environment for fastpages

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastpages#176]
This is an alternative to Docker, which gives people the option of different ways of managing environments.

**Comment by xnutsive** [comment]
Want me to work on this?

**Comment by hamelsmu** [comment]
Yes please!  That would be excellent!  I tried and failed, miserably 😭

**Comment by hamelsmu** [comment]
Closing this issue b/c it is stale

**Comment by hamelsmu** [comment]
@giacomov can you help with this issue?

**Comment by giacomov** [comment]
sure! Can you point me to the status quo? Do you have any draft recipe or anything I can start from, or should I start from scratch?

**Comment by hamelsmu** [comment]
There is no status quo, put there are docker containers in the
_action_files directory as well as a docker compose file at the root of
this repo

**Comment by giacomov** [comment]
oh, ok! 

I am a little confused about the objective here. The beauty of this package is its integration with github.

How would you envision somebody running fastpages from a command line on their local machine? Wouldn't that pretty much amount to calling `nbdev`?

**Comment by hamelsmu** [comment]
This is a conda package that is an alternative for people for local development.  So instead of running docker compose they can use a conda package.  

The conda package will not change the way this application is deployed, it is only for local development. HTH

**Comment by giacomov** [comment]
ok, got it. I missed this information. Thanks!

**Comment by hamelsmu** [comment]
@giacomov following up -- any progress on this -- let me know if I can clarify anything

**Comment by hamelsmu** [comment]
I'm going to go ahead and close this issue as it is stale.  If anyone wants to volunteer will be happy to reopen
