### ISSUE TITLE
03-07-2020: Exporting Jupyter Notebook as HTML does not Render FastProgress bars

### ISSUE THREAD

**Issue by ncoop57** [fastai/fastpages#191]
#### You must check both boxes

- [x] Have you searched opened / closed issues on this repo for a similar problem?
- [x] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

1. Generate a Jupyter Notebook that uses the `fastprogress` library's `progress_bar` method for outputting status of for loops in python:
![image](https://user-images.githubusercontent.com/7613470/76150869-b5c4b480-607c-11ea-9f7a-9baa58dcaa64.png)

2. Push a Jupyter Notebook under the `_notebooks` folder on your repo's master branch and wait for GitHub Actions to complete

3. Navigate to your blog post on your fastpages' website and look at the output of the Jupyter Notebook cell with the `progress_bar` status:

![image](https://user-images.githubusercontent.com/7613470/76150858-99c11300-607c-11ea-9004-c6e565c68e12.png)

I believe the expected behavior should just be to render the progress bar as is done in the actual Jupyter Notebook

![image](https://user-images.githubusercontent.com/7613470/76150902-1522c480-607d-11ea-883b-49ab62044a8e.png)

Here is a link to the blog post with this issue which has a direct link to the Jupyter Notebook in GitHub and Google Colab: https://nathancooper.io/i-am-a-nerd/deep_learning/software_engineering/2020/03/07/How_to_Create_an_Automatic_Code_Comment_Generator_using_Deep_Learning.html

**Comment by hamelsmu** [comment]
@ncoop57 I don't know how easy it will be to include the progress bars, because of the way it is handled may be difficult.   

On another note, I looked at your blog post and I am really excited about it.  Let me know when you plan on advertising it!  I would love to share it!

**Comment by hamelsmu** [comment]
@ncoop57 I traced this back to a bug in fastprogress, which I opened a PR to fix https://github.com/fastai/fastprogress/pull/55

You can track the progress there.  🙇  Thank you, closing this issue.
