### ISSUE TITLE
some  variables have black background after ```python

### ISSUE THREAD

**Issue by sshleifer** [fastai/fastpages#192]
How can I turn off the rule that blackens some variables in markdown python code snippets?

eg in a markdown cell in 2020-03-07_blogpost.ipynb (look at the source, github will prolly render it)

```python
def forward(
    self,
    input_ids,
    attention_mask=None, # ignored pad tokens in input_ids
    decoder_input_ids=None, # make these if not supplied
    decoder_padding_mask=None, # ignored pad tokens in decoder_input_ids
):
```
results in
![image](https://user-images.githubusercontent.com/6045025/76156535-e7b03800-60c9-11ea-8463-f8073541aa7c.png)

#150 is related, I think.

**Comment by hamelsmu** [comment]
Are you using the most recent version of `fastpages`?   There were some recent CSS bugs that have been fixed.  The current state looks like this:

For notebooks:

![image](https://user-images.githubusercontent.com/1483922/76158520-622d8780-60cb-11ea-9afe-34ac293ed160.png)


For markdown

![image](https://user-images.githubusercontent.com/1483922/76158545-b6d10280-60cb-11ea-8a4e-bbc0dacd888d.png)


Please upgrade and let me know if this is still an issue.  If opening a new issue, please provide  a link to your repo.  🙇 Thank you!

**Comment by hamelsmu** [comment]
@sshleifer I just looked at your repo, and yeah unfortunately there was a pretty bad bug just a couple of days ago as I botched the CSS.  Really sorry about that.  I've made it easier to upgrade things, now.  Please have a go at it now and let me know.  

It's probably best if you copy over your posts to a new template.  ( It should be easy to upgrade from now on with the issue template).  Thanks

**Comment by sshleifer** [comment]
Thanks, that worked!
