### ISSUE TITLE
2020-03-08: Taller text output cells

### ISSUE THREAD

**Issue by sshleifer** [fastai/fastpages#193]
I am returning a string without newlines that it about 50 words. Ideally I want this to show up in multiple lines. Is there a way I can do that in html/yaml or should I manipulate the string in python?

![image](https://user-images.githubusercontent.com/6045025/76170258-9f8b2700-6156-11ea-8ddd-255a65a60755.png)
#### You must check both boxes

- [x ] Have you searched opened / closed issues on this repo for a similar problem?
- [x ] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

1. Steps to reproduce the problem
2. A link to the notebook or markdown file where the error is occuring

https://sshleifer.github.io/blog_v2/jupyter/2020/03/06/bart.html
https://github.com/sshleifer/blog_v2/blob/master/_notebooks/2020-03-06-bart.ipynb

**Comment by hamelsmu** [comment]
@sshleifer I'll look into this.  Can you let me know if this works in the meantime?

```py
from IPython.display import display, Markdown
display(Markdown('*some markdown* $\phi$'))
```

**Comment by sshleifer** [comment]
That worked! Thanks!

**Comment by hamelsmu** [comment]
@sshleifer I fixed this in https://github.com/fastai/fastpages/pull/199
