### ISSUE TITLE
10/03/2020  Custom Domain Problems

### ISSUE THREAD

**Issue by firmai** [fastai/fastpages#195]
Hi Great product,

I am looking to push my blog https://github.com/firmai/vault to www.firmai.org/blog. 

I have followed the appropriate steps, but the build still seems to fail. 

Any help would be appreciated. 

Thanks,
Derek

**Comment by firmai** [comment]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/26666267/76246683-0fa6c380-62a3-11ea-89a2-dc3465c341ed.png">

**Comment by hamelsmu** [comment]
Your CNAME file has

`https://www.firmai.org`

I believe it should contain

`firmai.org`

**Comment by hamelsmu** [comment]
You also never merged the setup PR

https://github.com/firmai/vault/pull/1

**Comment by firmai** [comment]
Thanks for having a look at this, the problem is persisting. Same issue.

**Comment by hamelsmu** [comment]
I believe there must be an issue with your ssh keys perhaps you put wrong keys in wrong place
