### ISSUE TITLE
Fast Template for Jupyter Books

### ISSUE THREAD

**Issue by timothyb0912** [fastai/fastpages#196]
**Is your feature request related to a problem? Please describe.**
Similar to how setting up a blog used to be a painful task with many steps, setting up a Jupyter Book currently has many steps and can be error prone as well.

**Describe the solution you'd like**
A fast template for creating a Jupyter Book website via a Github project page.

**Describe alternatives you've considered**
I haven't seen anything else like what I'm describing.

**Additional context**
An example of my trying unsuccessfully so far to set up a Jupyter Book inside of a project-repo that will also contain source code is [here](https://github.com/timothyb0912/genvi/tree/feature/init-dev-guide/dev-guide). This is the sort of effort I would have loved a fast template for. Manual following of the instructions can be error prone for non-trivial use cases.

**Comment by hamelsmu** [comment]
I believe @jph00 might have something for books?   Perhaps nbdev is the best thing I have seen so far for a books site:  https://github.com/fastai/nbdev

**Comment by hamelsmu** [comment]
Closing this issue as it probably is better suited for the forums:

@timothyb0912 can you please open a thread on the forums about this?  https://forums.fast.ai/c/fastai-users/nbdev

That will help with discoverability and discussion.  Thank you!
