### ISSUE TITLE
Intuitive URLs for looking at posts by year, month, or day ...

### ISSUE THREAD

**Issue by ohmeow** [fastai/fastpages#197]
Take for example this URL:  

https://fastpages.fast.ai/actions/markdown/2020/03/06/fastpages-actions.html

In most blogging platforms, you can get a list of posts by year, month, or day by hacking the URL as such:

https://fastpages.fast.ai/actions/markdown/2020/03/06 -> show markdown posts for the 6th

https://fastpages.fast.ai/actions/markdown/2020/03 -> show markdown posts for March 2020

https://fastpages.fast.ai/actions/markdown/2020 -> show markdown posts for 2020

**Comment by hamelsmu** [comment]
I'm not sure of a way to do this easily in Jekyll, without lots of customized development.  Happy to take a PR on this, but closing this for now.  I would suggest posting this on the fastai forums for more visibility and perhaps someone will offer a way to pull this off that is maintainable. 

Thank you.
