### ISSUE TITLE
[2020-03-13]: [Automated upgrade failing to pull latest commit]

### ISSUE THREAD

**Issue by byteshiva** [fastai/fastpages#208]
I see that the automated upgrade is not pulling latest commits from fastpages.

Are there any rules set to avoid multiple Automated PR for a day from fastpages. How many automated upgrades can we do in a day.

I don't see below error message relevant when there are commits happening on fastpages. 

```
Your version of fastpages is up to date. There is nothing to change
```

Ref:
https://github.com/byteshiva/blog/issues/7
https://github.com/byteshiva/blog/issues/8
https://github.com/byteshiva/blog/issues/9

**Comment by hamelsmu** [comment]
I just bumped the version.  It should allow you to upgrade, now.

**Comment by hamelsmu** [comment]
Let me know if you still have this issue, will be happy to reopen it.  Closing for now.

**Comment by byteshiva** [comment]
Thanks @hamelsmu, now It works fine.

**Comment by byteshiva** [comment]
It's again not upgrading from fast pages I see you've created Google analytics html, in the latest automated upgrade it's not getting reflected .

**Comment by hamelsmu** [comment]
It’ll work now

**Comment by hamelsmu** [comment]
Please note that I tend to wait a couple of days before bumping the version.  But since you asked I did it now 😃

**Comment by byteshiva** [comment]
> Please note that I tend to wait a couple of days before bumping the version. But since you asked I did it now

Oh thanks , how  update version related can you point me some documents to understand the code, any high level architecture or design documents or any conversation thread will also work.
