### ISSUE TITLE
[2020/03/13]: [Potential bug in reporting build fail]

### ISSUE THREAD

**Issue by stem-immigrant** [fastai/fastpages#209]
#### You must check both boxes

- [x] Have you searched opened / closed issues on this repo for a similar problem?
- [x] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

1. Using notebook to create a page
2. Example: https://github.com/stem-immigrant/blog/blob/master/_notebooks/2020-03-13-first-entry.ipynb
3. https://github.com/stem-immigrant/blog/runs/506841094?check_suite_focus=true
4. 
<img width="1616" alt="Screen Shot 2020-03-13 at 6 18 10 PM" src="https://user-images.githubusercontent.com/62118530/76663410-342ac600-6557-11ea-8f35-2edf6a002d64.png">

It appears that there is a failure in generating the page, but the error doesn't seem to be propagated properly. Note the error message despite the green check. Trying to figure out what the problem is, this bug is about resurfacing the problem.

**Comment by stem-immigrant** [comment]
reproducible, I get the same behavior when I do a small edit of the notebook.

**Comment by stem-immigrant** [comment]
I fixed the problem that lead to that particular error (in this case, I had a `:` in the title which is not allowed. It would have been nice if the error was not hidden under a apparently successful build. It looks to me that the error from the container is not properly propagated.

**Comment by hamelsmu** [comment]
YOu have to escape the `:` with double quotes.  This is mentioned explicitly in the docs https://github.com/fastai/fastpages#customizing-blog-posts-with-front-matter

Really strange that this is marked as a success.  I'll file a bug with GitHub.  Can you drop a link here to that workflow run?  You can get a link the line that errored, specifically that would be helpful.  

Closing as this seems like a bug with GitHub Actions.  Look forward to your follow up

**Comment by hamelsmu** [comment]
Nevermind, you already provided the link above.  I missed that.  Thanks and I'll file a bug on the GitHub side
