### ISSUE TITLE
Add an automatic open on binder badge

### ISSUE THREAD

**Issue by willingc** [fastai/fastpages#211]
I'm loving the work on this project. It would be lovely to offer the option to automatically open notebooks on mybinder.org in addition to Google's collab.

cc @betatim @choldgraf

**Comment by hamelsmu** [comment]
@willingc Thanks for the nudge ❤️ 

I discussed this with @betatim a [couple of weeks ago](https://discourse.jupyter.org/t/a-new-open-source-jupyter-blogging-system-hosted-on-github-pages/3334/4):

My question:

> Since this is a blogging site, I can imagine folks having a diverse set of Jupyter notebooks on many different topics. For example, someone may choose to write about Altair one day and deep learning using fastai the next day. Therefore, I can imagine that these notebooks would have very different dependencies.

> What is the best way to deal with this situation as my understanding is conventionally users of Binder are assumed to have a separate repo per project with dependencies defined globally at the repo level. 

@betatim's answer

> I think the %pip pattern is also what people do for colab where they can’t control what is installed (I think).

> Another option is to use a (big) base environment from a different repository and pull in the notebook for the post when someone launches it. Search this forum for “binder boxes” or “prepared binder”. The idea is that someone maintains a repo that installs dependencies but has little content of its own. In a different repo (or gist) you have all the content but none of the dependencies. You combine the two with a (slightly too) complex URL (but you are auto generating it, so that should be OK) which tells BinderHub to launch the container image for the dependencies repo but put a notebook from the contents repo in it. I made a little example based on the Kaggle kernels env: https://github.com/betatim/kaggle-binder/tree/master#how-can-i-use-this


**I suppose the best thing to do is to find a Docker Container that is hosted and well maintained on DockerHub that contains a reasonable set of Data Science dependencies, but doesn't take that long to build on Binder?  Any suggestions here?**

Thank you all for your thoughts!

**Comment by betatim** [comment]
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook is probably a good place to start.

If you choose the path of a base env + nbgitpuller I wouldn't worry about (re)build time as the base env will be (re)built rarely.

You could also ping https://github.com/googlecolab/colabtools/issues/1002 to see if there is any news on that.

**Comment by hamelsmu** [comment]
Great.  I'll get this integrated into fastpages soon.  

I'm going to change this so that users have two options for front matter:

## Option One (This will override the second approach if both exist)

```yaml
all_badges: true
```

this will include all badges (github, colab, binder, etc), and will be logically equivalent to:

## Option Two 

```yaml
badge:
   github: true
   collab: true
   binder: true
```

**Comment by hamelsmu** [comment]
I have closed this issue with https://github.com/fastai/fastpages/pull/216, please feel free to review. 

**Most importantly, I decided to punt on the issue of providing a Data Science environment, and let Binder use whatever default it uses in the absence of an environment specification.**

I included links to the Binder documentation in case the user wants to configure or customize their binder environment.

**Comment by willingc** [comment]
Thanks everyone!
