### ISSUE TITLE
Cannot launch make server

### ISSUE THREAD

**Issue by btahir** [fastai/fastpages#227]
Have you searched opened / closed issues on this repo for a similar problem?
Yes
Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?
Yes

Hi - 

I can't get make server to work. It worked the first time I set the repo up but not since. The localhost shows nothing and I get this docker error: `covid_dz_jekyll_1 exited with code 1`

I tried starting by deleting the docker images but it still did not work. Using make convert does convert the notebook to a post however and I can see the dashboard once I commit to master.

Not sure if this is the underlying issue: jekyll_1     | /usr/local/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/static_file.rb:70:in `stat': No such file or directory @ rb_file_s_stat - /data/data/LICENSE (Errno::ENOENT)

My repo is: https://github.com/btahir/covid_dz

Thanks!

**Comment by hamelsmu** [comment]
Try 

make stop

Followed by 

make build

**Comment by hamelsmu** [comment]
Sorry try `make remove` followed by `make build`

**Comment by btahir** [comment]
Still the same error.

**Comment by hamelsmu** [comment]
run the command `docker ps` you will see a list of container ids, for each container id do 

`docker stop <container id>`

then try `make build` and `make server` again

**Comment by hamelsmu** [comment]
Its your `data` folder.  You need to hide this folder from jekyll, either by renaming it to `_mydata`  or by hiding that folder in `_config.yml` via the `exclude` parameter.   

**Note** do NOT rename your folder to `_data` as that is somehting special in Jekyll

I was able to reproduce your error and resolved it with these steps.  Feel free to comment if you have any issues

**Comment by btahir** [comment]
Ah that did it. Thanks!
