### ISSUE TITLE
Customize URL - Remove Dates in URL

### ISSUE THREAD

**Issue by WittmannF** [fastai/fastpages#234]
Hello, I am creating a website with data analysis of the Corona Virus in Brazil. I want a fixed and intuitive link. Is it possible to create a link that does not necessarily contain the date of the blog? I was think of something like covid19br.github.io/world (something analog to this, but in portuguese). Is that possible?

**Comment by hamelsmu** [comment]
This can be achieved through permalinks

https://jekyllrb.com/docs/permalinks/
