### ISSUE TITLE
Result collapse

### ISSUE THREAD

**Issue by sharan19** [fastai/fastpages#237]
While scrapping for large quantities of images the results are pretty big and not very important for viewer.

**Describe the solution you'd like**
I would like for feature to collapse only the result and not code along with. The viewer can expand the result if required.

**Describe alternatives you've considered**
I tried to collapse or hide but that is not helpful

**Additional context**
I was building a image classifier using images scrapped from the internet. I build a large dataset of few hundred images. I feel scrolling through all those image results while scrapping will be unnecessary for the viewer.
![Current](https://user-images.githubusercontent.com/40206793/77894167-8d526380-7292-11ea-8d4d-3670d109a399.png)

**Comment by hamelsmu** [comment]
Do you mind opening an issue in `fastai/nbdev` about this?  This is where the change needs to be made, and I can help.  

Thank you

**Comment by hamelsmu** [comment]
@sharan19 Going ahead and closing this, please add the the issue to nbdev so we can work on this
