### ISSUE TITLE
3-30-2020: Cannot upgrade due to "cannot stat 'assets/main.scss'"

### ISSUE THREAD

**Issue by KeAWang** [fastai/fastpages#239]
#### You must check both boxes

- [Yes ] Have you searched opened / closed issues on this repo for a similar problem?
- [Yes] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

1. Try to upgrade through a GitHub Actions issue.
2. Error location: https://github.com/KeAWang/lower-the-entropy/runs/547445997?check_suite_focus=true

The failure under `copy new files` is:
```
copying Gemfile
copying Gemfile.lock
copying Makefile
copying _action_files
copying _fastpages_docs
copying _includes
copying _layouts
copying _pages
copying _plugins
copying _sass
copying docker-compose.yml
copying index.html
cp: cannot stat 'assets/main.scss': No such file or directory
##[error]Process completed with exit code 1.
```

**Comment by hamelsmu** [comment]
Hi sorry about this, you have to do copy your files over, this was right before I did a major refactoring of the repository.  So you cannot use the automatic upgrade, unfortunately.  

Sorry about this.  You should be fine after you copy over all your files.

**Comment by KeAWang** [comment]
What do you mean by "copy my files over"?

**Comment by hamelsmu** [comment]
create a new repo from the fastpages repo, copy your files from your old repo to the new repo
