### ISSUE TITLE
Not able to run "make server" 

### ISSUE THREAD

**Issue by kn-neeraj** [fastai/fastpages#244]
When I run make server command I get following error -
"
ERROR: for analyticsblog_jekyll_1  Cannot create container for service jekyll: status code not OK but 500: {"Message":"Unhandled exception: Drive sharing failed for an unknown reason"}

ERROR: for fastpages  Cannot create container for service fastpages: status code not OK but 500: {"Message":"Unhandled exception: Drive sharing failed for an unknown reason"}
"
Any ideas?

**Comment by hamelsmu** [comment]
What is your operating system?  Do you have issues with your local drive of some kind?  Have you installed Docker?

**Comment by kn-neeraj** [comment]
I am using windows 10.
No issues with local drive.
I had installed docker and it was running. Have to accept that I don't understand anything about Docker. I was tired of testing by pushing commits to git so want to setup local testing of the blog.

Any step by step guide how to do that? What is written in the repository didn't get me through.

Thanks.

**Comment by hamelsmu** [comment]
Unfortunately I don't know too much about windows.  This is a Docker, not a fastpages issue so. I suggest searching for this error.  I did a google search and found some threads

https://www.google.com/search?q=Unhandled+exception%3A+Drive+sharing+failed+for+an+unknown+reason&oq=Unhandled+exception%3A+Drive+sharing+failed+for+an+unknown+reason&aqs=chrome..69i57.269j0j7&sourceid=chrome&ie=UTF-8

@xnutsive is helping to create a conda environment that may be more approachable per https://github.com/fastai/fastpages/issues/176

If you figure out how to resolve this issue please let us know regardless.  Closing this issue for now, but feel free to keep the conversation going.
