### ISSUE TITLE
[2020-04-11]: [attachment:image in notebook is not converted correctly]

### ISSUE THREAD

**Issue by noklam** [fastai/fastpages#248]
1. Steps to reproduce the problem
1. Open a notebook, take a screenshot with Printscreen
2. Start a markdown cell , use Ctrl-V to paste the image -> which create attachment:image that can be seen from the notebook
3. fastpages converter fail to convert this image properly.

2. A link to the notebook or markdown file where the error is occuring
https://gist.github.com/noklam/ecf798806f1d721bb389dee2de5eda24

# Screenshots
![image](https://user-images.githubusercontent.com/18221871/79012988-41f55a80-7b9a-11ea-8220-2e00f2b0d06b.png)
##Expect screenshot images
![image](https://user-images.githubusercontent.com/18221871/79013010-4cafef80-7b9a-11ea-9532-4e4a0c291cf2.png)

**Comment by hamelsmu** [comment]
Unfortunately this will not work you have to reference the image with a relative path 

like this

`![](image.png)`
