### ISSUE TITLE
Integrate fastpages with existing github-page based blog

### ISSUE THREAD

**Issue by leemengtaiwan** [fastai/fastpages#249]
**Is your feature request related to a problem? Please describe.**
Great project!

I just want to ask whether it is possible to integrate fastpages with an existing GitHub-page based blog.

For example, I have a blog based on [leemengtaiwan.github.io](https://github.com/leemengtaiwan/leemengtaiwan.github.io) and is hosted on a custom domain [leemeng.tw](https://leemeng.tw). 

Is it possible to keep my original blog at `leemengtaiwan.github.io` and use fastpages to build an additional page like `leemeng.tw/fastpage_generated_pj.html` with Jupiter notebook? Any suggestion or direction is appreciated, thanks in advance!

**Comment by hamelsmu** [comment]
Here are some resources that might be helpful:

1. https://forums.fast.ai/t/fastpages-replacing-main-username-github-io-page-w-fastpages/64316/3

2. When you setup fastpages you will receive a PR that contains instructions on setting up a custom domain.  You can preview those instructions here: https://github.com/fastai/fastpages/blob/5fca2a629866a7936c3a46a5a8ab7958e78a5df7/_fastpages_docs/_setup_pr_template.md#optional-using-a-custom-domain

**Comment by hamelsmu** [comment]
Wow your site looks so nice, by the way!  Maybe fastpages should have a pelican extension, too

**Comment by leemengtaiwan** [comment]
@hamelsmu Thanks! I would follow your suggestions and try to integrate all the wonderful things in fastpages into my blog and tell everyone to use it :)

**Comment by leemengtaiwan** [comment]
> Maybe fastpages should have a pelican extension, too

@hamelsmu It would be dream come true! Since Pelican is written in Python, which is used extensively by all the data scientists and ML engineers, it would fit perfectly with the Jupiter blogging functionality provided by fastpages.
