### ISSUE TITLE
[04-12-2020]: The line of page titles getting broken

### ISSUE THREAD

**Issue by sayakpaul** [fastai/fastpages#252]
#### You must check both boxes

- [x] Have you searched opened / closed issues on this repo for a similar problem?
- [x] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

1. Steps to reproduce the problem: [N/A]
2. A link to the notebook or markdown file where the error is occurring: https://github.com/sayakpaul/portfolio/tree/master/_pages
3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.: N/A
4. This will help expedite troubleshooting: the A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. the local development server as indicated in the [development guide (https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md)? 

![image](https://user-images.githubusercontent.com/22957388/79062684-ffc33a80-7cb9-11ea-91b2-f46d2a069117.png)

My question: Is there a way to keep all the page titles in a single line?

**Comment by hamelsmu** [comment]
I see all pages titles in a single line

![image](https://user-images.githubusercontent.com/1483922/79062975-7547f000-7c53-11ea-80d3-019852e9781b.png)


depending on your screen size it will wrap things if you have that many items.

**Comment by sayakpaul** [comment]
That is because I deleted Tags and Search.

**Comment by hamelsmu** [comment]
I'm not sure if it is possible to not wrap to multiple lines because there is a hard upper limit to the screen width that this will show.  

Would it be acceptable if this appeared inside a collapsible menu?

**Comment by sayakpaul** [comment]
Yes, of course. That would be nice. On the other news, I just revamped my personal site sayak.dev this morning (IST) with fastpages. The experience was amazing. 

Site is live here: https://sayak.dev/.

**Comment by hamelsmu** [comment]
Thanks for sharing that !  

To try to fix this issue I’m going to take your screenshot and open an issue on the Jekyll/minima repo as this needs to be fixed upstream 

I’ll do this later today

**Comment by sayakpaul** [comment]
Sure sure. I am on my way to publishing my first blog post as well tonight. Will Tweet it out :)

**Comment by sayakpaul** [comment]
@hamelsmu, as promised here, 's my first blog post with Jupyter Notebooks and fastpages: https://sayak.dev/tf.keras/preprocessing/2020/04/13/embedding-image-preprocessing-functions.html. 

One tiny observation:

When I put a phrase within `~` it does not render as struck out on the website. On Colab though, it renders correctly. 

![image](https://user-images.githubusercontent.com/22957388/79100624-8f352000-7d84-11ea-9941-127ca9b2b9a1.png)

![image](https://user-images.githubusercontent.com/22957388/79100649-9a884b80-7d84-11ea-854a-676106f33e47.png)
