### ISSUE TITLE
2020-04-14: HTML <center> does not render in Markdown

### ISSUE THREAD

**Issue by e-tony** [fastai/fastpages#254]
#### You must check both boxes

- [ yes ] Have you searched opened / closed issues on this repo for a similar problem?
- [ yes ] Have you searched the [fastai forums](https://forums.fast.ai/) for a similar problem?

#### Failure to provide this information or going through these steps will result in automatic closing of the issue

1. Try to center markdown (e.g. \<center\>{% twitter https://twitter.com/jeremyphoward/status/1232059428238581760?s=20 %}\</center\>)
2. https://github.com/fastai/fastpages/blob/69caeb9bab6eb6af8bc136a1e036f13e6eb8f103/_posts/2020-03-06-fastpages-actions.md

**Comment by hamelsmu** [comment]
Tweet card is already centered by default. 

see this for example https://fastpages.fast.ai/actions/markdown/2020/03/06/fastpages-actions.html

 What exactly is the issue, then in this case?

**Comment by e-tony** [comment]
Twitter was just an example. I am trying to center a Markdown table.

**Comment by hamelsmu** [comment]
That won't work in Jekyll, you can use the <center> tag, but then everything inside <center> must be HTML, also.

**Comment by e-tony** [comment]
Ok. Will look for an alternative. Thank you!
