### ISSUE TITLE
Define notebook title and description through plain front matter

### ISSUE THREAD

**Issue by leemengtaiwan** [fastai/fastpages#255]
**Is your feature request related to a problem? Please describe.**

I know we can specify a post's title and description this way in the jupyter notebook:

```text
# my title
> a description

- toc: false 
```

But I really want a way to specify all the metadata including `title` and `description` using following more unified format, how can I achieve this:

```text
- title: my title
- description: a description
- toc: false 
```

I have tried setting `titles_from_headings` in `_config.yml` but `my_title` just got ignored and all I got is the default `Title` for a post's title.

```text
titles_from_headings:
  enabled:     false
  strip_title: true
  collections: true
```

**Describe the solution you'd like**

Able to specify title and description in following format:

```text
- title: my title
- description: a description
- toc: false 
```

**Comment by hamelsmu** [comment]
Can you open an issue with fastai/nbdev?  This is the correct place to do this.  Thank you!  

P.S. Good feature suggestion
