### ISSUE TITLE
How to change font?

### ISSUE THREAD

**Issue by DonYum** [fastai/fastpages#259]
Hi guys,
First of all, I have to admit that fastpages is awesome! It's so easy to get started.

However, When I write in Chinese, the display is not pretty. Such as:
https://donyum.github.io/blog/markdown/2020/04/17/docker-with-GPU-support.html

So, I wonder if there is a way to change the font.

Other advises that can beautify pages with Chinese are also appreciated.

Thx a lot!

**Comment by hamelsmu** [comment]
Thanks, @DonYum this section in the README contains instructions

https://github.com/fastai/fastpages#customizing-fastpages
