### ISSUE TITLE
2020-04-22: MathJax not working in Markdown cell

### ISSUE THREAD

**Issue by jasongfleischer** [fastai/fastpages#265]
## Required information

1. Steps to reproduce the problem

In a fast pages Jupyter notebook, create a markdown cell and paste LaTeX style math for MathJax into it.  For example the following:

So my optimistic number of beds is going to be to use all beds in San Diego, and assume an even better 60% non-COVID occupancy rate for both county and federal hospitals:

$(6509 + 2434) * (1 - 0.6) \sim 3600$ beds left over for COVID-19 patients 

2. A link to the notebook or markdown file where the error is occuring

https://jasongfleischer.github.io/argo-navis/covid19/jupyter/epidemiology/2020/04/20/SanDiego-COVID-19.html?fbclid=IwAR0DVyvLjku3jVqNtCEI-tb94AudZ598EFZ5wfGFNRj4IZEsEwZFx3EKKBE#The-number-of-available-hospital-beds

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.

N/A

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

<img width="833" alt="Screen Shot 2020-04-21 at 10 48 14 PM" src="https://user-images.githubusercontent.com/26612594/79945255-40d9ee00-8422-11ea-9b27-9b27529afc37.png">

There were no errors during site build: https://github.com/jasongfleischer/argo-navis/runs/607496351?check_suite_focus=true

**Comment by jasongfleischer** [comment]
Hahah I'm living in the future.  Just noticed its still the 21st not the 22nd. Sorry.

**Comment by hamelsmu** [comment]
you have to set `use_math` to `true` in `config.yml` per the README:

use_math: Set this to true to get LaTeX math equation support. This is off by default as it otherwhise loads javascript into each page that may not be used.

**Comment by jasongfleischer** [comment]
Thanks ! Sorry for the RTFM problem.

**Comment by yzhou79** [comment]
$$\sum_{i=0}^{k-1} [c_{i}*p^{*^{-1}}_{i}]_{p_{i}} * p_{i}^{*} - e*P$$

why above math doesn't show correctly?

**Comment by yzhou79** [comment]
\sum_{i=0}^{k-1} [c_{i}*p^{*^{-1}}_{i}]_{p_{i}} * p_{i}^{*} - e*P
