### ISSUE TITLE
Using `sticky_rank` in notebook posts

### ISSUE THREAD

**Issue by caglorithm** [fastai/fastpages#266]
Adding `sticky_rank` to the header of a notebook post but it doesn't affect the sorting of my posts. 

This features is only documented with Markdown posts. Does it work with notebooks as well? 

Thanks for the work!

**Comment by hamelsmu** [comment]
Did you try it with notebooks?  It works for me

```md
# Title
> description

- sticky_rank: 1
```

**Comment by hamelsmu** [comment]
I confirmed that this works for me, and added a clarification to the README.   The [fastpages](https://fastpages.fast.ai/) website also has a notebook post that is pinned to the top as an additional example.
