### ISSUE TITLE
2020-04-22: permission error during  Jekyll build on github 

### ISSUE THREAD

**Issue by wawachief** [fastai/fastpages#267]
Hi

I am experiencing a problem since today when building the site on github. Yesterday, it worked fine, today I added a new notebook. It builds correctly locally but it fails on github.

https://github.com/wawachief/fastpages/runs/609307981?check_suite_focus=true

The Jekyll build's logs are :
```
Run docker://jekyll/jekyll
  with:
    args: jekyll build -V
/usr/bin/docker run --name jekylljekyll_d35ae3 --label c27d31 --workdir /github/workspace --rm -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/fastpages/fastpages":"/github/workspace" jekyll/jekyll jekyll build -V
Fetching gem metadata from https://rubygems.org/.......
Using concurrent-ruby 1.1.6
Using i18n 0.9.5
Bundler::PermissionError: There was an error while trying to write to
`/usr/gem/cache`. It is likely that you need to grant write permissions for that
path.
An error occurred while installing minitest (5.14.0), and Bundler cannot
continue.
Make sure that `gem install minitest -v '5.14.0' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  github-pages was resolved to 204, which depends on
    jekyll-mentions was resolved to 1.5.1, which depends on
      html-pipeline was resolved to 2.12.3, which depends on
        activesupport was resolved to 6.0.2.2, which depends on
          minitest
```

**Comment by hamelsmu** [comment]
Please [upgrade fastpages](https://github.com/fastai/fastpages)

**Comment by ScottBrenner** [comment]
Hi, have this issue as well and my fastpages is up-to-date - https://github.com/ScottBrenner/asot-jupyter/issues/2#issuecomment-619700408 - any tips?

**Comment by hamelsmu** [comment]
Hi Scott, I don’t see any errors on your repo

**Comment by ScottBrenner** [comment]
Appreciate the quick reply - sorry, neglected to mention I'm seeing this error locally, when running `make build` (during `docker build --no-cache -t hamelsmu/fastpages-jekyll -f _action_files/fastpages-jekyll.Dockerfile .`). I'm on Windows 10 Home, running Docker with Docker Toolbox, in Windows Subsystem for Linux 😅

**Comment by hamelsmu** [comment]
Whats your error?

**Comment by ScottBrenner** [comment]
```
$ docker build --no-cache -t hamelsmu/fastpages-jekyll -f _action_files/fastpages-jekyll.Dockerfile .
Sending build context to Docker daemon  4.085MB
Step 1/5 : FROM jekyll/jekyll:4.0.0
 ---> 422d316c5393
Step 2/5 : COPY . .
 ---> 32039b06caec
Step 3/5 : RUN chmod -R 777 .
 ---> Running in 8bba8200de71
Removing intermediate container 8bba8200de71
 ---> c5aa97da4406
Step 4/5 : RUN gem install bundler
 ---> Running in dae87508ebb4
Successfully installed bundler-2.1.4
1 gem installed
Removing intermediate container dae87508ebb4
 ---> 571b19c730dd
Step 5/5 : RUN jekyll build
 ---> Running in e769c79c14ef
Fetching gem metadata from https://rubygems.org/.......
Using concurrent-ruby 1.1.6
Using i18n 1.8.2
Fetching minitest 5.14.0
Errno::EACCES: Permission denied @ rb_file_s_rename -
(/home/jekyll/.gem/ruby/2.7.0/cache/minitest-5.14.0.gem,
/usr/gem/cache/minitest-5.14.0.gem)
An error occurred while installing minitest (5.14.0), and Bundler cannot
continue.
Make sure that `gem install minitest -v '5.14.0' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  jemoji was resolved to 0.12.0, which depends on
    html-pipeline was resolved to 2.12.3, which depends on
      activesupport was resolved to 6.0.2.2, which depends on
        minitest
The command '/bin/sh -c jekyll build' returned a non-zero code: 5
```

**Comment by hamelsmu** [comment]
have you tried  grant permissions to this file?

chmod -R 777  <directory>

or something like that?

**Comment by ScottBrenner** [comment]
> have you tried  grant permissions to this file?

Doesn't that happen here?
https://github.com/fastai/fastpages/blob/c534fefb4c223dd8abedd7d8da34d9862b913288/_action_files/fastpages-jekyll.Dockerfile#L7

**Comment by hamelsmu** [comment]
it does, however its worth trying for troubleshooting

**Comment by hamelsmu** [comment]
Try rebuilding your docker images from scratch with `make build`

**Comment by hamelsmu** [comment]
I don’t have much experience with Docker on Windows, and some other folks
have had some problems.  Perhaps try the solution outlined here
https://stackoverflow.com/questions/43755922/error-mounting-a-config-file-into-the-container

**Comment by ScottBrenner** [comment]
Can confirm it's an issue with Docker on Windows:
```
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
```
Can open a shell to the container, grant permissions, then `jekyll build` works fine .. will report back if I can figure out a more permanent fix!

**Comment by juan-carlos-calvo** [comment]
I get the same error on a mac

**Comment by ScottBrenner** [comment]
Got it! It's an issue with the upstream `jekyll` image tagged at `4.0.0` ➡️ https://github.com/envygeeks/jekyll-docker/issues/268#issuecomment-619671719 has the workaround.

**Comment by juan-carlos-calvo** [comment]
Then I got another error. I would just change the base image to `3.8.6` until is fixed (this worked for me).

**Comment by vsoch** [comment]
I reproduced this error on Ubuntu 18.04, running jekyll/jekyll:latest (currently 4.0) with docker-compose.yml to deploy a jekyll site. Changing to 3.8 fixed the issue.

**Comment by hamelsmu** [comment]
I'm not sure if changing to 4.0 is safe as there were some pretty drastic changes.  I am monitoring this issue closely ... will try to fix this soon

**Comment by hamelsmu** [comment]
I am having problems reproducing this error, I'm really confused on how to fix this 

If anyone is available for pair programming would love to fix this please let me know if there are any volunteers

**Comment by juan-carlos-calvo** [comment]
> I am having problems reproducing this error, I'm really confused on how to fix this
> 
> If anyone is available for pair programming would love to fix this please let me know if there are any volunteers

happy to

**Comment by hamelsmu** [comment]
I am not comfortable with YOLO reverting back to 3.8.6 I am not confident that it won't break something else.

**Comment by hamelsmu** [comment]
@juan-carlos-calvo Just to confirm, if you clone a fresh copy of this repo, and then call

`make build`

do you get this same error?

**Comment by juan-carlos-calvo** [comment]
yes

**Comment by wawachief** [comment]
I had the same problems when I upgraded to 4.0. After quite a bit of struggle I got it running.
If I remember well, I changed _action_files/fastpages-jekyll.Dockerfile. Here is the content I use : 
```
_action_files/fastpages-jekyll.Dockerfile
# Defines https://hub.docker.com/repository/docker/hamelsmu/fastpages-jekyll
FROM jekyll/jekyll:4.0.0
ENV BUNDLE_PATH=$GEM_HOME

COPY . .

# Pre-load all gems into the environment
RUN chmod -R 777 .
RUN gem install bundler
RUN chmod -R 777 /home/jekyll /var/jekyll /srv/jekyll /usr/gem/
RUN jekyll build
```
To get it work I deleted all my docker images and containers relative to jekyll and run a make build. 
Now Everything works fine with the latest update, the action file on github and the local server.

**Comment by hamelsmu** [comment]
Many thanks to @juan-carlos-calvo for pair programming with me

Given the many issues with the Docker container, we decided to just use a frozen container and use `hamelsmu/fastpages-jekyll` instead of `jekyll/jekyll` for now until things are fixed.  You can [Upgrade](https://github.com/fastai/fastpages#upgrading-fastpages) to get these changes.
