### ISSUE TITLE
2020-4-29: blogs are not updated locally

### ISSUE THREAD

**Issue by jvanelteren** [fastai/fastpages#274]
Issue occurs after following steps:
When running fastpages locally on Windows 10 home
After running make build and make server
After changing and saving notebook in _notebooks folder

There seems to be nothing happening. Refreshing the browser shows the same old blog.

Output after running make server:
`Creating blog_fastpages_1 ... done
Creating blog_converter_1 ... done
Creating blog_watcher_1   ... done
Creating blog_jekyll_1    ... done
Attaching to blog_fastpages_1, blog_watcher_1, blog_converter_1, blog_jekyll_1
fastpages_1  | Agent pid 7
fastpages_1  | === Running Locally: All assets expected to be in the directory /data ===
converter_1  | Agent pid 7
converter_1  | === Running Locally: All assets expected to be in the directory /data ===
converter_1  | converting: _notebooks/2020-03-23-analyse.ipynb
fastpages_1  | converting: _notebooks/2020-03-23-analyse.ipynb
jekyll_1     | Successfully installed bundler-2.1.4
jekyll_1     | 1 gem installed`

**Comment by hamelsmu** [comment]
did you do a hard refresh in your browser to overcome the cache?

**Comment by hamelsmu** [comment]
also try incognito mode if you are unsure about your cache

**Comment by jvanelteren** [comment]
Tried out incogito, same result. I also don't see any additional output in the terminal which would indicate something is happening.
Both blog watcher and blog jekyll are active

**Comment by hamelsmu** [comment]
if you restart your server does it work?  Can you share your logs can you share a link to your repo and/or include other information that might be helpful in troubleshooting

**Comment by jvanelteren** [comment]
Restarting with ctrl c works.
Link to repo: https://github.com/jvanelteren/blog/
I've put a  log build and server.txt in the root with the log of make build and make server
I'm running that docker toolbox thing, since normal docker is not supported for windows home. Snapshot dockertoolbox.png also in the root

**Comment by hamelsmu** [comment]
I'm not able to reproduce this issue if I clone your repo -- hotloading works fine for me.  

Any additional ideas?  If you make a new fastpages repo without making any customizations, and change something in the notebook does it work for you?

**Comment by jvanelteren** [comment]
Tried it out, no luck
Is the terminal supposed to give a signal to show it detected a change? I only get terminal responses whenever I try to access a page on the blog that does not exist e.g. 
jekyll_1     | [2020-05-01 15:09:39] ERROR `/ddd/' not found.

But watcher never gives a response. It seems like it simply does not detect a change. 
Well otherwise I will manually restart. Still faster than pushing to github...

Thanks for creating fastpages btw! Simple publishing of notebooks has pushed me to make my pet projects better.

**Comment by hamelsmu** [comment]
I forked your branch and performed the following steps:

1. ran `make server`

2. Changed one of your blog posts to have the text `WOO TEST`

It was reflected locally 

![image](https://user-images.githubusercontent.com/1483922/80868215-e6c10000-8c4d-11ea-811f-5165deb98fe9.png)

And yes you will get a message that a change is detected like this

`watcher_1    | converting: _notebooks/2020-04-22-flights_above_nl.ipynb`

Also your images will not be imported correctly because you did not follow the instructions in config.yaml

```
###########################################################
#########  Special Instructions for baseurl ###############
#
#### Scenario One: If you do not have a Custom Domain #####
#    -  if you are not using a custom domain, the baseurl *must* be set to your repo name
# 
####  Scenario Two: If you have a Custom Domain #####
# 1. If your domain does NOT have a subpath, this leave this value as ""
# 2. If your domain does have a subpath, you must preceed the value with a / and NOT have a / at the end.  
#      For example: 
#           "" is valid
#           "/blog"        is valid
#            "/blog/site/" is invalid  ( / at the end)
#            "/blog/site"  is valid
#            "blog/site"   is invalid  ( because doesn't begin with a /)
#
# 3. You must replace the parameter `baseurl` in _action_files/settings.ini with the same value as you set here but WITHOUT QUOTES.
#
```
