### ISSUE TITLE
Automated Upgrade PR restores '_pages/about.md'

### ISSUE THREAD

**Issue by ScottBrenner** [fastai/fastpages#279]
## Description

The Automated Upgrade PR workflow reverts/restores changes to `_pages/about.md`

I opened https://github.com/ScottBrenner/asot-jupyter/issues/10 to begin the automated upgrade process in my repository, which triggered https://github.com/ScottBrenner/asot-jupyter/actions/runs/94105795 and created https://github.com/ScottBrenner/asot-jupyter/pull/11.

Everything looks good, except it wants to revert the any modifications to `_pages/about.md` - https://github.com/ScottBrenner/asot-jupyter/pull/11/files#diff-578149caa896d898111580a7a04f8ad8.

I manually restored the file with https://github.com/ScottBrenner/asot-jupyter/pull/11/commits/fd2488fe2ce8af551cfbb00f6c9a73a50d9fa723, but could the Automated Upgrade workflow ignore this file?

## Details

1. Steps to reproduce the problem
    - Commit a change to `_pages/about.md`
    - Trigger Automated Upgrade workflow

2. A link to the notebook or markdown file where the error is occuring
    - https://github.com/ScottBrenner/asot-jupyter/pull/11/commits/08b7c8ced777af891efbff3f21c63de7899cff8f#diff-578149caa896d898111580a7a04f8ad8

**Comment by hamelsmu** [comment]
@ScottBrenner thanks for letting me know, this should now be fixed

**Comment by ScottBrenner** [comment]
Confirmed, thanks! https://github.com/ScottBrenner/asot-jupyter/issues/14#issuecomment-623028509
