### ISSUE TITLE
Revert to previous notebook output if data resource is unavailable

### ISSUE THREAD

**Issue by anomal** [fastai/fastpages#288]
**Is your feature request related to a problem? Please describe.**
My fastpage displayed the following because the data source URL went down.
> An Exception was encountered at 'In [1]'.
> Execution using papermill encountered an exception here and stopped:

**Describe the solution you'd like**
Rollback to the previous working version of the notebook output if there is an error.

**Describe alternatives you've considered**
Exception handling in the notebook code might prevent the error message from displaying, but there would still be no graphs. Ideally, it is better to show the old version of the notebook (before the data resource went down).

**Additional context**
https://covid19dashboards.com/ontario-confirmed-cases-per-region/

**Comment by hamelsmu** [comment]
How does this issue relate to fastpages?  Should this issue be on covid19dashboards instead?

**Comment by hamelsmu** [comment]
Please open this issue on https://github.com/github/covid19-dashboard

However, I am not sure it makes sense to show an old dashboard if it is not able to update properly, I would rather it threw an error?  <please continue the conversation in the right repo, please so I can track>

Thanks
