### ISSUE TITLE
Search functionality not working

### ISSUE THREAD

**Issue by gkaissis** [fastai/fastpages#292]
## Required information

1. Steps to reproduce the problem
Selecting "search", then inserting a search term and hitting Return does nothing.
2. A link to the notebook or markdown file where the error is occurring
https://fastpages.fast.ai/search/

Happens in my own blog too: https://gkaissis.github.io/blog/search/

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.

Not applicable

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

Not applicable

**Comment by hamelsmu** [comment]
Wow ok not sure how this happened

**Comment by hamelsmu** [comment]
Thanks so much for reporting @gkaissis fixing this via https://github.com/fastai/fastpages/pull/293

**Comment by hamelsmu** [comment]
You can get the fix by [Upgrading fastpages](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/UPGRADE.md)
