### ISSUE TITLE
Website does not look right.

### ISSUE THREAD

**Issue by fpscan** [fastai/fastpages#294]
I've setup Fastpages based on PR and everything was working fine and I was about the write few things but I might changed something and this is how it looks like now;

![image](https://user-images.githubusercontent.com/4651944/81623216-9db23e00-93fb-11ea-9e8c-28ca872a911a.png)

**Comment by hamelsmu** [comment]
You have applied some customizations to your site that are breaking.  Please follow the troubleshooting steps and re open the issue after you have gathered necessary information to allow me to troubleshoot

![image](https://user-images.githubusercontent.com/1483922/81628354-5012e280-93b5-11ea-9139-1e942a63e6bf.png)

**Comment by hamelsmu** [comment]
My hunch is your `_config.yml` is specified incorrectly.  particularly your baseurl, I think your baseurl should be `""` instead of `/gadsby`. 

Again you have to follow the troubleshooting steps closely and it is likely you will be able to correct this on your own.  Thanks
