### ISSUE TITLE
Render Tensorboard Graphics from Jupyter Notebooks

### ISSUE THREAD

**Issue by ncoop57** [fastai/fastpages#296]
**Is your feature request related to a problem? Please describe.**
Tensorboard is commonly used to monitor progress model metrics as well as showing performance to others. I believe it would be super useful to render any tensorboard graphics inside of blog posts especially for posts that are comparing multiple models against each other.

**Describe the solution you'd like**
I would like a solution that takes a snapshot or even is able to embed a tensorboard graphic inside of a blog post that was generated using the Jupyter notebook magic
`%tensorboard --logdir <logs>`.

**Describe alternatives you've considered**
Some alternatives I've seen people float around is weights and bias, but I don't believe they are as well used or integrated well into notebooks currently. I could of course take a snapshot of the tensorboard and embed that into the blog post or even somehow export it to a matplotlib, however, a more robust solution would be to natively support rendering tensorboard graphics.

**Additional context**
![image](https://user-images.githubusercontent.com/7613470/81891272-04f3fd80-9576-11ea-9404-8cbcdc6ca4a6.png)
Here is a screen shot of an example tensorboard graphic that I wish could be rendered in my blog post automatically.

**Comment by hamelsmu** [comment]
Thanks I don't think this is possible as you need an interactive backend and in GitHub pages this not currently possible.  

Let me know if you come up with any further ideas.

**Comment by austinyhc** [comment]
@ncoop57 Maybe you could embed the tensorboard as an IFrame for fastpages to render. Hope it is helpful.
````python
from  IPython import display
display.IFrame(
    src="https://tensorboard.dev/experiment/${EXPERIMENT_ID}/",
    width = "100%",
    height="800px"
```
