### ISSUE TITLE
public blog but private pages

### ISSUE THREAD

**Issue by h17** [fastai/fastpages#298]
Issue: I would like to keep private GitHub with public blog page (ideally I would like to have some pages private and some public but I suspect that requires major GitHub change so I leave this out of scope of this ticket). 

Currently, work-around: public blog and private GitHub currently requires following each time:
make public entire repository, build, make repository private back.

**Comment by hamelsmu** [comment]
What errors do you get when your repository is private?

**Comment by h17** [comment]
The actions all go through no problem but 404 @ https://h17.github.io/temp/

To toggle between https://h17.github.io/temp/ working and not: change is private->public in settings of repository and then touch some file (like say toggle show_image between true and false in _config.yml).

I suppose the issue is that some process cannot read into private repository.
I added you as collaborator to https://github.com/h17/temp in case you want to take a closer look.
This entire page is just for testing.

**Comment by nehalecky** [comment]
Hey @h17, I also encountered the same issue! I had forgotten that I set my repo to private and remember this once I visited [Working with GitHub Pages](https://help.github.com/en/github/working-with-github-pages), and saw the disclaimer at the top reminding me that GH Pages wasn't available for private repo in _Free_ subscriptions:
![image](https://user-images.githubusercontent.com/1455590/83337161-ff80fd80-a26d-11ea-8695-9689201565c5.png)

It's working now as I change the settings of the repo to public and re-executed the [build-site](https://github.com/nehalecky/test-fastpages/runs/723463382?check_suite_focus=true) actions. 

I'm curious if your subscription is _Free_? If not, perhaps you can try upgrading to see if it still works? 
 
Regardless, the Action workflow might likely benefit from warning during build against a private repo or some post deployment check to see if the page was successfully deployed?

**Comment by hamelsmu** [comment]
This is unfortunately not possible at the moment, will go ahead and close this issue.  We will have to wait until private pages comes out on free accounts to support this

**Comment by hamelsmu** [comment]
> Regardless, the Action workflow might likely benefit from warning during build against a private repo or some post deployment check to see if the page was successfully deployed?

@h17 did you get a deployment error? Can you include a link to your failed deployment attempt here?

**Comment by HafizAhmadHassan** [comment]
I got a same issue I made a private blog with fastpages "notebook folders are " not accessible but Blog is accessible with the link
