### ISSUE TITLE
local images in notebooks are still not loading with fastpages

### ISSUE THREAD

**Issue by mrtunguyen** [fastai/fastpages#308]
Hello, 

1. following this issue [72](https://github.com/fastai/fastpages/issues/72) I think the problem of loading local images in notebooks was solved. However, it seems that local images in notebook are still not loading even though I already upgraded the last version of fastpage. Are there somethings I have to configure myself to make this feature working?

2. I wrote some mathematical formula which works well on notebook locally, but when i pushed into site, it can't render well? Do you have any sources to tell how we can write mathematical formula properly on markdown.

Thanks.

**Comment by hamelsmu** [comment]
Troubleshooting guide was not followed.
