### ISSUE TITLE
Integration with medium or best fastpages+medium practices

### ISSUE THREAD

**Issue by h17** [fastai/fastpages#309]
Articles created with fastpages do not upload into medium.  Integration would be great but not sure if possilbe, however workaround and best practices for fastpages+medium would be helpfull to include somewhere (like say FAQ page).  I expect that more than half of fastpage users also interested in publishing on medium, so this will help a lot of users.

**Comment by hamelsmu** [comment]
This is not possible to upload into Medium from fastpages
