### ISSUE TITLE
Wrong rendering of backticks in the post description

### ISSUE THREAD

**Issue by MaxBalashov** [fastai/fastpages#310]
I used backticks - `fastpages` in the description of my post. And it rendered in the wierd way (like latex formula).

You can see it [here](https://maxbalashov.github.io/ml-notes/fastpages/blogging/2020/05/26/DS-fastpages-blog.html):
![](https://user-images.githubusercontent.com/29922558/83362980-64d40c00-a39e-11ea-9c9f-7b17ea72d441.png)

Also I've attached [link](https://github.com/MaxBalashov/ml-notes/blob/master/_notebooks/2020-05-26-DS-fastpages-blog.ipynb) to post .ipynb.

**Comment by MaxBalashov** [comment]
Also add to file name [In progress]: `2020-05-26-[In progress]-DS-fastpages-blog.ipynb`
![](https://user-images.githubusercontent.com/29922558/83363307-28ee7600-a3a1-11ea-8062-7715c66c1367.png)

And also I've got bad rendering.

**Comment by hamelsmu** [comment]
Backticks are not supported in the description, its a special case where limitation of Jekyll
