### ISSUE TITLE
Showing line numbers in the code snippets

### ISSUE THREAD

**Issue by rednafi** [fastai/fastpages#313]
Showing line numbers in the code snippets can really help while explaining concepts with code snippets. I can easily refer to a particular line/chunk of code with `show_line_number` option turned on.

**Comment by hamelsmu** [comment]
@vosaul is working on this

**Comment by vosaul** [comment]
Hello,
![image](https://user-images.githubusercontent.com/28349676/84226126-9b6dfd00-aae9-11ea-8991-f1dc5ca11d23.png)

**Comment by hamelsmu** [comment]
Looks good 🥳

**Comment by hamelsmu** [comment]
This has to work for the different types of posts, including the Jupyter generated posts, which get generated as HTML files with an `.md` extension.  Let me know if that makes sense, when you run this project locally you will see examples in `_posts`

**Comment by hamelsmu** [comment]
Decided not to do this as every solution I have has edge cases that don’t work well

**Comment by jeremyabramson** [comment]
Is there any thought to re-starting this effort, even if it's only for a subset of post types (namely, in my case at least, notebooks?). 

Tutorial-type posts really benefit from being able to explain what's happening on specific lines of code.  I understand it may not work for all cases, but I'd take even a hacky solution if it allows that functionality.

**Comment by hamelsmu** [comment]
It’s beyond my skill level at the moment but if you know someone that can
help please invite them to contribute

**Comment by jeremyabramson** [comment]
@vosaul, I’d love to hear any updates on this. Even pointers for where to look for PRs. This feature — line numbers on NBconverted blog posts — is the main friction to me fully adopting fastpages. I’m willing to look into it, but if you’ve got the answer, all the better!

**Comment by vosaul** [comment]
@jeremyabramson It has been done for highlighting JSON, Python, and Yaml. If it's suited for you I'll find that code
