### ISSUE TITLE
[20200605] : Should all markdown pages contain a date in the filename?

### ISSUE THREAD

**Issue by gusdnd852** [fastai/fastpages#314]
Should all markdown pages contain a date in the filename?  It seems quite inconvenient when I manage documents on a file-by-file. It would be nice if the markdown file automatically includes the date like the notebook file. 

p.s. I think we don't need to generate URLs by date or manage files/posts by date (This is rather uncomfortable, maybe adding an option would be nice.)

**Comment by hamelsmu** [comment]
Yes they should contain a date in the file name, its the way Jekyll Works
