### ISSUE TITLE
Liquid error in the twitter tag in the default post.

### ISSUE THREAD

**Issue by jonathanmc** [fastai/fastpages#315]
### You must follow ALL the steps in the [troubleshooting guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/TROUBLESHOOTING.md).  Not doing so may result in automatic closure of the issue.

Did this.

## Required information

1. Steps to reproduce the problem

STEPS:

1. Copied repo. 

2. Followed install steps.  No site showed.

3. Went to SETTINGS and turned GitHub Pages on, on the MASTER branch.
-> Got build error in Twitter tag.

> The page build failed for the `master` branch with the following error:
> 
> The tag `twitter` on line 86 in `_posts/2020-01-14-test-markdown-post.md` is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.

4. Fixed twitter user name in config.
-> Still got same error.

5. Deleted Twitter card portion of generic test first post.
Page built properly.

There is something wrong with that Twitter card code but I am not well versed enough to debug it . I removed it, and site worked.

Note that mention to turn on Github Pages should be added to readme/start page too, for clarity.

2. A link to the notebook or markdown file where the error is occurring
3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.
4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

**Comment by hamelsmu** [comment]
If you do not copy the repo, you have to create a repository template, at which point a pull request is automatically opened for you.  You do not need to enable GitHub pages as that is enabled for you automatically if you follow the instructions closely.   this error occurs if steps are not followed.   Let me know if that helps!
