### ISSUE TITLE
Altair visualisations with separate data files

### ISSUE THREAD

**Issue by Rik-de-Kort** [fastai/fastpages#317]
Altair gives the option of putting the data that underlies visualisations in separate files, for instance:

````python
import altair as alt
import pandas as pd

alt.transformers.enable("json", urlpath="altairdata")

df = pd.DataFrame([[0, 1], [2, 3], [4, 5]], columns=["foo", "bar"])
alt.Chart(df).mark_point().encode(x="foo", y="bar")
````
This saves significantly on notebook size, and also gets around the 5000 rows restriction in a somewhat more scalable manner.

However, when using fastpages, the "altairdata" directory gets lost, leading to empty visualizations (see [here](https://nothingisnttrivial.com/2020/06/08/Introduction-Bayes.html) for an example).

I have a decent amount of programming experience, so if you give me some pointers I can also go hunt for it.

**Comment by hamelsmu** [comment]
You need to completely run your notebook before you push it to GitHub, GitHub or fastpages doesn't run your notebook for you it just converts it to an HTML page.   Let me know if that helps
