### ISSUE TITLE
Math Equation not Properly Rendered

### ISSUE THREAD

**Issue by riven314** [fastai/fastpages#318]
1. Description
I have set ```use_math = true``` in my ```_config.yml```. When test locally in my VS Code IDE, I can see math equations are properly rendered, but when viewed in my blogpost website, they are not rendered properly.

OS: Windows 10

This is what I see in VS Code IDE:
![vscode](https://user-images.githubusercontent.com/21143399/84071356-21157e00-aa00-11ea-94fb-182f460f214e.JPG)

This is what I got in blog website:

![math](https://user-images.githubusercontent.com/21143399/84071141-ced45d00-a9ff-11ea-9db6-b6e5b4b42385.JPG)

2. A link to the notebook or markdown file where the error is occurring
[The link to the blogpost](https://riven314.github.io/2020/06/09/controling_linguistic_style_aspects.html)
[My Markdown File](https://github.com/riven314/riven314.github.io/blob/master/_posts/2020-06-09-controling_linguistic_style_aspects.md)

**Comment by hamelsmu** [comment]
Can you post this one on the [forums](https://forums.fast.ai/c/fastai-users/nbdev/48) please?  I don't know much about equations and there are people who have successfully enabled that there.  Thank you

**Comment by riven314** [comment]
I finally solved the issue. It causes by the fact that the subscript notation (i.e. "_")is not properly protected, as a result, the subscript notation is mistakenly converted to "<em>" when rendering into html. 
Add a "\" in front of every subscript notation (as a means of protection) could solve the problem.
e.g.
```
# subscript is not protected in this case
$p(X_t = 100)$ 

# subscript is protected in this case
$p(X\_t = 100)$
```

**Comment by hamelsmu** [comment]
Thank you for following up with the solution.  This will be helpful for others in the future
