### ISSUE TITLE
Any way to combine hide_input and collapse-show?

### ISSUE THREAD

**Issue by h17** [fastai/fastpages#323]
If you put #hide_input on the top the input is hidden, if you do #collapse-show you can collapse or not the cell? can these two be combined somehow so that you can both hide the input and have a collapse button for that cell?

**Comment by hamelsmu** [comment]
Have you tried it?

**Comment by h17** [comment]
I have
# collapse hide_input
does the same things as 
# hide_input
# collapse
does the same thing as
# hide_input

I suppose the feature is designed specifically for code as it even says "Hide Code" "Show Code" even thought collapse could be more general where you might want to collapse or show sections of output that you want.  Iam not sure if this is fastpage or general markdown..? Can you point to a codebase that handles this?

**Comment by hamelsmu** [comment]
Oh yes, you can only have one command at a time, because this is a way nbdev works.  

perhaps open an issue on nbdev saying you would like to apply multiple flags on a code block.   Look forward to seeing your issue there.  

Thanks

**Comment by hamelsmu** [comment]
This could be a bug in the collapse, I am still not 100% clear on what you desire based on your comment above

**Comment by h17** [comment]
Thank you. Just did.
