### ISSUE TITLE
Render bare URLs as hyperlinks

### ISSUE THREAD

**Issue by drscotthawley** [fastai/fastpages#326]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I add bare URLs in my Markdown editor and see them rendered as hyperlinks, but then when fastpages compiles them they are rendered  on the blog as merely plain text with no opportunity to click on them.  For example typing "https://www.google.com" appears as a clickable link as I'm editing the blog...
 
(^^ btw see how GitHub automatically rendered that bare URL as a clickable link?  That's what I'm used to and that's what I'd like.)

...then I have to go back and manually either add angle-brackets around all the URLs, or add some kind of square-brackets-parentheses construction like `[https://www.google.com](https://www.google.com)` 

**Describe the solution you'd like**
That any properly-formatted bare URL gets rendered as a clickable link, i.e. "blue with an underline". 

**Describe alternatives you've considered**
As I mentioned, manually going back and reformatting the URLs. 

**Additional context**
As mentioned, even GitHub Issues formats bare URLs as hyperlinks by default.  As do many Markdown viewers.

**Comment by drscotthawley** [comment]
Seems this is a "known issue" with Jekyll.  I found multiple feature requests of this sort around the internet for various markdown-based apps.  Kramdown in particular does not support this. 
I'm looking into either writing a little script to auto-add angle brackets around bare URLs, or a Jekyll plugin of some sort.

**Comment by drscotthawley** [comment]
I have a solution,  thanks to "@Mandy8055" on SO.  This will add angle brackets around bare URLs and leave other links (HTML or regular Markdown) alone.  I have tested it with some rather complicated URLs and found it to be compliant. 

Currently this is set up to modify the file in place:
```
perl -i.orig  -pe 's/(?!>)^(https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/\/=]*))(?!>)$/<$1>/g' markdown_file.md
```
where `markdown_file.md` is the post. 
If you want to see what the output will be first without overwriting the file, you can remove the "-i.orig" in the perl command, and it will just print to stdout. 

Whether this gets integrated in everyone's fastpages is, totally up to you.  The `perl` dependence may not be desirable.  I tried to use `sed` instead of `perl`, but I couldn't get the former to accept the regex even after trying various command-line flags.  Whereas with `perl` it just-worked. 

It's easy enough to copy and paste the above command line that users who are having trouble with bare URLs not getting processed they way they like can simply run the above line for each post once, and problem solved. 

I have yet to test this in Jupyter notebooks.

**Comment by drscotthawley** [comment]
`perl` is arguably more powerful, but in case that's regarded as overkill, @Mandy8055 also came up with a `sed` version that works for all the cases I tried:

```bash
sed -i -E 's@^[^<]?(https?://(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&/=]*))[^>]?$@<\1>@gm' markdown_post.md
```

**Comment by hamelsmu** [comment]
I'll go ahead and close this as you have found a workaround.  Thanks for documenting your approach so that other people can find this
