### ISSUE TITLE
cron example and attribution

### ISSUE THREAD

**Issue by h17** [fastai/fastpages#327]
This is not necessarily fast pages feature but I think at least a link on the README of how to setup cron for notebook updates would be great.  I realized this is possible through https://covid19dashboards.com/ that you maintain.  (By the way, amazing well-made cite, I have known about fastpages for some time but it was covid19dashboards that got me onboard).

Back to cron, first time using it on github: my original thought was to just copy and play around with covid19-dashboard/.github/workflows/update-models.yaml and play around but thought if I am going to be using it I should cite it properly.  
Do I just put 
#This workflow used workflow of Hamel  Husain from
#covid19-dashboard/.github/workflows/update-models.yaml
at the top?

Lastly if I understood correctly each yaml is a standalone and does not need to be initialized anywhere, i.e. being in .github/workflows/ would initialize them at commit?

**Comment by hamelsmu** [comment]
I think this is slightly off topic from fastpages, here is some documentation:  https://mlops-github.com/docs/papermill
