### ISSUE TITLE
HTML table not showing on the complete width of the post.

### ISSUE THREAD

**Issue by KushajveerSingh** [fastai/fastpages#329]
I wanted to insert two images side-by-side in my post. Using markdown was not an option, as fastpages would not change the URLs in that case. So I decided to use HTML table in jupyter notebook. I inserted the following code in the markdown cell of jupyter notebook.

```html
<table style="width:100%">
    <tr>
        <td><img src="https://raw.githubusercontent.com/KushajveerSingh/blog/master/images/extra_images/post_004/01.png"></td>
        <td><img src="https://raw.githubusercontent.com/KushajveerSingh/blog/master/images/extra_images/post_004/02.png"></td>
    </tr>
    <tr>
        <td colspan="2"><center>Figure 1. Caption</center></td>
    </tr>
</table>
```
The problem I am facing right now is the HTML table is not being rendered for the complete width of the post, as shown in the picture below.

![ab](https://user-images.githubusercontent.com/24699564/85162842-9cd4bd80-b27f-11ea-8794-1ad50bb8261b.png)

**Comment by hamelsmu** [comment]
Sounds like you figured it out https://forums.fast.ai/t/nbdev-fastpages-how-to-insert-images-side-by-side/73500/5
