### ISSUE TITLE
Fold the comment section

### ISSUE THREAD

**Issue by rednafi** [fastai/fastpages#332]
The *uttarances* comment section doesn't fold. So when the number of comments is high, it gets tedious to scroll all the way down.

![Screenshot from 2020-06-22 01-55-14](https://user-images.githubusercontent.com/30027932/85233865-794e7600-b42b-11ea-8276-dc869dc73934.png)

An option to hide and fold the comment section can improve readability here.

**Comment by hamelsmu** [comment]
This is something you will have to contribute upstream to `uttarances`
