### ISSUE TITLE
Subscribe icon is partially hidden

### ISSUE THREAD

**Issue by armsp** [fastai/fastpages#334]
This is a partial screenshot of the [official blog](https://fastpages.fast.ai/) -
![image](https://user-images.githubusercontent.com/12681262/85325782-d446a280-b4e9-11ea-8a27-3f22b5525a2a.png)
As you can see that the "Subscribe" icon is partially hidden in the footer section.

I am not able to find a html `_layout` or `_includes` file that would have the code for the footer.
Any idea where those files are so that I may work on a solution?

**Comment by hamelsmu** [comment]
Fixed by https://github.com/fastai/fastpages/pull/337
