### ISSUE TITLE
Using fastpages github action on other blogs

### ISSUE THREAD

**Issue by chekos** [fastai/fastpages#340]
The problem: When I use the fastpages github action on my own blog with the flag `BOOL_SAVE_MARKDOWN` set to true I end up stuck in a loop as the Bot is commiting to master. 

<img width="924" alt="Screen Shot 2020-06-30 at 9 05 51 AM" src="https://user-images.githubusercontent.com/28694175/86149513-e6f44500-bab0-11ea-8e47-a2b1233012db.png">

What would be the best way to stop this from happening?
I tried using `if: "!contains(github.event.commits.message, 'Bot')"` and variations of the same idea but i can't seem to be able to skip triggering my build jekyll action. Is there anything specific about the bot updates i can use to filter out those commits? using the head_commit or commits.message doesn't seem to work.

Any help would be greatly appreciated, thanks!

**Comment by hamelsmu** [comment]
Yes this is exactly why this option is turned off by default.  You have to pull the changes locally each time GitHub makes a change on your behalf.  It is not recommended, and is only used in a special case where you need to troubleshoot.  

Otherwhise, I would suggest you only do this conversion locally (see the development guide in the README), without using GitHub Actions.
