### ISSUE TITLE
First PR was not triggered

### ISSUE THREAD

**Issue by CexyNature** [fastai/fastpages#342]
After following the setup instructions, the first PR was not triggered.
```
- Generate a copy of this repo by clicking on this link. Name your repo anything you like except {your-username}.github.io.
- GitHub Actions will automatically open a PR on your new repository ~ 30 seconds after the copy is created. Follow the instructions in that PR to continue.
```

Four days ago I was able to copy the repo successfully. Today, I have tried twice without success.  I cannot see any recent commit in the last few days that might be causing the issue (an issue in the GitHub side?_

Thanks for this great tool.

**Comment by hamelsmu** [comment]
There appears to have been some [recent issues with GitHub](https://www.githubstatus.com/).  I [just tested it](https://github.com/hamelsmu/test-this-now/pull/1) and everything works for me.

**Comment by marcingminski** [comment]
Hi there, did you eventually get the PR? I have the same problem. Tried multiple times and not getting any. Not sure where to go from here. I'm new to fastpages, love the concept but don't know it well enough to figure out what to do now.

**Comment by hamelsmu** [comment]
> Enable local and third party Actions for this repository) I got the PR. Thanks. Apologies for trouble but it may be worth mentioning this in the instruction?

@marcingminski please submit a PR to edit the instruction

**Comment by kennedykwangari** [comment]
After following the setup instructions, the first PR was not triggered. Tried  in the last 5 days with no success.

**Comment by hamelsmu** [comment]
@kennedykwangari you must have not enabled Actions (see the instructions, as well as the comments in this issue).  I have [tested it just now](https://github.com/hamelsmu/test-07-22-2021), and it works.

**Comment by kennedykwangari** [comment]
@hamelsmu  I have enabled local and third party Actions and followed all the instructions shared but to no avail.....

**Comment by hamelsmu** [comment]
@kennedykwangari its very difficult to help you because you are not pointing me to a reproducible public example. 

I am only left to guess on what your issue to be:

[Your repo](https://github.com/kennedykwangari/kennedykwangari.github.io) isn't using fastpages, its using fast_template.

**Comment by hamelsmu** [comment]
@kennedykwangari Additionally, I can see that [you already have a fastpages repo](https://github.com/kennedykwangari/Data-Interviews-Decoded) and [blog that is working correctly](https://kennedykwangari.github.io/Data-Interviews-Decoded/) so it appears that everything is working correctly.
