### ISSUE TITLE
documentation(setup)

### ISSUE THREAD

**Issue by project-delphi** [fastai/fastpages#346]
Following current [docs](https://github.com/fastai/fastpages#setup-instructions) on setup don't mention copying all branches option of `click on this page` link. Without that, github actions doesn't trigger. Not sure if the option to include all branches is a new feature in github template cloning.
<img width="1137" alt="Screen Shot 2020-07-02 at 9 48 32 AM" src="https://user-images.githubusercontent.com/864506/86368363-163eb980-bc4b-11ea-91c9-5d8d9c8f8ab5.png">

**Comment by hamelsmu** [comment]
I was not able to reproduce this issue, can you try again?

**Comment by hamelsmu** [comment]
I [was not able to reproduce this error](https://github.com/hamelsmu/blog/pulls) you have to be patient, it can take ~ 60 seconds to generate a PR
