### ISSUE TITLE
matplotlib: Horizontal overflow and <!DOCTYPE svg PUBLIC ...>

### ISSUE THREAD

**Issue by DavidWalz** [fastai/fastpages#347]
The matplotlib backend for jupyter inline plots stores figures as svg by default. In fastpages these figure overflow horizontally and a
```
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"> 
```
is shown in front of every figure. The latter was mentioned in https://forums.fast.ai/t/fastpages-a-few-hiccups/64457 .
An example can be seen [here](https://davidwalz.github.io/fastpages/2020/07/04/plotting.html) with the corresponding notebook [here](https://github.com/DavidWalz/fastpages/blob/master/_notebooks/2020-07-04-plotting.ipynb).

A workaround is to use "png" as format, see [here](https://davidwalz.github.io/fastpages/2020/07/05/plotting-png.html)
```python
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('png')
```

**Comment by hamelsmu** [comment]
It is not clear that this is a bug.  Some people prefer that their charts are allowed to overflow and control the width themselves appropriately.  You can place a scrollbar so your charts do not overflow with this in `custom-styles.css`

```css
  .output_wrapper{
    overflow: scroll;
  }
```

What do you think?

**Comment by hamelsmu** [comment]
When I first added this by default, some folks didn't like it because they wanted their charts to extend slightly past the margin.   Therefore, we made the hard decision to let people handle their charts on their own appropriately.  

Note that when you have a mobile device or smaller screen the scrollbar will be enabled automatically.

**Comment by hamelsmu** [comment]
Nevermind, more I think about it I think you are right, I think the old thinking is bad.  I will give everything a scrollbar.  This has been fixed in #348 

You can upgrade fastpages per the instructions on the README to pull the latest change.

**Comment by DavidWalz** [comment]
Thank you Hamel!

The behaviour is still different for svg and png matplotlib images in notebooks that are larger than the text. While the former now have a scrollbar, the latter are rescaled to the text width [example](https://davidwalz.github.io/fastpages/2020/07/05/plotting-png.html). I think it would be good if the rendering would be consistent. My personal preference is rescaling, but for that I could just as well create figures of the correct size. 

Also, the <!DOCTYPE svg PUBLIC ...> tag still shows up for svgs.

**Comment by DavidWalz** [comment]
ping @hamelsmu

**Comment by hamelsmu** [comment]
I have no idea how to fix this.  It seems that the doctype declaration that
matplotlib spits out is unnecessary but I couldn’t find how to turn it off.


Perhaps you can also do some research and let me know if you find any ideas
for solutions.  I wonder if you save the file and then load it in a
markdown cell ![](image.svg) if that works or not

**Comment by hamelsmu** [comment]
Closing this issue because it seems like the best fix is something upstream with matplotlib.  There appears to be a modality that works and can be modified by the end user
