### ISSUE TITLE
Upgrade deletes user content

### ISSUE THREAD

**Issue by prabhant** [fastai/fastpages#350]
Hi, 
During the upgrade process fastpages delete the user content in about.md,
Like here: https://github.com/openml/blog/commit/9ddecc00d85cecbb26f9d1e627941900bc5c494f#diff-578149caa896d898111580a7a04f8ad8

**Comment by hamelsmu** [comment]
You cannot use automated upgrades if you plan on customizing the css or HTML of the site.  This is in the README, thanks!
