### ISSUE TITLE
Markdown numbered lists not rendering correctly

### ISSUE THREAD

**Issue by tiega** [fastai/fastpages#352]
## Required information

1. Steps to reproduce the problem

Write a numbered list in markdown with a paragraph in between the list entries. The numbering of the rendered HTML will not follow the supplied numbers in markdown.

### Buggy behaviour in fastpages:
https://tiega.github.io/fastblog/2020/01/01/bug-test.html
<img width="633" alt="Screen Shot 2020-07-09 at 1 22 57 AM" src="https://user-images.githubusercontent.com/30088608/86950428-c13b0000-c182-11ea-99b8-b2d26ee9a0c0.png">

### Expected behaviour in Github markdown preview:
https://github.com/tiega/fastblog/blob/master/_posts/2020-01-01-bug-test.md
<img width="442" alt="Screen Shot 2020-07-09 at 1 23 33 AM" src="https://user-images.githubusercontent.com/30088608/86950527-d31ca300-c182-11ea-8516-f8f0d537942e.png">

2. A link to the notebook or markdown file where the error is occurring

Links provided above.

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

See above.

Fastpages is a lovely project and is by far my favourite blogging tool. Thanks Hamel and the rest of the FastAI team for your incredible work!

**Comment by hamelsmu** [comment]
Jekyll / fastpages is currently using [kramdown](https://jekyllrb.com/docs/configuration/markdown/) and the limitations on which this occurs falls on the way Jekyll is rendering pages.  

I would open an issue with those repositories on GitHub instead of this one, as this relies on those to operate.  Thanks

**Comment by sohang3112** [comment]
I am facing the same issue - is there any work around for this?
