### ISSUE TITLE
Fixed-width font in collapsed code blocks

### ISSUE THREAD

**Issue by MaxGhenis** [fastai/fastpages#354]
**Is your feature request related to a problem? Please describe.**
Is there a way to make collapsed code blocks a fixed width font? e.g. this is from the documentation's [notebook blog post](https://fastpages.fast.ai/jupyter/2020/02/20/test.html):
![image](https://user-images.githubusercontent.com/6076111/87359127-162c9c80-c51c-11ea-94b5-6135c03de7cb.png)

**Comment by hamelsmu** [comment]
Yes, you can customize the CSS.  See [Customizing Fastpages](https://github.com/fastai/fastpages#customizing-fastpages)
