### ISSUE TITLE
Issue with enabling RSS feed on fastpages

### ISSUE THREAD

**Issue by Abhiswain97** [fastai/fastpages#356]
Steps to reproduce the problem:
1. Go to [*this*](https://abhiswain97.github.io/ListeningToLife/) link.
2. Click on the `Subscribe` button.

Screenshot of error:
![RSS_error](https://user-images.githubusercontent.com/54038552/87364611-bcff5000-c591-11ea-9bba-fa5d292dfed1.png)

**Comment by hamelsmu** [comment]
You have to use an RSS feed https://www.lifewire.com/what-is-an-rss-feed-4684568
