### ISSUE TITLE
A way to implement fastpages on an existing package repo

### ISSUE THREAD

**Issue by enzoampil** [fastai/fastpages#357]
Right now, I have an existing repo that I want to have an official website for, and turn the example jupyter notebooks into "blog posts".

Is there a way to implement fastpages on an existing repo?

The approach that's top of mind would be to have a separate repo for the website, but this would require that I migrate the jupyter notebooks to this repo, and to do the same thing for succeeding notebooks. I was hoping to find a way to avoid this migration.

**Comment by hamelsmu** [comment]
I would still have a seperate repo for sanity, but then copy over the notebooks to the appropriate repo with fastpages with a GitHub Action.   

What do you think?

**Comment by enzoampil** [comment]
@hamelsmu Oh if this can be done automatically with a github action, then that would be great! 

Would you happen to have have a resource to help me get started doing this?

**Comment by hamelsmu** [comment]
Here are some resources:

- see this getting started talk: https://youtu.be/S-kn4mmlxFU
- see this article: https://fastpages.fast.ai/actions/markdown/2020/03/06/fastpages-actions.html

Rough outline:

- From your "code repo" create an action that triggers anytime you update a notebook in your repo, that:
     - Clones your other blog repo
     - Copy your notebooks into your blog repo
     - Commit and push the changes to your blog repo

You will likely have to upload an SSH key as a secret into Actions to allow you to push to your new repo.  

You can see an example here where I check out two repos and copy contents of one into the other https://github.com/fastai/fastpages/blob/master/.github/workflows/upgrade.yaml#L64-L75

You will have to figure out the best way of authenticating from within the Actions context.  It is definitely a learning experience but well worth it!.  

I'll go ahead and close this issue, but good luck!  Let me know how it goes

**Comment by enzoampil** [comment]
Thanks so much @hamelsmu ! will let you know :)
