### ISSUE TITLE
Youtube embed is not responsive on smaller screens.

### ISSUE THREAD

**Issue by PseudoCodeNerd** [fastai/fastpages#358]
https://github.com/fastai/fastpages/blob/c463c5c28e1ce9d365778eabc8a5c94bc4788730/_includes/youtube.html#L8
Ideally on reducing browser width, the youtube embed should be smaller to keep it within the screen. This might be due to a bug in the styling. `overflow` might be the culprit here. Attaching screenshots to show the bug.

<p float="left">
  <img src="https://user-images.githubusercontent.com/33770878/87623777-caf4d280-c743-11ea-8d5e-dedf523a4a10.png" width="400" />
  <img src="https://cdn.discordapp.com/attachments/730755633493835778/733163849678717078/Screenshot_20200716-090107_Chrome.jpg" width="400" /> 
</p>

Both screenshots are on a Samsung Galaxy S8 with a viewport of 360x740. The first image is at normal page zoom while the second is zoomed out to show the overflowing youtube block.

I can fix this.

*In progress: Adding Troubleshooting Guide info*.

**Comment by hamelsmu** [comment]
> I can fix this.

Can you please submit a pull request?

**Comment by hamelsmu** [comment]
Closing this for now look forward to your PR

**Comment by xpire** [comment]
@hamelsmu could you look at my PR?

**Comment by JayThibs** [comment]
Is this merged? Because I have this issue on my website.
