### ISSUE TITLE
Is there a simple way to add a package's documentation to fastpages?

### ISSUE THREAD

**Issue by enzoampil** [fastai/fastpages#362]
I'm currently using fastpages with a separate repo to show blog posts related to a separate python package in its own github repo. Is there a simple way to integrate the documentation of that package in fastpages as well? Or would you recommend separate websites for the docs and the blog posts?

**Comment by hamelsmu** [comment]
If you are trying to document a python package I would recommend checking out nbdev as they have docs generation for this purpose.  To answer your question I recommend a separate fastpages repo as things can become cluttered 

I feel that fastpages is really meant for blogs it’s not so great for docs there are other things that  are probably a better fit like nbdev or google “just the docs”

**Comment by enzoampil** [comment]
Got it thanks again! @hamelsmu
