### ISSUE TITLE
PR is no longer created on copy (at least within 10 minutes)

### ISSUE THREAD

**Issue by h17** [fastai/fastpages#369]
Previously created multiple repositories from fastpages template and something changed.  

Now when I follow step 1
"Generate a copy of this repo by clicking on this link. Name your repo anything you like except {your-username}.github.io."
Step 2 
"GitHub Actions will automatically open a PR on your new repository ~ 30 seconds after the copy is created. Follow the instructions in that PR to continue."
either does not happen or takes way longer (10 minutes passed).

I tried with both "copy all branches" (which I don't think is needed) just in case; same result.

see for example:
https://github.com/h17/fastpages-test

**Comment by hamelsmu** [comment]
Please refresh your browser. the PR was opened https://github.com/h17/fastpages-test/pull/1
