### ISSUE TITLE
Erroring out  during auto upgrade

### ISSUE THREAD

**Issue by byteshiva** [fastai/fastpages#373]
I tried doing upgrade but failed with following error.
```
cp: cannot stat '../current_files/_sass/minima/custom-variables.scss': No such file or directory
```

Ran auto upgrade twice but got the same error
Details available at :
https://github.com/byteshiva/blog/runs/930438981?check_suite_focus=true
https://github.com/byteshiva/blog/runs/930435228?check_suite_focus=true

**Comment by byteshiva** [comment]
Failing after the fix upgrade

**Comment by hamelsmu** [comment]
See my comment on #377 

P.S. it is not necessary to tag me on two issues about the same thing
