### ISSUE TITLE
How to add a custom image as a thumbnail to each blog post when link is shared?

### ISSUE THREAD

**Issue by enzoampil** [fastai/fastpages#378]
I've had a great experience writing blog posts with fastpages, but then I noticed that when I share the link to the blog post, there's no thumbnail that comes with sharing the link (e.g. with this [link](https://enzoampil.github.io/fastquant-blog/grid%20search/backtest/2020/04/20/backtest_with_grid_search.html)). For context, this is the behaviour I'm used to since Medium has this built in when you write blogs on their platform.

I was wondering if there's a way to do this easily with fastpages?

Thanks! :smile:

**Comment by hamelsmu** [comment]
yes.  Please read the README

![image](https://user-images.githubusercontent.com/1483922/89144205-dac13480-d501-11ea-8b08-a138796d2af6.png)

**Comment by enzoampil** [comment]
Apologies I missed that. Thank you!
