### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by vmanot** [fastai/fastpages#379]
**Is your feature request related to a problem? Please describe.**
There's no problem per se.

**Describe the solution you'd like**
Basic dark mode support.

**Comment by hamelsmu** [comment]
I tried to do this already, and it is a nightmare to get it to work with fastpages especially with syntax highlighting and everything else.  

If you look at jekyll/minima the syntax highlighting doesn't quite work well there in the dark theme.  If someone with HTML / CSS Design Experience wants to take this on  let me know

**Comment by hamelsmu** [comment]
I don't think this can be supported without significant changes to the project.  Closing this issue
