### ISSUE TITLE
How do I debug failed build?

### ISSUE THREAD

**Issue by misza222** [fastai/fastpages#385]
## I get an error during the automated build

I wrote a post in ipynb and during the build process, when converting to md, there is an error. How do I get my hands on md file so I can see where the problem is?

![image](https://user-images.githubusercontent.com/89839/89861503-4eb8a800-dba6-11ea-9409-e4b8be6a106e.png)

How do I debug such problems?

**Comment by hamelsmu** [comment]
Did you try the Troubleshooting Guide linked above?  Give that a go and reopen the issue with more information please.

**Comment by misza222** [comment]
Yes, that was the colon in the post subtitle. Thanks @hamelsmu
