### ISSUE TITLE
Local images not rendering

### ISSUE THREAD

**Issue by jordwil** [fastai/fastpages#387]
Link to notebook: 
https://github.com/jordwil/ds_blog/blob/master/_notebooks/2020-07-30-int-project-gold.ipynb

Corresponding blog post will not display any local image that I provide a path to with the ![](<path/to/img>) notation.

**Comment by hamelsmu** [comment]
Please follow the troublehsooting guide carefully to try to debug. 

I was not able to reproduce your error.  My site: https://hamelsmu.github.io/image-test/machine%20learning/python/eda/cleaning/multi-target/regression/2020/07/30/int-project-gold.html

and minimal repo with your same files for reference: https://github.com/hamelsmu/image-test
