### ISSUE TITLE
Collapsible Markdown Cells

### ISSUE THREAD

**Issue by Robbie-Palmer** [fastai/fastpages#391]
I would like to unobtrusively include paragraphs of additional explanatory text that a reader can optionally dive into.

For example, below a plot, I would like to explain all assumptions made in the calculations.
Casual readers would prefer to skim over these points, others may like having these included to challenge/query/build upon.

I like the `#collapse-hide` tag for this use with code.
I would like to be able to use the same or a similar tag at the top of markdown cells inside a Jupyter notebook.

I have tried to make the additional context separate from the main flow through
1. Boxes / Callouts - but this _draws_ attention
2. Markdown quote with `>` - but this adds emphasis
3. Indentation in a markdown cell - this does make the text smaller and separate, but surrounds it with a purple box, drawing attention
4. Footnotes - This makes the text small and unobtrusive, but need to include `fndetail:` with a number or a string that makes it into a small dot; and it ends the footnote with a link to nowhere.

**Comment by hamelsmu** [comment]
closing issue because it has gone stale, OP has not responded, feel free to reopen if needed

**Comment by Robbie-Palmer** [comment]
Thanks @hamelsmu! Embarrassing case of "let me google that for you" :sweat_smile:
Using a `<details>` tag with plain text fits my use case perfectly.

Unfortunately markdown within the `<details>` tag doesn't render as in the examples, staying in raw format

```
<details>
  <summary>Click to expand!</summary>
  
  ## Heading
  1. A numbered
  2. list
     * With some
     * Sub bullets
</details>
```

Renders as

![image](https://user-images.githubusercontent.com/8760191/91410051-34d1c300-e83e-11ea-9370-5dd6bdaef51a.png)

Instead of:
<details>
  <summary>Click to expand!</summary>
  
  ## Heading
  1. A numbered
  2. list
     * With some
     * Sub bullets
</details>

Not something I'm currently looking to do, but could be a future use case
P.S. Thanks for this amazing platform! :blush:

**Comment by abdksyed** [comment]
Apologies for commenting on already closed issue.

But I tried the collapsed mark down, the fastpage did render the collapse but the structure isn't maintained and font-size is not getting enlarge as other markdown text

Rendered as:

![image](https://user-images.githubusercontent.com/62547949/135710175-cedae31e-04c8-4039-89c3-cd7a51f6a8f4.png)

Desired:
<details>
  <summary>Categories to Super Categories</summary>

  ```
      {
        'cardboard': 'raw_material', 'paper': 'raw_material', 'plastic': 'raw_material',  
        'metal': 'raw_material', 

        'wall-tile': 'wall', 'wall-panel': 'wall',
        'wall-wood': 'wall', 'wall-brick': 'wall', 'wall-stone': 'wall',
        'wall-concrete': 'wall', 'wall-other': 'wall', 

        'ceiling-tile': 'ceiling', 'ceiling-other': 'ceiling', 
        
        'carpet': 'floor', 'floor-tile': 'floor', 'floor-wood': 'floor',
        'floor-marble': 'floor', 'floor-stone': 'floor', 'floor-other': 'floor', 

        'window-blind': 'window', 'window-other': 'window',

        'door-stuff': 'furniture', 'desk-stuff': 'furniture', 'table': 'furniture',
        'shelf': 'furniture', 'cabinet': 'furniture', 'cupboard': 'furniture',
        'mirror-stuff': 'furniture', 'counter': 'furniture', 'light': 'furniture',
        'stairs': 'furniture', 'furniture-other': 'furniture', 

        'rug': 'textile', 'mat': 'textile', 'towel': 'textile', 'napkin': 'textile',
        'clothes': 'textile', 'cloth': 'textile', 'curtain': 'textile',
        'blanket': 'textile', 'pillow': 'textile', 'banner': 'textile','textile-other': 'textile', 

        'fruit': 'food', 'salad': 'food', 'vegetable': 'food', 'food-other': 'food', 

        'house': 'building', 'skyscraper': 'building','bridge': 'building', 
        'tent': 'building', 'roof': 'building', 'building-other': 'building',

        'fence': 'structural', 'cage': 'structural', 'net': 'structural', 'railing': 'structural', 
        'structural-other': 'structural',

        'grass': 'plant', 'tree': 'plant', 'bush': 'plant', 'leaves': 'plant',
        'flower': 'plant', 'branch': 'plant', 'moss': 'plant', 'straw': 'plant',
        'plant-other': 'plant',

        'clouds': 'sky', 'sky-other': 'sky',

        'wood': 'solids', 'rock': 'solids', 'stone': 'solids', 
        'mountain': 'solids', 'hill': 'solids', 'solid-other': 'solids',

        'sand': 'ground', 'snow': 'ground', 'dirt': 'ground', 'mud': 'ground',
        'gravel': 'ground', 'road': 'ground', 'pavement': 'ground','railroad': 'ground',
        'platform': 'ground', 'playingfield': 'ground', 'ground-other': 'ground',

        'fog': 'water', 'river': 'water', 'sea': 'water', 'waterdrops': 'water',
        'water-other': 'water',
        
        'things': 'things', 'water': 'water', 'window': 'window', 'ceiling': 'ceiling',
        'sky': 'sky', 'floor': 'floor', 'food': 'food', 'building': 'building','wall': 'wall'
      }
  ```
  
</details>
