### ISSUE TITLE
moving from old to new blog

### ISSUE THREAD

**Issue by anaveenan** [fastai/fastpages#392]
I had my blog reside in location https://anaveenan.github.io/naveenanarjunan/ but to upgrade I have created a new page with latest version of fast pages https://anaveenan.github.io/anaveenan/. I want to make sure if users use the link https://anaveenan.github.io/naveenanarjunan/  (not able to commit or update this repo because of the old version) it should redirect to https://anaveenan.github.io/anaveenan/ . How can I achieve this ?

**Comment by hamelsmu** [comment]
See this thread on how to redirect things https://forums.fast.ai/t/fastpages-replacing-main-username-github-io-page-w-fastpages/64316

Post on that thread if needed for help once you read it carefully
