### ISSUE TITLE
Demo site is now working ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by ankitbko** [fastai/fastpages#393]
https://fastpages.fast.ai/ does not open. 
![image](https://user-images.githubusercontent.com/3169316/91417682-c9ecb000-e86e-11ea-87f8-1d23962d20db.png)

**Comment by hamelsmu** [comment]
@ankitbko thanks for reporting this

@jph00 is this something to do with the recent migration?

**Comment by hamelsmu** [comment]
its working now!  closing issue
