### ISSUE TITLE
Support for email subscribe form and automatic email plugin

### ISSUE THREAD

**Issue by yashjakhotiya** [fastai/fastpages#394]
**Is your feature request related to a problem? Please describe.**
No, it is a feature that will help users increase their blog reach

**Describe the solution you'd like**
There are two steps here - 

1. fastpages support for a form on home page for blog readers to subscribe via email and store a list of these subscribers.
2. A GitHub action that sends email to this list on every new blog post, detailing the blog.

Although, first step can be fairly simple here, I am not sure about how feasible is the second one.

**Describe alternatives you've considered**
https://gist.github.com/sharu725/744bf9357c62a34d416ba71650a64968 - This Jekyll snippet with Mailchimp seems to be a promising alternative

**Additional context**
Increasing reach of her blog is any serious blogger's primary goal. If this support is added in fastpages, this could make fastpages stand out.

**Comment by hamelsmu** [comment]
I don't think there is an easy way for me to support this without adding a third party paid service like mail chimp.  I'm happy to take a PR if you have a working prototype but I don't know if I want to involve lots of third party tools?  I suggest using the release feature and telling users to subscribe to your repository releases? WDYT?
