### ISSUE TITLE
Conversion of notebooks fails when python dependencies are not met

### ISSUE THREAD

**Issue by codescv** [fastai/fastpages#395]
When I convert a notebook with no Python dependencies installed, the conversion fails with this error:

```
converter_1  | An error occurred while executing the following cell:
converter_1  | ------------------
converter_1  | from nbdev.showdoc import doc
converter_1  | doc(parallel)
converter_1  | ------------------
converter_1  | 
converter_1  | 
converter_1  | NameErrorTraceback (most recent call last)
converter_1  | <ipython-input-2-e7f7c1168dad> in <module>
converter_1  |       1 from nbdev.showdoc import doc
converter_1  | ----> 2 doc(parallel)
converter_1  | 
converter_1  | NameError: name 'parallel' is not defined
converter_1  | NameError: name 'parallel' is not defined
converter_1  | 

```

My question is, why does the converter need to run the notebook while converting?
If my notebook includes a Python program which trains a model on GPU for 5 hours, then the conversion of that notebook will never complete.

**Comment by hamelsmu** [comment]
You have to have nbdev installed to make this work.  See the Development Guide in the README.  There is a Docker container that makes it easy to setup a local development environment.

**Comment by codescv** [comment]
Thanks! I was using `make server` to test, and I was able to work around this issue by adding `!pip install fastai nbdev` in the cell.

But still, why does the converter need to run the notebook? The output is already there. Is there a way to just convert the notebook as is, without actually running it? Since sometimes the notebook can take many hours to run from the beginning to the end.

**Comment by codescv** [comment]
A strange thing I found is, if I have a cell like this:
```
from nbdev.showdoc import doc
from fastcore.all import parallel
```
Then it will raise an error while converting, but if I have a cell like this(tensorflow is NOT installed anywhere):

```
import tensorflow as tf
```
It will not give me any errors.

**Comment by codescv** [comment]
Stranger still, if those two imports are in different cells, no errors will occur:
```
from nbdev.showdoc import doc
```

and
```
from fastcore.all import parallel
```

**Comment by hamelsmu** [comment]
That's kind of strange..... sounds like a potential nbdev issue, but not sure
