### ISSUE TITLE
Make authors section support a link in the post header

### ISSUE THREAD

**Issue by ankitbko** [fastai/fastpages#397]
**Is your feature request related to a problem? Please describe.**
Allow users to specify a hyperlink in Authors section in post header. This could be used to specify co-authors profile/blog and will help reader easy access to author's profile.

**Describe the solution you'd like**
The authors setting in frontmatter can be modified to support a url 

```yaml
author:
  - name: Ankit Sinha
    url: https://linkedin/profile
  - name: Foo
```

Accompanying changes in `post.html`
```
      {%- if page.author -%}
        • {% for author in page.author %}
          <span itemprop="author" itemscope itemtype="http://schema.org/Person">
		  {%- if author.url -%}
		    <a href="{{ author.url }}" target="_blank">
			  <span class="p-author h-card" itemprop="name">{{ author.name }}</span></span>
		    </a>
		  {%- else -%}
			<span class="p-author h-card" itemprop="name">{{ author.name }}</span></span>            
		  {% endif -%}
		  {%- if forloop.last == false %}, {% endif -%}
        {% endfor %}
      {%- endif %}
```
Will result in this
![image](https://user-images.githubusercontent.com/3169316/91835083-85925300-ec66-11ea-9926-36953d1a93a8.png)

**Comment by hamelsmu** [comment]
Great suggestion.  thank you

**Comment by hamelsmu** [comment]
Unforutnately, this will not work for notebooks, only markdown.  this is because nbdev only supports one level of metadata on the notebook, I cannot have nested lists like this.  

One solution I use is to put html in the yaml itself `author: "<a href=''>Hamel</a>"`
