### ISSUE TITLE
unnecessary step when update README and index.html

### ISSUE THREAD

**Issue by deep-diver** [fastai/fastpages#398]
When I update `README.md` and `index.html`, GitHub Action still runs a step `convert notebooks and word docs to posts` which has nothing to do with those files. Especially, `README.md'. 

What do you think?

**Comment by hamelsmu** [comment]
I think its ok.  I don't want to create a single filter for just README.md?

**Comment by deep-diver** [comment]
ok no problem.
I thought I could make a universal filter
but I have found nbdev itself already filters out notebook files which has any changes only.
