### ISSUE TITLE
Title and Meta tags appear twice

### ISSUE THREAD

**Issue by ankitbko** [fastai/fastpages#400]
SEO related tags appear twice in HTML.  This makes search engines rather unhappy. I think this is because `{%- seo -%}` appear twice, once in `head.html` and again in `custom_head.html`
![image](https://user-images.githubusercontent.com/3169316/92121136-8e765680-ee17-11ea-8fe2-c1f3ba327a57.png)

![image](https://user-images.githubusercontent.com/3169316/92121298-bc5b9b00-ee17-11ea-9989-800e1f1833bf.png)

**Comment by hamelsmu** [comment]
Thanks!  I fixed this via #403
