### ISSUE TITLE
Border on all tables if any table is scrollable 

### ISSUE THREAD

**Issue by ankitbko** [fastai/fastpages#409]
Kinda difficult to explain so I will explain 2 scenarios - one which works correctly and other which does not. This issue is regarding border (1px solid black) on tables which are generated from notebook in one case and not generated in other case.

Scenario 1 (bad) - Have 2 (or more) tables in a notebook. One table is small and does not have scroll and another table has scroll bar.
Actual - Both tables have block border due to style injected on .table class on page itself that overrides border:none from fastpages-style,scss
Expected - Tables does not have black border.
Link - https://ankitbko.github.io/blog/2020/09/bulk-import-using-sql-spark-connector-p3/ Scroll down and you will see first table which has an ugly black border. Later in the blog are couple of other tables which has scroll bar. Hiding (`#hide`) these other tables resulted in no black border in the first one.
Image - 
![image](https://user-images.githubusercontent.com/3169316/92512693-cb35b980-f22c-11ea-97ea-b5f2dea570df.png)

Scenario 2 (good) - Single table (same as from scenario 1).
Actual/Expected - Table does not have black border
Link - https://ankitbko.github.io/blog/2020/09/bulk-import-using-sql-spark-connector-p2/  This is exactly same table as from scenario 1 (literally copy paste of the cell). 
Image -
![image](https://user-images.githubusercontent.com/3169316/92512728-dbe62f80-f22c-11ea-97bc-d56ea02f2441.png)

This border is added because of additional style which is added on the page itself. Playing around a little bit I think this is added when any table overflows and scroll bar is rendered. But I may be wrong and more investigation is needed.
![image](https://user-images.githubusercontent.com/3169316/92513008-45663e00-f22d-11ea-8b26-3c825100463c.png)

**Comment by hamelsmu** [comment]
@ankitbko can you open a PR to fix this?

**Comment by ankitbko** [comment]
I can but I am not finding who/what is adding the styles. I *think* the root cause is the [scoped attribute](https://www.w3schools.com/tags/att_scoped.asp) which is not supported now a days. I just cant find anything obvious that is adding this style, tried to search on nbdev too. Do you know which method is handling the tables conversion?

**Comment by hamelsmu** [comment]
I am not sure, I think table conversion is probably happening in nbdev via nbconvert.  However perhaps this is fixible via a css overrride?

**Comment by ankitbko** [comment]
Yes so either I can add `!important` tag to [this place](https://github.com/fastai/fastpages/blob/master/_sass/minima/fastpages-styles.scss#L204) or remove `table: block !important` from [here](https://github.com/fastai/fastpages/blob/master/_sass/minima/fastpages-styles.scss#L200). Both of them seems to solve this issue. You added the `table: block` style in [this](https://github.com/fastai/fastpages/pull/166/files#diff-016edf0eebfc963467c5040d34e17e09R388) PR, is it important? Let me know what works best and I will raise the PR.

**Comment by ankitbko** [comment]
So if we remove `display: block` then the display will depend upon media query and will be set if screen size is less than 1000px. So the border will appear on smaller resolution/display. If we override it with `!important` then it will never show.

![image](https://user-images.githubusercontent.com/3169316/92521828-86654f00-f23b-11ea-82c9-8fd0eb412fbd.png)

**Comment by hamelsmu** [comment]
Are there any downsides to removing `display: block` ?  Does it mess up the
rendering of anything else?

**Comment by ankitbko** [comment]
Doesnt look like in any of my blogs... `display: block` will reappear when screen size is less than 1000px due to media query defined in _base.scss. I will raise a PR to check it in preview.
