### ISSUE TITLE
CI build fails after the recent update to DockerHub image

### ISSUE THREAD

**Issue by machinelearninghelsinki** [fastai/fastpages#411]
## Required information

1. Steps to reproduce the problem
The build was working fine few hours ago and after the new push to Dockerhub  (`hamelsmu/fastpages-nbdev
`)  the CI build fails. To reproduce the error just make changes to index.html 

2. A link to the notebook or markdown file where the error is occurring

Not applicable, since following the same repo as in https://github.com/fastai/fastpages (https://github.com/machinelearninghelsinki/mlstudygroup)

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.
Not applicable

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide]
![error1](https://user-images.githubusercontent.com/71074595/92742162-0d274280-f388-11ea-823d-42f85713d517.png)

**Comment by hamelsmu** [comment]
Thanks! I'm working on it now

**Comment by abhisheksreesaila** [comment]
Just providing additional screenshots for reference. 
![Screen Shot 2020-09-10 at 10 22 28 AM](https://user-images.githubusercontent.com/11252442/92744714-b6057b80-f34f-11ea-9f1b-b5d217c1825c.png)

**Comment by hamelsmu** [comment]
@machinelearninghelsinki @abhisheksreesaila I have fixed this now, can you try re-running and see if this works?

**Comment by machinelearninghelsinki** [comment]
@hamelsmu It works now! Thanks a lot
