### ISSUE TITLE
[Question]: Is there a command-line tool that I use to manually convert notebooks to HTML pages?

### ISSUE THREAD

**Issue by dclong** [fastai/fastpages#413]
Instead of relying on GitHub Actions?

**Comment by hamelsmu** [comment]
you  can use `make convert` per the instructions linked to from the README https://github.com/fastai/fastpages/blob/b4c638b9bf8d3376148d9366f7fa7c61b1a50ef2/_fastpages_docs/DEVELOPMENT.md

**Comment by dclong** [comment]
The doc says `make convert` converts things to `.md`. Is there a way to convert it to HTML locally?

**Comment by hamelsmu** [comment]
Read the development guide, it shows you how to preview the blog locally, which of course includes conversion to HTML
