### ISSUE TITLE
Use nbdev_detach to support copy/pasted images

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastpages#415]
See https://forums.fast.ai/t/fixed-fastpages-cannot-see-build-process-of-github-actions/78719/8

![image](https://user-images.githubusercontent.com/1483922/92960220-1bc23800-f422-11ea-8f51-9b6bec362d4a.png)

**Comment by castorfou** [comment]
I use a workaround that some could find usefull.
When I want to copy/paste an image directly inside a notebook to be turned by nbdev.
I first paste the image in the notebook. 
![gnome-shell-screenshot-P1X160](https://user-images.githubusercontent.com/2387408/125786342-3d0fe58c-6eff-4fa4-9971-fce93edd9b68.png)
Then right click the image, copy image, and paste again.
At that level this is a binary content embedded in the notebook and nbdev will be fine with it.

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
