### ISSUE TITLE
Referring to "fastcore: An Underrated Python Library" notebook: NameError: name 'delegates' is not defined; name 'PrePostInitMeta' is not defined

### ISSUE THREAD

**Issue by chho-work** [fastai/fastpages#419]
Ref: notebook: "fastcore: An Underrated Python Library"

Thanks for sharing! Great work!
I opened the Colab version, installed the required packages and restarted the runtime as instructed. 

Run into the following:
![Screenshot from 2020-09-17 09-48-24](https://user-images.githubusercontent.com/58581036/93410861-6c2b1100-f8cc-11ea-998a-8638368e9656.png)

And also
![Screenshot from 2020-09-17 10-00-17](https://user-images.githubusercontent.com/58581036/93410967-a8f70800-f8cc-11ea-8596-4a5d4ea3f0a4.png)

All other cell worked! 
Don't know if this is the right place to report this.  If not, pls help and indicate the right location.  

Many thanks!

**Comment by hamelsmu** [comment]
Thanks I fixed this now.
