### ISSUE TITLE
Add social media "share" button for blogpost

### ISSUE THREAD

**Issue by inc0** [fastai/fastpages#42]
I think it's pretty standard by now to have "tweet this post" kind of buttons... we should add them too

**Comment by hamelsmu** [comment]
Excellent idea

**Comment by mikonapoli** [comment]
Would something like this work? https://sourabhbajaj.com/blog/2017/10/29/adding-social-media-share-icons-to-jekyll/

**Comment by hamelsmu** [comment]
@mikonapoli maybe except that styling doesn't really mesh well with minima, would be great if we could find something that isn't as loud

**Comment by drscotthawley** [comment]
Hey related to this:
 I just noticed that if I add meta tags for "image: " and "description:" to the top of a post -- even when using the minima theme, then both Twitter and Facebook will use the image & description for a preview "card" when you post the blog posts' URL! 
Nice.  This should go in the docs. ;-).  I can PR this after I've done a bit more testing.

**Comment by drscotthawley** [comment]
Correction to previous comment:
Newest versions of fastpages and nbdev (from today) actually break this for notebooks. :-1:   So now images & descriptions no longer appear on Twitter or Facebook. 
Still works for markdown posts though.

**Comment by drscotthawley** [comment]
@hamelsmu  Here are some share buttons that look good with minima!  
https://jekyllcodex.org/without-plugin/share-buttons/

I just installed them on my blog, by downloading & adding  `_includes/share-buttons.html` and [by modifying my `_layouts/post.html`](https://github.com/drscotthawley/devblog3/blob/master/_layouts/post.html) , and the result appears just above the Utterances comments in any of my posts, e.g.: https://drscotthawley.github.io/devblog3/2018/12/16/Parallelizing-Python-Simplified.html

However when I actually try to use them:
- the Twitter one does nothing - it pulls up twitter but there's no post
- the Facebook one pulls of Facebook but produces "Page not Found".  
- the Email one opens my email client but it's a blank email.

Maybe I did it wrong and someone else will have success with this set of buttons.

**Comment by hamelsmu** [comment]
> Correction to previous comment:Newest versions of fastpages and nbdev (from today) actually 
 break this for notebooks. 👎 So now preview images & descriptions no longer appear on Twitter or Facebook. 

This works for me, so not sure why its not working for you.  Also, please open a seperate issue

**Comment by hamelsmu** [comment]
@drscotthawley I like this jekyll social media thing the style is really nice!  I think we will use it.  good find!

**Comment by hamelsmu** [comment]
going to triage this issue out in favor of other issues.  Not convinced that this functionality is useful versus the surface area that expands of what must be maintained and documented.

Happy to keep discussing
