### ISSUE TITLE
Support rendering `mermaid` by adding plugin `jekyll-spaceship`

### ISSUE THREAD

**Issue by sunbc0120** [fastai/fastpages#420]
**Is your feature request related to a problem? Please describe.**
In markdown posts, sometime people would use `mermaid` to display flowcharts graphs. 

**Describe the solution you'd like**
To get `mermaid` work in jekyll, a plugin needs to be installed [jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship#installation)

**Describe alternatives you've considered**
Searched through the documentation but haven't found alternative ways to write flowcharts.

**Additional context**
Can create a PR if it's Ok.

**Comment by hamelsmu** [comment]
You can add this Gem after you create your fastpages copy, why would you want to add it for everyone?  Is it that useful?  What can you do with this?  Is this just for flowcharts?

**Comment by sunbc0120** [comment]
> You can add this Gem after you create your fastpages copy, why would you want to add it for everyone? Is it that useful? What can you do with this? Is this just for flowcharts?

Sure, can add on my own copy, but under a section with comments saying
`Everything below here should be left alone. Modifications may break fastpages`.

The best practise would be to have this supported from the root repo.

`mermaid` is just for flowcharts, but `jekyll-spaceship` supports many other features as mentioned by their [doc](https://github.com/jeffreytse/jekyll-spaceship#installation).

    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
 
It's up to you if want to add these for everyone.

**Comment by hamelsmu** [comment]
I experimented with this and this adds tons of dependencies to the build for everyone.  I'm going to pass on this particular plugin.  I suggest you add it if you want
