### ISSUE TITLE
Add YouTube channel and LinkedIn profile links as a site wide configuration option (like twitter_username)

### ISSUE THREAD

**Issue by owenlamont** [fastai/fastpages#421]
**Is your feature request related to a problem? Please describe.**
I'd like the ability to add GitHub and Twitter links to the footer of my FastPages blog - but would like to be able to refer readers to my LinkedIn page and YouTube channel too.

**Describe the solution you'd like**
I'd like an equivalent to the twitter_username site wide configuration to be able to refer to a the above mentioned resources which would appear in the footer next to the Twitter and GitHub links with an appropriate logo image.

**Describe alternatives you've considered**
I'm not sure... I can link within posts to those resources but from a user interface approach I think it would be so much better if those pages could be linked to in the same place as the GitHub and Twitter links in the footer.

**Additional context**
It'd be great to have links with images adjacent to the existing GitHub / Twitter footer ones

![github_twitter_links](https://user-images.githubusercontent.com/12672027/93694100-5d499600-fb3a-11ea-88dd-d51c1aba051c.png)

**Comment by hamelsmu** [comment]
Can you open an issue on Jekyll / Minima?  Looks like this  is supported in v 3.0.0 onwards but they haven't yet cut a release. https://github.com/jekyll/minima

**Comment by owenlamont** [comment]
Thanks for the info... if it is already in progress I'll guess I'll just have to be patient for their version 3 release. I'm not a Ruby dev but when Minima 3 is released I should raise a new issue to update the Gemfile here?

**Comment by hamelsmu** [comment]
It’s unclear when they will cut a release I have no idea best is to ask them
