### ISSUE TITLE
Unable to convert notebook to fastpage - Github Action failing

### ISSUE THREAD

**Issue by srujanreddyj** [fastai/fastpages#427]
## Required information

1. Steps to reproduce the problem
   1. Uploaded a .ipynb file to convert into fastpages.

2. A link to the notebook or markdown file where the error is occurring
   1. https://github.com/srujanreddyj/mlblog/blob/master/_notebooks/2020-09-22-m5-forecasting-1.ipynb -- error started after uploading this notebook

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.
    1. Error in github actions 
     EntryFilter: excluded /docker-compose.yml
           Reading: _posts/2020-09-22-m5-forecasting-1.md
             Error: YAML Exception reading /github/workspace/_posts/2020-09-22-m5-forecasting-1.md: (<unknown>): mapping values are not allowed in this context at line 5 column 18
      Remote Theme: Cleaning up /tmp/jekyll-remote-theme-20200922-1-porxbw
/usr/gem/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `parse': (<unknown>): mapping values are not allowed in this context at line 5 column 18 (Psych::SyntaxError)

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).
    1. CI/build-site --  
![image](https://user-images.githubusercontent.com/48939255/93969866-7ddc4080-fd32-11ea-9cdd-739295ba5380.png)
 https://pipelines.actions.githubusercontent.com/2H2ZPPzEFDeQ2Ob0ZaOp0m1gGYYbKDPH45FvZwEnM8Jyytn9ad/_apis/pipelines/1/runs/19/signedlogcontent/3?urlExpires=2020-09-23T05%3A18%3A14.4516751Z&urlSigningMethod=HMACV1&urlSignature=Q7S%2B%2Fm41Q5t12UQgOIjyh%2FtpKFVJLUSZqKKxmcnrGOY%3D

**Comment by Shubhamai** [comment]
Hi @srujanreddyj , did your issue solved? How did you solve the issue? Because I am also getting the same problem.

**Comment by srujanreddyj** [comment]
@Shubhamai No Shubham, I couldn't solve it.

**Comment by hamelsmu** [comment]
There is something wrong with your front matter in your notebook.

**Comment by nitishsaDire** [comment]
The issue is with the front matter. For me, it was with the title of my blog. 
The earlier title was, Optimisation Algorithms: Part I
I removed ":" as mentioned infrequent errors in https://github.com/fastai/fastpages/blob/master/_fastpages_docs/TROUBLESHOOTING.md

Without ":" there was no error in the build
