### ISSUE TITLE
Initial PR is not created, despite opening Action settings.

### ISSUE THREAD

**Issue by joshkraft** [fastai/fastpages#429]
## Required information

1. Steps to reproduce the problem

I have generated a few repos by following 'Generate a copy of this repo by clicking on this link.'. I am creating public repositories, not using my username as the title, and have double-checked at 'All Actions' are allowed. I am still unable to see any initial pull request created.

2. A link to the notebook or markdown file where the error is occurring

I have created/deleted a few repos after waiting for a few hours on each. Here is the latest: https://github.com/joshkraft/joshkraft-ml-blog/

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

**Comment by nkleinbaer** [comment]
I had this same issue, but found a workaround. In addition to ensuring that 'All Actions' are allowed in the settings menu, I also had to enable them from the 'Actions' tab:
![image](https://user-images.githubusercontent.com/47011214/95365322-3657c780-088f-11eb-864f-96e7aeae935c.png)

If you look at the setup.yaml you'll notice that the workflow runs on push events, and will only run if the commit message is 'Initial commit'.

https://github.com/fastai/fastpages/blob/894e9f3ef9f566b3225b5c77e70be366eaf90cf4/.github/workflows/setup.yaml#L1-L8

So as a workaround

1. Ensure that you have enabled actions on the repository.
2. Add a new file to the repo and name the commit 'Initial commit'
3. Go to the actions tab and ensure that the setup workflow finished. A PR should appear once it finishes with a green checkmark. If it fails you should be able to click on it and see where it failed.

![image](https://user-images.githubusercontent.com/47011214/95366248-6a7fb800-0890-11eb-9912-bb04cc771f4d.png)

**Comment by joshkraft** [comment]
Ah, great, thanks @nkleinbaer ! I can confirm that following the above workaround resolved my issue.

**Comment by ravindrabharathi** [comment]
Thanks @nkleinbaer . I too faced the same issue as @joshkraft . It's now resolved .

**Comment by nkleinbaer** [comment]
@hamelsmu  I wonder if it might be worth amending the installation instructions or the FAQ to explaining these additional steps? I'm not sure if there has been a change to how Github handles Actions/Workflows, but it seems that now you must manually enable actions after creating the repository from the template. The instructions mention that you may need to enable actions, but it does not specify that you will need to push a commit with the message 'Initial commit' after doing so.

**Comment by hamelsmu** [comment]
@nkleinbaer can you expand upon why Actions were disabled for you?   Are you part of an organization that has that disabled by default?

**Comment by joshkraft** [comment]
I am using a personal account, with no organization attached. When I use the link to generate a FastPages repo, the Actions tab displays this: 
<img width="551" alt="Screen Shot 2020-10-08 at 3 35 27 PM" src="https://user-images.githubusercontent.com/30248392/95505183-f6bad980-097b-11eb-9462-c40ee02dbe1f.png">

Once I enable that and send in another 'Initial Commit', everything works as expected.

**Comment by hamelsmu** [comment]
Ok I'm going to have to fix this by creating something a bit easier than forcing you to create a commit?    If anyone has any recommendations for workflows please let me know

**Comment by hamelsmu** [comment]
I have some ideas.  Stay tuned.  I think I can fix this.

**Comment by hamelsmu** [comment]
Ok I fixed this by adding new instructions to the repo.  Thanks, everyone!  Thanks for the nudge @joshkraft

**Comment by nkleinbaer** [comment]
> @nkleinbaer can you expand upon why Actions were disabled for you? Are you part of an organization that has that disabled by default?

I'm honestly not sure why actions are disable for me. Similar to @joshkraft I am using a personal account that is not connected with any organization. I noticed that actions are not disabled if I create a new empty repository - only if I use the fastai/fastpages template.

**Comment by nkleinbaer** [comment]
Thanks @hamelsmu, perhaps irrelevant now but it seems that there are some others experiencing the same issue over the last couple of days: https://github.community/t/workflow-isnt-enabled-in-repos-generated-from-template/136421/5

**Comment by hamelsmu** [comment]
@nkleinbaer thanks for pointing that out.  I’ll raise this issue with GitHub to find out more
