### ISSUE TITLE
Calculate Reading Time

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastpages#43]
https://blog.webjeda.com/jekyll-snippets/

It would be good if the reading time could be made next to the date in the way [Medium](https://medium.com/) does

![image](https://user-images.githubusercontent.com/1483922/74597322-7de4c700-5012-11ea-9ccc-0a73eeb029b4.png)

Which requires editing the `_layout/post.html` file.  I would recommend encapulating the reading time in a `_layouts` file and including it in `_layout/post.html`

**Comment by tyoc213** [comment]
Hi there, right now seting things up at [dl123.tyoc.mx](dl123.tyoc.mx) with a 404 and this :)

>  Your site is having problems building: The tag twitter on line 73 in _posts/2020-01-14-test-markdown-post.md is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.

**Comment by hamelsmu** [comment]
@tyoc213 I [looked at your repo](https://github.com/tyoc213/tyoc213.github.com) and it looks like you haven't followed the instructions in this repo for some reason?  Can you please go through all the steps carefully? 

- why don't you have `gh-pages` branch?
- it doesn't look like you used this repo as a template
- etc

Thanks

**Comment by tyoc213** [comment]
The principal branch is the `gh-pages` not master :) https://github.com/tyoc213/dl123 but maybe I will try again :)I skiped when I started so maybe is a problem with order I executed things...

And I was trying to report this [development guide ](https://github.com/fastai/fastpages/blob/_dev_tools/README.md) from the contributing.md

**Comment by tyoc213** [comment]
Well, I tried with [dl111](https://github.com/tyoc213/dl111/tree/gh-pages) but did obtain same result, by the way CNAME is created when you set the url in the settings of the repo.

Also as pointed out in https://github.com/fastai/fastpages/issues/49#issuecomment-586625453 there is an error with the tweetcards... for first build and consecutive ones?

**Comment by hamelsmu** [comment]
@tyoc213 if you use the newest repo there should not be an error
