### ISSUE TITLE
Time Issue on fastpages blog

### ISSUE THREAD

**Issue by hiteshhedwig** [fastai/fastpages#430]
I  have uploaded notebooks in the same syntax asked. But somehow, time showing on blog for all post is 7/Oct/2020. Even tho i posted first blog on 4 Oct 2020 as shown in image below:

2020-10-4-changing-folders-name.ipynb
2020-10-5-dog-breed-fastai.ipynb
2020-10-8-opensource-dataset.ipynb

![Screenshot from 2020-10-08 09-18-16](https://user-images.githubusercontent.com/40434383/95412850-885c2400-0947-11eb-8786-4a07e6c69b49.png)

But the blog display is something like this. How to deal with it?

![Screenshot from 2020-10-08 09-16-26](https://user-images.githubusercontent.com/40434383/95412637-0cfa7280-0947-11eb-8eae-8a5677cc1432.png)

**Comment by hamelsmu** [comment]
You aren't following the naming conventions.  Read closely

![image](https://user-images.githubusercontent.com/1483922/95496240-5ea9f980-0955-11eb-952e-c64dbb0330ed.png)
