### ISSUE TITLE
Add documentation on how to subscribe to RSS

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastpages#432]
Jeremy gave me two suggestions which I bookmarked in discord chat need to add to the README

**Comment by hamelsmu** [comment]
I added this to the README

**Comment by phucnsp** [comment]
Hello @hamelsmu,

I am using Feedrabbit service for subscribing with RSS, but I don't know how to hyperlink the "Subscribe" button, which is at the bottom of fastpage's front page, with my Feedrabbit link.

Can you please help.

**Comment by v-poghosyan** [comment]
> Hello @hamelsmu,
> 
> I am using fastpage with Feedrabbit service for subscribing with RSS, but I don't know how to hyperlink the "Subscribe" button, which is at the bottom of fastpage's front page, with my Feedrabbit link.
> 
> Can you please help.

I also cannot find where the RSS anchor tag is so that I may link to Feedrabbit.
