### ISSUE TITLE
jupyter notebooks not showing as blog post in my domain.

### ISSUE THREAD

**Issue by akkefa** [fastai/fastpages#438]
This is my domain https://urduhack.com.

Github Url: https://github.com/urduhack/urduhack.com

I added a notebook in _notebook folder it's not showing anywhere in my domain. 

`https://github.com/urduhack/urduhack.com/blob/master/_notebooks/2020-10-16-urdu-unicode-ranges-explained.ipynb`

**Comment by hamelsmu** [comment]
can you try creating a new repo with that is not named .com?  You can still host your site on .com just don't name your repo that, I think that will confuse things in the way the repo is setup.

**Comment by akkefa** [comment]
Issue resolved. I created a new repo.
