### ISSUE TITLE
Integrate fastpages in an existing repository

### ISSUE THREAD

**Issue by albert17** [fastai/fastpages#441]
**Is your feature request related to a problem? Please describe.**
I want to use fastpages in an existing repository. So far, I only see the option of creating a new one.

**Describe the solution you'd like**
I would like to be able to use fastpages in an existing repository without having to create another one. Is this possible? I don't see the option in the documentation.

**Additional context**
Regarding to this topic I have seen a closed issue: https://github.com/fastai/fastpages/issues/357 which seems to show that is it not possible.

If not possible, is it planned to be added?

**Comment by hamelsmu** [comment]
You have to create a new repository.  It is possible to use on an existing repository but it would require significant work on your end to configure everything.

**Comment by albert17** [comment]
@hamelsmu Do you have any documentation or could you indicate me how to do it?

**Comment by hamelsmu** [comment]
Look at the README under customizing fastpages
