### ISSUE TITLE
Is there a way to have custom javascript in the rendered HTML for a blog post?

### ISSUE THREAD

**Issue by armsp** [fastai/fastpages#442]
I have a blog post with Altair visualization made from Jupyter Notebook as usual. However, I want to add some custom JavaScript to it. 
Inside the Jupyter notebook, you have to run the cell with the JavaScript every time you open it to see its effects, even though the rest of the interactivity of the Altair chart works without executing any cell. Because of this behavior, just publishing the jupyter notebook with the JavaScript code would probably not have any effect (I haven't actually tested it).

Similar to https://github.com/fastai/fastpages/pull/171 I want to have fastpages add a little JavaScript code in the rendered HTML for one of the posts, so that the already existing HTML for the charts are modified a little.

Is there a way to achieve this?

**Comment by hamelsmu** [comment]
This is example of how custom javascript is injected into fastpages: https://github.com/fastai/fastpages/blob/master/_includes/custom-head.html

This requires you to [customize fastpages](https://github.com/fastai/fastpages#customizing-fastpages) and learn about how the internals work a bit more.

**Comment by armsp** [comment]
@hamelsmu That helped a lot and I just got it working. I think it's actually better to have custom scripts enabled via Jekyll.

**Comment by hamelsmu** [comment]
great!
