### ISSUE TITLE
Using a custom domain, links in the tags page are missing the domain part

### ISSUE THREAD

**Issue by mojones** [fastai/fastpages#444]
Not sure if this is a bug or an error somewhere in my config. The repo is here

https://github.com/mojones/dfd_jupyter_test

and my custom domain is

https://drawingfromdata.com/

Links to individual posts are fine on the front page under "Posts". But on the tags page:

https://drawingfromdata.com/categories/

the domain part of the URL is missing. I think I have the baseurl set as per the docs in *_config.yaml* and *settings.ini*, because other navigation seems to be working fine.

**Comment by hamelsmu** [comment]
This is because you have not carefully read the documentation in `_config.yaml`

```yaml
####  Scenario Two: If you have a Custom Domain #####
# 1. If your domain does NOT have a subpath, this leave this value as ""
# 2. If your domain does have a subpath, you must preceed the value with a / and NOT have a / at the end.
#      For example:
#           "" is valid
#           "/blog"        is valid
#            "/blog/site/" is invalid  ( / at the end)
#            "/blog/site"  is valid
#            "blog/site"   is invalid  ( because doesn't begin with a /)

```

**If your domain does NOT have a subpath, this leave this value as ""**
