### ISSUE TITLE
Add a explicit note to the documentation instructing users to add the CNAME file to their master branch when using a custom domain

### ISSUE THREAD

**Issue by mojones** [fastai/fastpages#445]
I've just been caught out by this, and apparently so have others e.g.

https://forums.fast.ai/t/fastpages-new-commits-remove-custom-url-from-settings-page/81197

When setting up a custom domain using the Settings tab on the repo, it creates the CNAME file in the root of the gh-pages branch. Then next time you commit to the master branch, triggering a rebuild, the CNAME file disappears and the custom domain stops working. This is easily fixed by copying the CNAME file to the root of master branch so that it gets included every time the gh-pages branch is rebuilt. But if, like me, the user sets up the custom domain by using the settings form on the repo, they might not even know about the existence of the CNAME file. 

For relatively inexperienced users, it might be good to have a dedicated section in the docs on the steps required to use a custom domain - I'm happy to take a stab at it and make a PR.

**Comment by hamelsmu** [comment]
detailed instructions on setting up a custom domain are already located in the pull request that is automatically triggered when your repository is setup.  Here is the [template of the pull request](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/_setup_pr_template.md).  I encourage you to look back to your first pull request and you will find these instructions.  

You are welcome to make a PR to the README of this repo if you find that to be inadequate.
