### ISSUE TITLE
The CI/CD failed to deploy my website to github pages because feel.xml is more than 100MB

### ISSUE THREAD

**Issue by armsp** [fastai/fastpages#446]
I didn't realize this but my current [`feed.xml`](https://github.com/armsp/covidviz/blob/gh-pages/feed.xml) file is 75MB in size. Yesterday I tried to add a new blog post and it [failed](https://github.com/armsp/covidviz/runs/1336718733?check_suite_focus=true#step:8:196) to deploy because the size had increased to 113MB.
```
Deploy
Push the commit or tag
  /usr/bin/git push origin gh-pages
  remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
  remote: error: Trace: 5c8aa6f09c9d58486348199327e33ce87ceb0516d80e5213b34f3f936de29303        
  remote: error: See http://git.io/iEPt8g for more information.        
  remote: error: File feed.xml is 113.52 MB; this exceeds GitHub's file size limit of 100.00 MB        
  To github.com:armsp/covidviz.git
   ! [remote rejected] gh-pages -> gh-pages (pre-receive hook declined)
  error: failed to push some refs to 'github.com:armsp/covidviz.git'
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```
Is this normal behavior? I barely have 17 posts on my [website](https://armsp.github.io/covidviz/) along with a Tag, About Me and landing page. Should I disable my feed? More importantly I want to understand why is the feed.xml file so huge. I didn't get any leads by Googling....perhaps I don't know how to google for this issue?

Any recommendation for this very helpful.

**Comment by hamelsmu** [comment]
Wow @armsp your site is super cool, really impressive.  I'm not sure offhand but I'm investigating this issue now.  Thanks for reporting it.

**Comment by hamelsmu** [comment]
@armsp Can you do me a favor and disable your RSS feed by commenting out this line in your `_config.yaml` file, I opened a PR that removes this.  Let's see if it works?  https://github.com/armsp/covidviz/pull/4

**Comment by hamelsmu** [comment]
@armsp ok I see that it works now, do you want an RSS feed?  If you do there are some ideas that I have after looking at [this documentation](https://github.com/jekyll/jekyll-feed).  After looking at the XML file, I believe the reason the file is so big is that the image files are being ported into the xml file, because the feed reads in the `image` field from front matter

**Comment by armsp** [comment]
It didn't work. Unfortunately the feed.xml file is still being built. Got almost the same error -
```
Deploy
Push the commit or tag
  /usr/bin/git push origin gh-pages
  Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
  remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
  remote: error: Trace: 6194143fdae2938150774abfd1c81c13729ff5d32de98969b9aed82b9a1e3b7f        
  remote: error: See http://git.io/iEPt8g for more information.        
  remote: error: File feed.xml is 113.52 MB; this exceeds GitHub's file size limit of 100.00 MB        
  To github.com:armsp/covidviz.git
   ! [remote rejected] gh-pages -> gh-pages (pre-receive hook declined)
  error: failed to push some refs to 'github.com:armsp/covidviz.git'
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"
```
I thought removing `jekyll-feed` from `_config.yml` ought to make it work just like your PR....but it didn't unfortunately.

**Comment by hamelsmu** [comment]
If you wan to keep your RSS feed, you probably want to only have excerpts:

```yaml
feed:
  excerpt_only: true
```

And limit your posts to 3 posts (limit is 10)

```
feed:
  posts_limit: 3
```

**Comment by armsp** [comment]
I am not inclined either way.... if feed doesn't work then I can let it go, no issues. But I don't think removing `jekyll-feed` solved the issue. The CI/CD failed to deploy.

**Comment by armsp** [comment]
@hamelsmu awesome...let me commit that and see if it works.

**Comment by hamelsmu** [comment]
oh sorry, I thought it worked.  sorry about that.

**Comment by hamelsmu** [comment]
It's fixed!  hurray!

**Comment by armsp** [comment]
Ah, it works finally!.

Thank you so much for this @hamelsmu !

On a side note I was searching google for why the feed.xml files are so huge and not getting anything relevant....should have stuck to basics and just went to jekyll-feed :)
