### ISSUE TITLE
Can't build locally

### ISSUE THREAD

**Issue by mpariente** [fastai/fastpages#449]
When I try to run the code locally, it doesn't work. I've read several linked issues but couldn't find a solution.

What I tried/did: 
- Upgraded fastpages
- Create `.jekyll-cache` folder. The error occurs after (missing `.tweet-cache`, if I create it, there is a new error I can't fix. Happy to provide the details if useful). 
- `sudo make build` and `sudo make server` ([suggested here](https://github.com/fastai/fastpages/issues/351#issuecomment-657017285) in #351. Same problem.
- Deleting my local copy and starting from scratch (we never know), same problem. 
- Read [this "solution"](https://github.com/fastai/fastpages/issues/370#issuecomment-666602759) in #370, no idea what it means, sorry. 
- Tried `make server` with https://github.com/btahir/covid_dz (seemed to have similar problems in #227 , which have been solved): didn't work and with https://github.com/armsp/covidviz (coolest fastpage I saw): same problem

I'm a __complete__ noob with Docker, jekyll and ruby deps and I'd really love some help on that. 

## Required information

1. Steps to reproduce the problem

```bash
git clone https://github.com/mpariente/fastmp
cd fastmp
make build
make server
```

2. Logs

```bash
$ make server
docker-compose down --remove-orphans || true;
Removing network fastmp_default
docker-compose up
Creating network "fastmp_default" with the default driver
Creating fastmp_fastpages_1 ... done
Creating fastmp_jekyll_1    ... done
Creating fastmp_notebook_1  ... done
Creating fastmp_converter_1 ... done
Creating fastmp_watcher_1   ... done
Attaching to fastmp_watcher_1, fastmp_fastpages_1, fastmp_converter_1, fastmp_notebook_1, fastmp_jekyll_1
converter_1  | Agent pid 7
converter_1  | === Running Locally: All assets expected to be in the directory /data ===
fastpages_1  | Agent pid 7
fastpages_1  | === Running Locally: All assets expected to be in the directory /data ===
watcher_1    | Agent pid 14
watcher_1    | === Running Locally: All assets expected to be in the directory /data ===
fastpages_1  | No notebooks were modified
converter_1  | No notebooks were modified
watcher_1    | No notebooks were modified
notebook_1   | [I 18:45:24.228 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
fastmp_fastpages_1 exited with code 0
fastmp_converter_1 exited with code 0
notebook_1   | [W 18:45:24.464 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
notebook_1   | [I 18:45:24.466 NotebookApp] Serving notebooks from local directory: /data
notebook_1   | [I 18:45:24.466 NotebookApp] Jupyter Notebook 6.1.4 is running at:
notebook_1   | [I 18:45:24.466 NotebookApp] http://2649c3ea3d97:8080/
notebook_1   | [I 18:45:24.466 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
jekyll_1     | ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
jekyll_1     | Configuration file: /data/_config.yml
jekyll_1     | /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /data/.jekyll-cache (Errno::EACCES)
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `each'
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/cache.rb:184:in `dump'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/cache.rb:101:in `[]='
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/cache.rb:45:in `clear_if_config_changed'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:118:in `reset'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:35:in `initialize'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:30:in `new'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:30:in `process'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
jekyll_1     | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
jekyll_1     | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
jekyll_1     | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
jekyll_1     | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
jekyll_1     | 	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
jekyll_1     | 	from /usr/local/bundle/bin/jekyll:29:in `load'
jekyll_1     | 	from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

and this goes on forever.

**Comment by hamelsmu** [comment]
Try `sudo make server`

**Comment by mpariente** [comment]
It's in the list of things I tried.. I detailed that part on purpose. 

And I think that's a bad idea in general because it'll install deps with sudo, which not everybody wants.

**Comment by mpariente** [comment]
It seemed like a cache problem, so I looked into disabling the cache in jekyll, I added the `disable_disk_cache: true`  to my `_config.yml` ([see jekyll PR](https://github.com/jekyll/jekyll/pull/7928)). The error changed but it still didn't work. 

Then, I tried to find out where things were installed, hit [this issue](https://stackoverflow.com/questions/23777277/rails-could-not-find-minitest-4-7-5-in-any-of-the-sources) which suggested this fix:

```bash
gem update bundler
bundle install
```

Finally I hit the same problem of "Permission denied": `... Permission denied @ dir_s_mkdir - /data/_site`. After running `mkdir _site`, local deployment works. 

Hopefully, this helps the next one(s) that has this problem.

**Comment by hamelsmu** [comment]
@mpariente thanks for sharing.   I'll try to think of a way to fix this

**Comment by hamelsmu** [comment]
Do you have to keep removing the `_site` directory?  I just pushed a change to `Make` that perhaps will help.

**Comment by mpariente** [comment]
I had to create it. 
Now that it's created, I don't have to do anything when I want to rebuild again. 

I also checked that I owned the folder and I did.

**Comment by hamelsmu** [comment]
ok thanks for sharing

**Comment by alexlenail** [comment]
I am having this issue as well, using the dockerized version of fastpages. (`make server`)

Neither `sudo make server` nor `disable_disk_cache: true` seem to change the issue at all. 

I triggered this by just copying a notebook from somewhere else into `_posts`. Is that not how to add notebooks to a fastpages site?

**Comment by abarbosa94** [comment]
I had the same error and got it working after the `mkdir _site` inside my project repo.

Thanks for sharing!
