### ISSUE TITLE
Implement Optional Subscription For Readers

### ISSUE THREAD

**Issue by hamelsmu** [fastai/fastpages#45]
If readers want to subscribe, create an optional subscribe form.  This one requires a bit more reseach as I think we can use Mailchimp but ideally i want a fully automated solution

**Comment by hamelsmu** [comment]
For this feature, I'm thinking about the following approach:

- Adding a button that [subscribes the reader to releases on the GitHub repository](https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository#watching-releases-for-a-repository)

- When an author wants to publish a post, I can create an automation that will cut a new release for the repo upon making a special commit or opening an issue that says something special.   

you might be wondering why am I doing this?  I want to compete with Medium as much as possible :)

@jph00 what do you think about this?  Do you think it would be too clunky or is this something we should try?

**Comment by hamelsmu** [comment]
Closing this as it is too idiosyncratic and you have to wire up a third-party provider, and I think complicates the setup process and/or increases the surface area of what we must maintain in a way that is not helpful.

**Comment by sebastiandres** [comment]
Hi @hamelsmu, I was wondering into building something similar! 
I think it would be a very nice addition to fastpages, but I agree on the decision; depending on a third party makes it more fragile.
I still might want to take a stab at this for my blog as I have it mostly for my own learning. Do you have notes or code I might take a look at?
