### ISSUE TITLE
Unable to perform upgrade through opening issue

### ISSUE THREAD

**Issue by btruhand** [fastai/fastpages#451]
## Required information

1. Steps to reproduce the problem

In your own forked repository of fastpages, create an upgrade issue as documented here: https://github.com/fastai/fastpages/blob/master/_fastpages_docs/UPGRADE.md. Now wait till the action for upgrade is performed

2. A link to the notebook or markdown file where the error is occurring

N/A

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.

The action will fail and the following error is shown https://github.com/btruhand/blog/actions/runs/367227523. It is related to https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

N/A

---------

I am not sure where exactly is the `set-env` command being used in the actions (not familiar with Github actions or how it is setup in fastpages). I'd be happy to try and resolve it if there are pointers and hints

**Comment by hamelsmu** [comment]
I fixed this now in https://github.com/fastai/fastpages/commit/2fd714497b3cd227eccac9d680eeb4f19c47bd72

You will have to copy and paste the workflow or make the same changes in your repository.  Please let me know if it works (just had to bump the version of that specific step).

**Comment by btruhand** [comment]
@hamelsmu looks good, I'll close the issue :)
