### ISSUE TITLE
When trying to post on social media, image from posts are not displayed

### ISSUE THREAD

**Issue by jvanelteren** [fastai/fastpages#457]
* steps to reproduce twitter card validator (https://cards-dev.twitter.com/validator) with blog post
https://jvanelteren.github.io/blog/2020/11/15/age_pure_pytorch.html

This looks ok, but the image isn't shown, log:
INFO:  Page fetched successfully
INFO:  16 metatags were found
INFO:  twitter:card = summary_large_image tag found
INFO:  Card loaded successfully

Some extra information:
* image is located in images folder
* front matter '- image: images/age_recognition.png'
* blog post displays correctly with image in main blog (https://jvanelteren.github.io/blog/)
* fastpages is updated to latest version

BTW thanks for you inspirational blogs about Docker, the last two blogs are a direct result of it, learning a ton!

**Comment by hamelsmu** [comment]
Pleae upgrade your version of fastpages per the instructions in the README.  You might have to copy and paste .github/workflows/upgrade.yaml file into your repo as GitHub recently made a breaking change.

**Comment by hamelsmu** [comment]
@jvanelteren I'm leaving this open please let me know how it goes

**Comment by jvanelteren** [comment]
I was under the impression it was at the latest version. Did the manual copying and the opening and merging an update which seemed to work. So I'm a bit unsure about that

But apparently something was wrong in my blog, because after I removed it and rebuild it with a fresh install, I can now confirm it works!
