### ISSUE TITLE
Consider using tags instead of categories

### ISSUE THREAD

**Issue by kiendang** [fastai/fastpages#462]
**Is your feature request related to a problem? Please describe.**
In Jekyll there are [tags and categories](https://jekyllrb.com/docs/posts/#tags-and-categories) which are mostly similar. The difference is that categories are integrated into the post's url. For example, if you set the categories of a post to be `[jupyter, python, data, ml]` the post's url will become `<baseurl>/jupyter/python/data/ml/<title>`. This leads to 2 problems:

- Adding too many categories would make the url too long
- Adding and updating categories would change the post's url

Other than this url issue, tags work the same way as categories. Thus if this url feature is unwanted, please consider using tags. Tags and categories can also be used at the same time. One example is https://codinfox.github.io/dev/2015/03/06/use-tags-and-categories-in-your-jekyll-based-github-pages/

**Describe the solution you'd like**
Consider implementing the current category feature as `tags` instead of `categories`. I'm happy to help if you think this makes sense.

**Describe alternatives you've considered**

**Additional context**

**Comment by hamelsmu** [comment]
@kiendang what I usually recommend people to do is to set the permalink attribute for the URL.  I agree with you that in principle tags seem to be better.  

Now that we have it, I don't want to break everyone's links if we change things to be handled as tags.  Any thoughts?

**Comment by kiendang** [comment]
Yup that makes sense.

> what I usually recommend people to do is to set the permalink attribute for the URL.

Maybe this should be added to the doc in the Categories section?
