### ISSUE TITLE
Autosetup don't  open a pr

### ISSUE THREAD

**Issue by chenxh1005** [fastai/fastpages#468]
The setup step didn't  automatically open a pr . I look into the Actions .The initial commit show this.I wonder if that was the problem and I don't know how to solve it .

![微信图片_20201202165734](https://user-images.githubusercontent.com/68215131/100851267-e75d9580-34bf-11eb-8a88-73092031e59c.png)

**Comment by hamelsmu** [comment]
did you remove this file by accident?

**Comment by hamelsmu** [comment]
ok nevermind I fixd this in #469 please try again from scratch should work now
