### ISSUE TITLE
Unable to run or build example notebook in local developer environment

### ISSUE THREAD

**Issue by keeran** [fastai/fastpages#470]
Hello there :wave:

I can't find any reference to problems running locally, either in this repo or in the forums, so I hope this is a suitable report.

When attempting to run a local developer environment via `docker-compose up`, the introduction example notebook fails to execute due to missing Python libraries:

![image](https://user-images.githubusercontent.com/848/101700090-5c0e7200-3a74-11eb-9f0b-e26822e2fbb8.png)

This is also reflected when the converter rebuilds the Markdown post:

![image](https://user-images.githubusercontent.com/848/101700152-75172300-3a74-11eb-95d0-baa77e6fe42e.png)

### Steps to reproduce

1. Clone this repository locally
2. Run `docker-compose up`
3. Visit `http://localhost:8080` and navigate to the `_notebooks/2020-02-21-introducing-fastpages.ipynb` to view the Python errors.
4. Save the notebook / delete the existing Markdown from `_posts` and allow it to rebuild in the background.
5. Visit `http://localhost:4000/fastpages/jupyter/2020/02/21/introducing-fastpages.html` to view the corresponding failed render.

I was able to work around this problem by editing the [`Dockerfile`](https://github.com/fastai/fastpages/blob/032ddcc84fb29dee569991c1d8f4c85d9ec8e087/_action_files/Dockerfile) as follows:

```Dockerfile
FROM fastai/jekyll:2020-09-12
RUN pip install pandas altair
WORKDIR /fastpages
...
```

and then `docker-compose build && docker-compose up`

Happy to open a PR to include these changes, but curious if this needs to change elsewhere / another base image ought to be used?

Many thanks for this cool project! ✨

**Comment by hamelsmu** [comment]
You have to install pandas in this environment with `!pip install pandas` I guess I can add a cell that does that?

**Comment by keeran** [comment]
> I guess I can add a cell that does that? Do you want to make a PR?

Sure thing, thanks for the tip - will get on it shortly.

**Comment by keeran** [comment]
@hamelsmu Not sure this is going to have the optimum effect:

![image](https://user-images.githubusercontent.com/848/102135799-65bb1f80-3e50-11eb-9057-867f45387bb6.png)

![image](https://user-images.githubusercontent.com/848/102135825-710e4b00-3e50-11eb-958a-6b3b12504584.png)

It works now... but it's lost style points :)

**Comment by keeran** [comment]
Tried this but still breaks the flow

![image](https://user-images.githubusercontent.com/848/102136505-61433680-3e51-11eb-98cf-93621688ef69.png)

I'll read some more as I think you mentioned the ability to hide a cell from the output completely.

**Comment by keeran** [comment]
Ah yes, this does the trick for the generated markdown \o/

```
#hide
!pip install pandas altair;
```
