### ISSUE TITLE
Adding files to watchlist on local machine

### ISSUE THREAD

**Issue by ashudva** [fastai/fastpages#478]
I am trying to customize the theme of my blog and testing on my local machine but I don't know how can I add files other than /_notebooks/*.ipyn to the watchlist. Currently, every time I make changes to the theme, I have to restart the server. 
Please help me, I am not familiar with ruby-rails, etc but I'm good with HTML-CSS etc

**Comment by hamelsmu** [comment]
look at `.docker-compose.yaml` you will see `watchmedo` in there.

**Comment by ashudva** [comment]
Thanks a lot!
