### ISSUE TITLE
How to switch from katex to MathJax? 

### ISSUE THREAD

**Issue by alexlenail** [fastai/fastpages#480]
It turns out that changing 
```
kramdown:
  math_engine: katex
```
to 
```
kramdown:
  math_engine: mathjax
```
does not change the rendering engine: latex is still rendered with katex.

**Comment by hamelsmu** [comment]
- Did you set `use_math: ` to `true`?  
- Did you follow the troubleshooting guide?  Were you able to discover anything?
- Can you provide a reproduceable example with katex working and mathjax not working (i.e. link to a notebook).

**Comment by hamelsmu** [comment]
The issue is closed for being stale, no response from original author.

**Comment by kwangsungjun** [comment]
I also have the same issue. 

Anyways, shouldn't we have `gem "kramdown-math-mathjaxnode"` in Gemfile?

(not that it was successful..)
