### ISSUE TITLE
[`code`](link) is missing link in fastpages-rendered html

### ISSUE THREAD

**Issue by alexlenail** [fastai/fastpages#488]
I believe if you place the following in a markdown cell in a notebook, in jupyter it will behave as expected, on a fastpages blog it will not have a link: 
```
[`integrate`](https://docs.scipy.org/doc/scipy/reference/integrate.html)
```

**Comment by hamelsmu** [comment]
Unfortunately this is not supported like this, but you can write html

<code><a href="www.something.com">your text</a><code>
