### ISSUE TITLE
Adding a multi-language feature

### ISSUE THREAD

**Issue by CongLiu-CN** [fastai/fastpages#489]
I always want to add content in Chinese, which is my first language, to my blog built with fastpages, while maintaining the previous content in English.

I would like to have a separate URL that holds all my content in a second language while displaying the content in English on the homepage. Whenever the user clicks the language-switch button on the nav bar on the homepage, he or she will be redirected to a separate URL accordingly.

Another solution would be that I can put each of the two language versions in two different git repos. I can manually connect them with each other by adding a link to their homepages. But this solution seems a bit weird.

I only add this request to know whether there is an existing feature like this or someone is working on something similar. If not, I would probably suggest you don't waste time on this since I can look for other frameworks that already have this feature. Thanks.

**Comment by hamelsmu** [comment]
You can have separate urls for each language right now.  Not planning on adding this feature but may revisit it when I rewrite fastpages in the future to use Hugo.
