### ISSUE TITLE
jupyter notebooks not rendering in my blog post 

### ISSUE THREAD

**Issue by 1Paws7** [fastai/fastpages#490]
I've  added my notebooks in my _notebookfolder but they are not rendering as blog post in my domain ,
my [notebook1](https://github.com/PriyanK7n/fastblogs/blob/master/_notebooks/2020-02-20-testmid.ipynb) is not even showing up in my blog [blog](https://PriyanK7n.github.io/fastblogs/)
and also others are showing in my blog  but not rendering in the post [notebook2](https://github.com/PriyanK7n/fastblogs/blob/master/_notebooks/2021-01-20-Covid19Project.ipynb)
My Github Url : [github](https://github.com/PriyanK7n/fastblogs)
My Blog post: [Blog](https://priyank7n.github.io/fastblogs/)

**Comment by hamelsmu** [comment]
Did you try the troubleshooting guide ☝🏽 ?

**Comment by howard-haowen** [comment]
I also had the same problem, which was solved after I did several things. I'm not sure which of them was the key, here's what I did. 

- requested an automatic update (by following the instructions in `trouble shooting`)
- deleted ` in the summary section of my post
- uploaded the .ipynb file straight from Colab to GitHub instead of doing this manually 


I hope this helps.

**Comment by 1Paws7** [comment]
> Did you try the troubleshooting guide ☝🏽 ?
yes i did i solved the issue hanging around notebook 1 turns out the images i used were in notebook1 were present  in outside directory so just changed it and it rendered but still wasn't able to understand why notebook 2 is 1 not rendering , would really love some tips as in why and wht to do if u could look into it 🙏

**Comment by hamelsmu** [comment]
You have to share more details about your error message, including the developer console and what you learned from the troubleshooting guide.

**Comment by hamelsmu** [comment]
Since you have started a conversation on the forums about this we will close this issue here and continue there
