### ISSUE TITLE
`> Note:` doesn't support blank lines? 

### ISSUE THREAD

**Issue by alexlenail** [fastai/fastpages#492]
```
> Note: hello
> 
> world
```
doesn't seem to work in fastpages (world is not inside the `.flash`)

**Comment by hamelsmu** [comment]
No it doesn't, its meant to be one continuous text.  You can always insert HTML for more customized things if you like.

**Comment by alexlenail** [comment]
@hamelsmu I would suggest this issue should be addressed. I believe just about everyone would expect this to work. 

Probably it's just an edit to the following regex? 

https://github.com/fastai/nbdev/blob/3e9546e62d319781a7855b31ae40f1ad07815086/nbdev/export2html.py#L105-L112

Should I open an issue against nbdev?

**Comment by hamelsmu** [comment]
You can open it against nbdev but I’m not sure that it will be addressed
soon.  You might have to be patient
