### ISSUE TITLE
ghtop notebook does not appear in a fresh setup

### ISSUE THREAD

**Issue by edgarriba** [fastai/fastpages#494]
hi! I followed the instruction to setup a new blog repository but the ghtop example doesn't seem to be built.

I tried also to trigger for updating everything seems fine. You can see the here our generated pages:  https://librecv.github.io/blog/

Is there anything we are missing ?

**Comment by hamelsmu** [comment]
The ghtop blog is a hidden post. 

You will notice that
---
hidden: true
---

**Comment by hamelsmu** [comment]
![image](https://user-images.githubusercontent.com/1483922/106047931-11cf6780-6099-11eb-9240-06f02c75faa2.png)

I'm going to delete this post now as it is a blog post we were planning on but ultimately decided not to post it.
