### ISSUE TITLE
Build fails when code contains Django template language (liquid tags)

### ISSUE THREAD

**Issue by stefanbschneider** [fastai/fastpages#498]
## Required information

1. Steps to reproduce the problem

I'm using the latest version of `fastpages` to run [my new blog](https://github.com/stefanbschneider/blog/).
On the blog, I want to write (among other stuff) about Django. [Django's templates](https://docs.djangoproject.com/en/3.1/ref/templates/language/) use syntax that is likely confused by Jekyll and that leads to build failures when using it in code snippets.

For example, including the following code snippet in a blog post leads to a build failure:

```html
<form action="{% url 'helloworld:index' %}" method="post">
    {% csrf_token %}
    <button type="submit" name="hello-world-button">Greet the world!</button>
</form>
``` 

The action leads to the following error: `Liquid Exception: Liquid syntax error (line 105): Unknown tag 'url' in /github/workspace/_posts/2021-01-29-django-db.md` (see [failed action](https://github.com/stefanbschneider/blog/runs/1792325984?check_suite_focus=true#step:7:158)).

When removing the code snippet from the blog post, it works fine.

This seems to be related to this issue, which is closed but apparently didn't solve the problem for me: https://github.com/fastai/fastpages/issues/66

2. A link to the notebook or markdown file where the error is occurring

* The markdown post without the code snippet, which works: https://github.com/stefanbschneider/blog/blob/bc9166eafcf1616357cf16ee3a07de3bb6dbb2d2/_posts/2021-01-29-django-db.md
* Previous version with the code snippet, which broke the build: https://github.com/stefanbschneider/blog/blob/5a7591ac4c41eb584cc2247bf88dbd6295f459b5/_posts/2021-01-29-django-db.md

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.

Using the [post with the Django code snippet](https://github.com/stefanbschneider/blog/blob/5a7591ac4c41eb584cc2247bf88dbd6295f459b5/_posts/2021-01-29-django-db.md), the action fails, eg, [here](https://github.com/stefanbschneider/blog/runs/1792325984?check_suite_focus=true#step:7:158).

Is there any recommendation how to deal with this other than just removing the snippet? I read something about `{% raw %}` tags around the snippet?

**Comment by stefanbschneider** [comment]
A workaround could be to embed the code snippet as HTML using https://emgithub.com/ , but this isn't really handy for many code snippets.

**Comment by hamelsmu** [comment]
You have to escape liquid tags

https://stackoverflow.com/questions/3426182/how-to-escape-liquid-template-tags

**Comment by stefanbschneider** [comment]
Thanks, putting `{% raw %}` and `{% endraw %}` around the code snippet solves the problem.

Just out of curiosity: Couldn't fastpages escape code blocks automatically?

**Comment by hamelsmu** [comment]
We escape notebook code but not markdown.  Since markdown is the native
Jekyll interface I don’t want to introduce magic that might confuse people
