### ISSUE TITLE
Uploaded notebook not pushing to the gh-pages branch

### ISSUE THREAD

**Issue by pdholakia98** [fastai/fastpages#500]
Hi, 

Running into an issue after uploading a new notebook to the _notebooks folder. The new notebook "2021-02-15-NHL-Instagram-Analysis.ipynb" has successfully uploaded, but it is not being reflected in the gh-pages branch of the repository. I'm not seeing any errors in GitHub Actions either. 

I've uploaded it multiple times and deleted it to see if that solved any issues, but to no avail. 

Link to the repository: https://github.com/pdholakia98/DholakiaSportsAnalytics

**Comment by hamelsmu** [comment]
Notebooks are not supposed to go into the gh-pages branch only HTML is.  Your notebooks go in your master branch and they are converted to HTML.  If they aren't being converted, look at the development guide and debug it a bit before opening an issue with information.

**Comment by pdholakia98** [comment]
Hi Hamel,

I don't believe your answer was sufficient enough to warrant closing the issue. I tried to debug the issue before posting here and read through the documents provided, but they're not detailed enough for me to understand why a notebook uploaded to the master _notebook folder would not create a post.

I would appreciate a better explanation of what the issue is, as the expected action steps are not occurring. 

Thanks

**Comment by hamelsmu** [comment]
Can you please debug locally and tell me what information you are seeing.  It's impossible to debug given the information you are sharing
