### ISSUE TITLE
I need md files after convert

### ISSUE THREAD

**Issue by sajjjadayobi** [fastai/fastpages#501]
thank you for your great work,
I need to have the result of convert notebook to md
is there any way to reach that?

**Comment by hamelsmu** [comment]
You can do this without fastpages.  See [nbconvert](https://nbconvert.readthedocs.io/en/latest/)

**Comment by hamelsmu** [comment]
If you want the md files, you can preview the blog locally with the Development guide as well.  If you want Actions to generate the markdown file 

![image](https://user-images.githubusercontent.com/1483922/107699810-72e76580-6c6b-11eb-8207-6b6bf714815b.png)
