### ISSUE TITLE
A button to download the notebooks directly

### ISSUE THREAD

**Issue by tcapelle** [fastai/fastpages#504]
A button similar to "open in colab" that downloads the notebook to your ocmputer.
![image](https://user-images.githubusercontent.com/18441985/109325259-0026de80-7856-11eb-8550-eebcca09ea1c.png)

**Comment by hamelsmu** [comment]
You can do this via HTML yourself, I"m not sure I want to include this as the options will become quite cluttered, give that the notebook is already stored in GitHub, and you can download it from there.

**Comment by tcapelle** [comment]
You are right, just found weird that so many cloud options are easily presented without the run locally option.

**Comment by hamelsmu** [comment]
Thanks
