### ISSUE TITLE
_action_files/settings.ini should not be added to blog

### ISSUE THREAD

**Issue by PhilipMay** [fastai/fastpages#508]
For me it seems like `_action_files/settings.ini` gets copied to `_site` which is not needed.
Should that be avoided?

**Comment by PhilipMay** [comment]
It seems like settings.ini is a fale that belongs to nbdev. It might note be used here at all?

**Comment by hamelsmu** [comment]
It is used by the GitHub actions workflow.  Yes it is needed.

**Comment by PhilipMay** [comment]
Ok - thanks.
But does it need to be put into `_site` and uploaded to the blog website?

**Comment by hamelsmu** [comment]
Oh yes, you can exclude that file if you wish with this config https://github.com/fastai/fastpages/blob/master/_config.yml#L124-L125

Cheers.
