### ISSUE TITLE
How to include requirements.txt for Binder?

### ISSUE THREAD

**Issue by zshn25** [fastai/fastpages#513]
For my notebook to work on Binder, I need to provide requirements.txt. How do I provide this?

Thanks

**Comment by hamelsmu** [comment]
Please open an issue on Binder.  This is not the right place to ask this question, unfortunately.  Thank you

**Comment by zshn25** [comment]
Sorry if I couldn't explain it properly. I have a post in my `_notebooks` dir which renders [like this](https://zshn25.github.io/ResNet-feature-pyramid-in-Pytorch/) using fastpages. It has a Binder link and when I click the Binder link, it opens the notebook to be run on Binder. But, the problem is that my notebook uses packages such as `torch` which cause an ImportError inside Binder. Now, how do I make the binder link point to a requirements.txt file which contains my required packages to run the notebook on Binder successfully?

**Comment by zshn25** [comment]
For anyone else wondering, the answer was to just place a `requirements.txt` in the root of your fastpages repo. Binder will use it for installing the required packages.
