### ISSUE TITLE
cartopy plot in notebook outputs SVG doctype string

### ISSUE THREAD

**Issue by datadu-de** [fastai/fastpages#519]
cartopy plot in notebook outputs SVG doctype string.

You can see the result in this notebook:
<https://datadu.de/matplotlib/cartopy/2021/05/01/our-slice-of-paradise.html>
below the code cell (output is collapsed due to the bug, as I wanted to hide the docstring.
![image](https://user-images.githubusercontent.com/49077745/116813588-af34ae80-ab54-11eb-9864-0a4d63b0a512.png)

The notebook itself can be found here:
<https://github.com/datadu-de/datadude/blob/master/_notebooks/2021-05-01-our-slice-of-paradise.ipynb>
As you can see the docstring is not rendered there

**Comment by datadu-de** [comment]
I checked with another library to see if it's a cartopy thing - however with geopandas it's the same - as it also uses matplotlib under the hood, still interesting, as it only happens with geo plots.

![image](https://user-images.githubusercontent.com/49077745/116814092-587ca400-ab57-11eb-8488-da06be5db5b7.png)

**Comment by enajx** [comment]
Those strings are the notebook's metadata leaking. Using [nb-clean](https://github.com/srstevenson/nb-clean) to remove the metadata from the notebook seems to fix the issue.
Run `nb-clean clean notebook.ipynb` and then re-execute all cells to generate plots.

**Comment by datadu-de** [comment]
@enajx thanks for looking into it! I will give `nb-clean` a try

**Comment by hamelsmu** [comment]
@datadu-de did that solve your issue?
