### ISSUE TITLE
CVE bugs found in libxml2 for nokogiri, rexml, kramdown

### ISSUE THREAD

**Issue by byteshiva** [fastai/fastpages#539]
1. Bump `nokogiri from 1.11.1 to 1.11.5`
More details available at:
- https://github.com/byteshiva/blog/pull/116

2. Bump `rexml from 3.2.4 to 3.2.5`
Details available at:
- https://github.com/byteshiva/blog/pull/112

3. Bump `kramdown from 2.3.0 to 2.3.1`
Details at 
- https://github.com/byteshiva/blog/pull/107

**Comment by byteshiva** [comment]
Closing since there is PR against the issues mentioned above

**Comment by puja108** [comment]
The rexml PR got closed after having been approved without merging or comment (https://github.com/fastai/fastpages/pull/518) and the nokogiri one is still open (https://github.com/fastai/fastpages/pull/538).

Is there a plan to fix this or does closing this issue (and at least now one of the PRs) mean "this is not gonna be fixed"?

**Comment by byteshiva** [comment]
> The rexml PR got closed after having been approved without merging or comment (#518) and the nokogiri one is still open (#538).
> 
> Is there a plan to fix this or does closing this issue (and at least now one of the PRs) mean "this is not gonna be fixed"?

@puja108 - I've opened a new PR(https://github.com/fastai/fastpages/pull/545) to bump rexml to 3.2.5
