### ISSUE TITLE
Create _posts dir during build if it isn't present. 

### ISSUE THREAD

**Issue by alexlenail** [fastai/fastpages#541]
I merged a feature branch into master with some updates to a notebook, and my posts disappeared. Looking through the build, for every notebook I see: 
```
converting: _notebooks/notebook.ipynb
[Errno 2] No such file or directory: '_posts/2021-05-23-notebook.md'
...
Conversion failed on the following:
notebook.ipynb
...
```

In this merge commit, I deleted the posts in `_posts/notebook.md` because I thought the github actions would create those files anyways. Am I thinking about fastpages incorrectly? Or is it just that I need to have a non-empty `_posts/` folder for the CI job to work...?

**Comment by alexlenail** [comment]
re-creating `_posts/` solved the issue. Should that be added to the build step?

**Comment by hamelsmu** [comment]
Not sure why you don't have `_posts/` that folder is in this repo.  I think you may have deleted it?

**Comment by hamelsmu** [comment]
Also yes, `_posts` is a required directory.  I think this error is a good thing.  I'll add something to that directory's README to warn users not to delete it.
