### ISSUE TITLE
fatal: not a git repository (or any parent up to mount point /github)

### ISSUE THREAD

**Issue by novice03** [fastai/fastpages#542]
Hello, 
I'm trying to use the fastpages action to convert my notebooks to .markdown and publish them on my github.io page. I've run into an error while adding the action to my repository ([https://github.com/novice03/novice03.github.io/runs/2671567434](https://github.com/novice03/novice03.github.io/runs/2671567434)). It says:

`Run fastai/fastpages@master`
`Agent pid 9`
`No notebooks were modified`
`fatal: not a git repository (or any parent up to mount point /github)`
`Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).`

My ci.yml file is located at [https://github.com/novice03/novice03.github.io/blob/main/.github/workflows/ci.yml](https://github.com/novice03/novice03.github.io/blob/main/.github/workflows/ci.yml). How can I fix this?

**Comment by hamelsmu** [comment]
I cannot troublehsoot this error because you have pointed me at a private repo.   Closing this issue
