### ISSUE TITLE
error parsing fragment

### ISSUE THREAD

**Issue by nvtrang91** [fastai/fastpages#546]
Hi,
I kept getting this during Jekyll Build and I couldn't see what is wrong
```
Remote Theme: Cleaning up /tmp/jekyll-remote-theme-20210603-1-1m256il
/usr/gem/gems/nokogiri-1.11.1-x86_64-linux/lib/nokogiri/xml/node.rb:840:in `in_context': error parsing fragment (1) (RuntimeError)
```
Not sure if this is a error or not because it's NOT in red. GH-page status is fine as well as first commit with _config.yml

Please help. Thanks

**Comment by hamelsmu** [comment]
I cannot replicate this issue.  Also not enough information is given to reproduce this error.  Thanks
