### ISSUE TITLE
Collapsible headings

### ISSUE THREAD

**Issue by alexlenail** [fastai/fastpages#547]
[Collapsible headings now exist on jupyter lab](https://twitter.com/jeremyphoward/status/1157342675491627009?lang=en). Would it be possible to add them to fastpages as an option?

**Comment by hamelsmu** [comment]
@choldgraf check it out someone trying to marry JupyterBook with fastpages kind of https://alexlenail.me/back_of_my_envelope/2021/06/23/Enzyme-Kinetic-Parameter-Inference.html

**Comment by choldgraf** [comment]
@hamelsmu super cool 🙂
