### ISSUE TITLE
Jekyll fails with `in_context': error parsing fragment (1) (RuntimeError)

### ISSUE THREAD

**Issue by isimplification** [fastai/fastpages#550]
## Required information

1. Steps to reproduce the problem
a. Create new notebook and upload to repo
[Notebook 1] (https://manpower.simplification.io/kuwait/manpower/analysis/2021/05/20/Manpower-EDA-v2.html) deployed just fine
2. Created new [notebook 2] (https://github.com/isimplification/manpower.simplification.io/blob/master/_notebooks/2021_06_07_Manpower_EDA_Version_3_3.ipynb) and uploaded to _notebooks folder
3. In GitHub Actions, Site build throughs the following error
4. A screenshot / dump 
![image](https://user-images.githubusercontent.com/63327750/121270764-eef36200-c887-11eb-881c-7dca76b290f5.png)

**Comment by ice3** [comment]
I have nearly the same error when creating a new project with the template.

**Comment by ice3** [comment]
My bad, the issues are totally unrelated, in my case, the setup didn't configure correctly the _config.yml.

**Comment by isimplification** [comment]
The problem seems to be the charts and graph, when you clear the cell it uploads and publishes fine

**Comment by zbarry** [comment]
I was having this same problem @isimplification with HoloViews/Bokeh plots. I ended up resolving it by removing `jemoji` from `_config.yml` and `Gemfile`.
