### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by sparsh-ai** [fastai/fastpages#558]
## Required information

1. Steps to reproduce the problem
Refer to this (https://nb-dev.recohut.com) site, generated via fastpages. Search functionality is not working.

2. A link to the notebook or markdown file where the error is occurring
https://nb-dev.recohut.com/

**Comment by goodboychan** [comment]
have you tried to use debug console in browser? It said that " https://nb-dev.recohut.com/assets/js/vendor/lunr.min.js net::ERR_ABORTED 404"
Do you use specific javascript?

**Comment by sparsh-ai** [comment]
I added assets/js/vendor/lunr.min.js file, referencing fastpages' official repo. After adding this, I also needed to disable math parsing option in config to make it work.

Also, not able to replicate this in prod site - https://nb.recohut.com/

Followed all kind of combinations but search still not working in prod.

**Comment by hamelsmu** [comment]
If you have modified the javascript for your site, I am not sure how to help you troubleshoot.   The demo site, which uses the code in the master branch works: https://fastpages.fast.ai/search/

If you are creating a fastpages site from scratch and still get an error like this, let me know

**Comment by sparsh-ai** [comment]
> If you have modified the javascript for your site, I am not sure how to help you troubleshoot. The demo site, which uses the code in the master branch works: https://fastpages.fast.ai/search/
> 
> If you are creating a fastpages site from scratch and still get an error like this, let me know

Hi @hamelsmu, it is working now. The error was due to one of then notebook. Some output was not getting supported.

To resolve it, I used Mac's VIM editor to goto: <error_line> and hide the output of that cell, and search started working again.
