### ISSUE TITLE
Wrap a text cell in a div, but still parse it as usual

### ISSUE THREAD

**Issue by alexlenail** [fastai/fastpages#559]
markdown cells are parsed such that paragraphs are wrapped with `<p>` tags, etc...

If I try to wrap a markdown cell in a `<div class="myClass">` in order to style this specific markdown cell in fastpages, the paragraphs inside are no longer wrapped with `<p>` tags -- fastpages basically doesn't parse the inside of the div.

Is there a way to wrap some content in a div, but still have fastpages parse the markdown inside?

**Comment by hamelsmu** [comment]
I think once you start using HTML, you cannot have markdown inside it.   Are you trying to use markdown inside HTML?  I don't think this is possible.  It gets super confusing really fast to try to enable this. 

Let me know if you have a better suggestion.

**Comment by alexlenail** [comment]
Makes sense. Still a shame though. Thanks for clarifying.
