### ISSUE TITLE
Notebook post  is not showing in my blog even after properly rendering

### ISSUE THREAD

**Issue by SumitJha406** [fastai/fastpages#560]
Here is my notebook post in _notebook folder:- https://github.com/SumitJha406/Data_oriented/tree/master/_notebooks
![Capture1](https://user-images.githubusercontent.com/73595258/124114901-c4fa1d80-da8a-11eb-9dc5-8c0560f7e342.PNG)

Action which took place after uploading this notebook is-
![Capture2](https://user-images.githubusercontent.com/73595258/124115218-291ce180-da8b-11eb-93ef-ffc7227fa1d4.PNG)

whereas When I uploaded word file in word folder , it is showing in my blog-https://sumitjha406.github.io/Data_oriented/

![Capture3](https://user-images.githubusercontent.com/73595258/124115460-7305c780-da8b-11eb-92dc-68dd2a2a837f.PNG)

**Comment by hamelsmu** [comment]
You have not specified the front matter of [your notebook](https://github.com/SumitJha406/Data_oriented/blob/master/_notebooks/2001-01-07-eda_of_flower_data.ipynb) correctly

see https://github.com/fastai/fastpages#customizing-blog-posts-with-front-matter

Also you did have an error in notebook conversion https://github.com/SumitJha406/Data_oriented/runs/2969771240?check_suite_focus=true#step:5:79
