### ISSUE TITLE
dockerize notebooks for future colab/binder use

### ISSUE THREAD

**Issue by alexlenail** [fastai/fastpages#561]
These notebooks have an "open in colab" button, but the imported packages might not be available by default in colab, requiring some `!pip install`s in that environment. Even then, with version changes, the colab/binder buttons may not work in the future. 

What is the recommended way of e.g. building a docker container directly from a notebook, or virtual environment? Would it be reasonable to bundle this in with fastpages as another github action?

**Comment by hamelsmu** [comment]
This is a bit out of scope for fastpages, but if you are interested in this you can check out the following:

- repo2docker: https://github.com/jupyterhub/repo2docker
- repo2docker action: https://github.com/jupyterhub/repo2docker-action
