### ISSUE TITLE
Automate setup of new blog

### ISSUE THREAD

**Issue by jph00** [fastai/fastpages#57]
Currently there are a lot of steps necessary to set up a new blog that need to be manually completed.

It would be great if some or all of them could be automated. e.g. perhaps there could be a little python script or something in the repo root that, after you generate from the template and clone, you could run the script, it would ask you a few questions, and then complete the remaining steps for you. I haven't checked whether all the steps are available thru APIs or not.

**Comment by hamelsmu** [comment]
This is an excellent idea.  I think this is the highest priority thing to work on.  I think it is possible with the API.

I’ll work on this next week.

**Comment by hamelsmu** [comment]
Current plan.  Upon using the template the user opens an issue with the magic comment: **/setup**

This triggers the following steps to happen

1. An SSH deploy key is created and automatically added to the repo https://developer.github.com/v3/repos/keys/#add-a-new-deploy-key

2. The private key will be automatically uploaded as an encrypted secret https://developer.github.com/v3/actions/secrets/

3.  Badge names are changed to reference the repo name automatically

4. _config.yaml is automatically updated with the repo name and username 

5. A gh-pages branch is automatically created (can do push -f ... to force creation inside Actions)

6. GitHub pages will automatically be enabled https://developer.github.com/v3/repos/pages/

**Note:** the user doesn’t ever “see” any of this it happens 100% in the background 

How does this workflow sound , @jph00? the benefit of this is that the user doesn’t have to create a personal access token and can just lean on Actions to do the magic.  The downside is no ability to have interactive questions / prompts - however the setup steps are pretty boilerplate unless you are trying to configure a custom domain.  

Thoughts?

**Comment by hamelsmu** [comment]
While we are at it we can add more automation that allows people to upgrade to a new version of fastpages with the magic command **/upgrade-site** that copies posts, notebooks, word docs etc into the latest version.  This will assume they haven’t customized anything.  This is just an additional idea

**Comment by hamelsmu** [comment]
Oh and don’t worry we can restrict this to only trigger if the owner of the repo makes these commands, for security reasons

**Comment by jph00** [comment]
This sounds amazing! :)
