### ISSUE TITLE
Investigate nbdev handling of external urls and update documentation accordingly

### ISSUE THREAD

**Issue by drscotthawley** [fastai/fastpages#58]
My notebook post (https://github.com/drscotthawley/devblog2/blob/master/_notebooks/2019-12-21-PCA-From-Scratch.ipynb) contains the line 

    ![splash pic i made](https://i.imgur.com/vKiH8As.png)

(This is using an external image URL because originally this was a Colab notebook.)

This is apparently causing an error in the build phase called "convert notebooks and word docs to posts", which fails with

    [Errno 2] No such file or directory: '/github/workspace/_notebooks/https:/i.imgur.com/vKiH8As.png'

This may be more appropriate to file as an nbdev issue, such as in nbdev's [copy_images()](https://nbdev.fast.ai/export2html/#copy_images), but I can't see from the `docker run` command before the error what the calling sequence really is, so for now, this Issue is going here. 

I want to show you the log from this build action, but for some reason I'm only able to copy & past the last screen of output 

```
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4.0->nbdev) (0.15.7)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.4.0->nbdev) (2.2.0)
Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (setup.py): started
  Building wheel for pyyaml (setup.py): finished with status 'done'
  Created wheel for pyyaml: filename=PyYAML-5.3-cp37-cp37m-linux_x86_64.whl size=44228 sha256=2849b70c15d9a6287c040494aacf5fce4dbc78c0f012589fdbaaaf42a88be977
  Stored in directory: /root/.cache/pip/wheels/8a/55/a4/c0a81d27c33462cfdcb904db018f5550197e88b2b6b85beed2
Successfully built pyyaml
Installing collected packages: pyparsing, packaging, pyyaml, fastscript, nbdev
Successfully installed fastscript-0.1.4 nbdev-0.2.11 packaging-20.1 pyparsing-2.4.6 pyyaml-5.3
Removing intermediate container 777fa6e7fb4e
 ---> 785732a2fae1
Step 9/13 : WORKDIR /fastpages
 ---> Running in b471877f7bcf
Removing intermediate container b471877f7bcf
 ---> 7a70164df948
Step 10/13 : COPY . .
 ---> ae0df79ca46c
Step 11/13 : RUN chmod u+x action_entrypoint.sh
 ---> Running in 9e435c1efb7b
Removing intermediate container 9e435c1efb7b
 ---> 1fea6b18ebe0
Step 12/13 : RUN chmod u+x word2post.sh
 ---> Running in 0aab46f15a33
Removing intermediate container 0aab46f15a33
 ---> 66431beca583
Step 13/13 : CMD [ "/fastpages/action_entrypoint.sh" ]
 ---> Running in c3b8d4d4c536
Removing intermediate container c3b8d4d4c536
 ---> b2f73f74387b
Successfully built b2f73f74387b
Successfully tagged e87b52:3234fc1855fc53ec9dac003860ef10bb
/usr/bin/docker run --name e87b523234fc1855fc53ec9dac003860ef10bb_c377e6 --label e87b52 --workdir /github/workspace --rm -e INPUT_BOOL_SAVE_MARKDOWN -e INPUT_SSH_DEPLOY_KEY -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/devblog2/devblog2":"/github/workspace" e87b52:3234fc1855fc53ec9dac003860ef10bb
Agent pid 7
converting: _notebooks/2019-12-21-PCA-From-Scratch.ipynb
[Errno 2] No such file or directory: '/github/workspace/_notebooks/https:/i.imgur.com/vKiH8As.png'
Traceback (most recent call last):
  File "/fastpages/nb2post.py", line 36, in <module>
    export2html.notebook2html(fname='_notebooks/*.ipynb', dest='_posts/', template_file='/fastpages/fastpages.tpl')
  File "/usr/local/lib/python3.7/site-packages/nbdev/export2html.py", line 426, in notebook2html
    raise Exception(msg + '\n'.join([f.name for p,f in zip(passed,files) if not p]))
Exception: Conversion failed on the following:
2019-12-21-PCA-From-Scratch.ipynb
```

The URL for this run is https://github.com/drscotthawley/devblog2/runs/449901792

**Comment by drscotthawley** [comment]
Update: looks like this may be explicitly an nbdev issue.  Latest run is:
https://github.com/drscotthawley/devblog2/runs/450012064?check_suite_focus=true , where this error message is from nbdev / export2html. 

Seems like there was an nbdev issue on [broken image urls](https://github.com/fastai/nbdev/issues/30), but as of Dec 30 2019 the last post from Sylvain was that they were fixed. 

If you like, we can close this Issue, and I can reopen over on the nbdev repo.

**Comment by hamelsmu** [comment]
@drscotthawley please open an issue in nbdev for this if you don't mind

**Comment by hamelsmu** [comment]
@sgugger do you want to transfer this issue to nbdev?

**Comment by hamelsmu** [comment]
Closing this but needs to be reopened in nbdev

**Comment by sgugger** [comment]
I can add some check that the images don't come from an external url in nbdev. The case didn't come up before since we always host them internally.

**Comment by hamelsmu** [comment]
Ok I'm reopening this as a note to myself to document this somewhere for users or see if I can try to find a workaround

**Comment by sgugger** [comment]
Just fixed it in nbdev

**Comment by drscotthawley** [comment]
@sgugger  Awesome!  Thanks.

**Comment by drscotthawley** [comment]
@sgugger I'm still getting the same error.  Is the new nbdev on PyPl yet?  (Maybe I just need to wait until tomorrow?)

The fastpages build runs 'pip install nbdev' , which gives 
```
Requirement already satisfied: nbformat>=4.4.0 in /usr/local/lib/python3.7/site-packages (from nbdev) (5.0.4)
```
i.e., it's not grabbing a new version.  ...And then it still tries to treat URLs as if they were files, as before. 

Full build: https://github.com/drscotthawley/devblog2/runs/451505272

**Comment by sgugger** [comment]
We won't make a release of nbdev every time we fix a bug. Is there a way to have the option to use a dev install @hamelsmu , if people want the latest?

**Comment by hamelsmu** [comment]
I could change the GitHub Actions to _always_ do a dev install rather than pypi.  Is that a good idea?

I could also add a feature where you could set a flag somewhere in to turn on dev install, it would involve editing the GitHub .github/workflow yaml files (which might be scary?)

@sgugger @drscotthawley What do you both think is the best approach as people who might potentially be users?   Please let me know your thoughts 🙇

**Comment by sgugger** [comment]
I think a flag would be the best (sometimes master could be unstable), so the end user can choose the normal or bleeding-edge-but-maybe-risky behavior.

**Comment by hamelsmu** [comment]
ok!  I added this to my backlog https://github.com/fastai/fastpages/issues/65

Thanks

**Comment by drscotthawley** [comment]
Regarding a 'dev install': I changed my fastpages fork's _actions/Dockerfile to pull straight from nbdev GitHub to get the latest version:
```
#RUN pip install nbdev
RUN pip install git+https://github.com/fastai/nbdev
```

which seems to install the latest nbdev ok:

```
...
Step 8/13 : RUN pip install git+https://github.com/fastai/nbdev
 ---> Running in 7b3c5453a4d2
Collecting git+https://github.com/fastai/nbdev
  Cloning https://github.com/fastai/nbdev to /tmp/pip-req-build-4nf78cuu
  Running command git clone -q https://github.com/fastai/nbdev /tmp/pip-req-build-4nf78cuu
Requirement already satisfied: nbformat>=4.4.0 in /usr/local/lib/python3.7/site-packages (from nbdev==0.2.12) (5.0.4)
Requirement already satisfied: nbconvert>=5.6.1 in /usr/local/lib/python3.7/site-packages (from nbdev==0.2.12) (5.6.1)
...
  Building wheel for pyyaml (setup.py): started
  Building wheel for pyyaml (setup.py): finished with status 'done'
  Created wheel for pyyaml: filename=PyYAML-5.3-cp37-cp37m-linux_x86_64.whl size=44228 sha256=b979a4a1ac513f38fc3c230cd4f0d9364340ae816aaf6fadfd10c3c7c7e643b9
  Stored in directory: /root/.cache/pip/wheels/8a/55/a4/c0a81d27c33462cfdcb904db018f5550197e88b2b6b85beed2
Successfully built nbdev pyyaml
Installing collected packages: pyyaml, fastscript, pyparsing, packaging, nbdev
Successfully installed fastscript-0.1.4 nbdev-0.2.12 packaging-20.1 pyparsing-2.4.6 pyyaml-5.3
Removing intermediate container 7b3c5453a4d2
 ---> 947fb68a56a8
Step 9/13 : WORKDIR /fastpages
```

...but in the end, still getting the same error as before, treating image URLs as if they were files. 
Run: https://github.com/drscotthawley/devblog2/runs/451767876

**Comment by hamelsmu** [comment]
@drscotthawley thanks for being so diligent and testing it out!!!! I must admit I don’t know nbdev deeply enough at this moment to have any useful comments.

@sgugger is there some background about not supporting external links nbdev?  Asking because I sense this is for a good reason, and I want to avoid re-learning something the hard way if possible.

**Comment by sgugger** [comment]
No reason, but I was looking for `http://` and `https://` but it looks like this image has just an `http:/`, that's why it failed. I pushed a commit to take those into account too.

**Comment by drscotthawley** [comment]
@sgugger That's odd...The url I provided above definitely has `https://`.  Again, the notebook reads
```
![splash pic i made](https://i.imgur.com/vKiH8As.png)
```
Some earlier part of the nbdev scripts must be stripping one of the /'s.    I suspect something up the chain is already committed to treating URL as files, for which extra slashes are superfluous, and so it's stripping the double slashes. 

I tried [forking my own version of nbdev and adding print statements around your checks](https://github.com/drscotthawley/nbdev/blob/master/nbdev/export2html.py)  for http:// or https://, but for some reason the output isn't printing to the GitHub console.  

The latest pull from nbdev repo gives the same error message:
```
RUN pip install git+https://github.com/fastai/nbdev.git
...
[Errno 2] No such file or directory: '/github/workspace/_notebooks/https:/i.imgur.com/vKiH8As.png'
```

**Comment by drscotthawley** [comment]
Ok, by running locally on my laptop, I  found exactly where this is happening in export2html.  I'll open an nbdev issue on this.   @hamelsmu  I'll give you a break from these messages! ;-)

**Comment by drscotthawley** [comment]
Update: Given Sylvain's newest changes, this error goes away when one uses the latest nbdev source.

**Comment by drscotthawley** [comment]
Closing this issue. 
It's fixed in the newest nbdev.  If users pull from nbdev github, they'll notice no issues.  Other users will need to wait for a release push to PyPi.

**Comment by rahuls0959** [comment]
@drscotthawley how did you solve this issue. I am facing the same
