### ISSUE TITLE
Saving html posts of notebooks

### ISSUE THREAD

**Issue by MikkelMathiasen23** [fastai/fastpages#594]
## Required information

1. Steps to reproduce the problem
We are wanting to save the intermediary html versions of our notebooks before creating the gh-pages. We are following the approach given in the FAQ: 
    ...

    - name: convert notebooks and word docs to posts
      uses: fastai/fastpages@master
      with:
        BOOL_SAVE_MARKDOWN: true
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}

    ...
When doing so we get the following error when the github-actions (CI.yaml file) runs: 

`Identity added: _mykey (_mykey)
Warning: Permanently added 'github.com,140.82.112.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.`

2. A link to the notebook or markdown file where the error is occurring
The error is happening in the GItHub actions. It is about the following notebook: 
https://github.com/MikkelMathiasen23/GameOfThrones_Network/blob/master/_notebooks/2021-11-13-03_Basic_Statistics.ipynb

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.
The error can be found here: 
https://github.com/MikkelMathiasen23/GameOfThrones_Network/runs/4221796102?check_suite_focus=true 

Step one explains how to reproduce the error.

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).
![error](https://user-images.githubusercontent.com/51484172/141943267-8885aa76-d8df-4c9c-9443-4e2ea81f0b62.PNG)

**Comment by hamelsmu** [comment]
Looks like you did not place a SSH key correctly in your repo?  I would suggest setting up a regular fastpages repo and walking through the steps to see an example of what this means.   Let me know if that helps.

**Comment by hamelsmu** [comment]
Closing due to no reponse
