### ISSUE TITLE
PR not triggered

### ISSUE THREAD

**Issue by jacoporepossi** [fastai/fastpages#608]
Hi there,
I'm writing this because the PR message is not triggered when I create the repo from fastpages.
I enabled external actions (Settings -> Actions -> Actions Permissions -> Allow all actions) but with no luck whatsoever.

I also found [this issue](https://github.com/fastai/fastpages/issues/429), but my Actions' tab looks normal so I really don't know how to proceed from here.

Here's a snapshop of my Actions
![immagine](https://user-images.githubusercontent.com/38635522/148129997-b08872b2-6caf-4178-9fe4-d779e3372e80.png)

**Comment by jacoporepossi** [comment]
any idea?

**Comment by jacoporepossi** [comment]
@FynnGilbert sorry to hear that.
I have no idea why I'm not getting the PR, I hope someone will look at this issue and can explain how to solve the problem

**Comment by francescodisalvo05** [comment]
I am having the same issue since yesterday

**Comment by francescodisalvo05** [comment]
I tried to create it again as a private repository and without selecting the "other branches" and now it works for me! I guess that the problem was on the branches (?)

**Comment by jacoporepossi** [comment]
Thanks @francescodisalvo05 , I confim it works!
Just wondering if anything will break by not selecting that option

**Comment by jacoporepossi** [comment]
Actually @francescodisalvo05 , it still doesn't work properly. It doesn't render the homepage properly.
Did you experience the same issue?

![image](https://user-images.githubusercontent.com/38635522/152652786-5cc49835-2c60-446b-804c-dc5fdd0a4f67.png)

**Comment by hamelsmu** [comment]
No nothing will break, yes you only need the master branch, I'll update the README

**Comment by DayalStrub** [comment]
not sure whether i somehow did something (else) wrong, or it's somehow hit and miss, but I too just tried to create a public repo (with GH suggested name! :rofl: ) from template and only copy master branch (which is default), but not getting any PR, as seen [here](https://github.com/DayalStrub/supreme-journey). 

_Note: If I do clone all branches, it seems keys are already set, so instead build action is automatically triggered - but no PR._

**Comment by hamelsmu** [comment]
Interesting!  That is very strange

**Comment by FynnGilbert** [comment]
> I tried to use the template without selecting the "other branches" and it worked for me!

This worked for me. Thank you SOO much.
