### ISSUE TITLE
Why my Jupyter notebook is not showing in blog?

### ISSUE THREAD

**Issue by dipesg** [fastai/fastpages#610]
When I upload a jupyter notebook in _notebooks folder, it uploaded correctly without error but when I open the blog it is not shown there. Please help me I am trying to solve it so hard but could not.

**Comment by stefanbschneider** [comment]
Does your GitHub action run without errors? Probably there is an error building the notebook.

**Comment by dipesg** [comment]
No there is no error 
![github1](https://user-images.githubusercontent.com/75604769/149816156-00c5ad3a-38dc-4972-92b0-1e1f9542f3e9.jpg)
![github2](https://user-images.githubusercontent.com/75604769/149816161-fcafac20-7c4e-42cf-a8e2-81def790b006.jpg)
.

**Comment by stefanbschneider** [comment]
Hm, does that happen for all your blog posts or just for a specific one?
Of course, if you set `hidden: true` or `published: false`, the blog won't be shown; but this should not be the case by default.

**Comment by dipesg** [comment]
When I try to upload markdown file i get this error.
![github3](https://user-images.githubusercontent.com/75604769/149868069-e1a2e02d-350d-4601-92ca-70ceddf570d3.jpg)

**Comment by dipesg** [comment]
Hey, Now it is showing in the blog but how I don't know. Previously it is not showing anyway thanks for your help @stefanbschneider

**Comment by stefanbschneider** [comment]
Strange. If there's a build error, I'd think you'd have to check the logs for more details on the error. To understand at which point and why the build fails.

But if it works either way - then good for you :)

**Comment by REsteche** [comment]
Well, after finding this I believe that I am the target of this same bug. GitHub actions run perfectly but posts don't show up on the blog except for the first blog post F
