### ISSUE TITLE
Notebook not shown in blog despite successful GitHub Actions

### ISSUE THREAD

**Issue by lukasalexanderweber** [fastai/fastpages#617]
## Required information

1. Steps to reproduce the problem

I tried to publish the [basic example](https://github.com/lukasalexanderweber/stitching_tutorial/blob/master/_notebooks/2022-02-02-Basic-Example.ipynb) and [a more complex notebook](https://github.com/lukasalexanderweber/stitching_tutorial/blob/master/_notebooks/2022-02-02-Stitching-Tutorial.ipynb)

2. A link to the notebook or markdown file where the error is occurring

The [more complex notebook](https://github.com/lukasalexanderweber/stitching_tutorial/blob/master/_notebooks/2022-02-02-Stitching-Tutorial.ipynb) is not shown on the blog on https://lukasalexanderweber.github.io/stitching_tutorial/.

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.

All actions run successful: https://github.com/lukasalexanderweber/stitching_tutorial/actions

4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

To be honest I'm not allowed to use docker at my workplace so I have not the possibility to check the file for locally for errors. Any help whats the issue with the notebook and why the actions do not throw any error would be appreciated

**Comment by hamelsmu** [comment]
Your [basic notebook](https://lukasalexanderweber.github.io/stitching_tutorial/2022/02/02/Basic-Example.html) works, your [more complex notebook ](https://nbviewer.org/github/lukasalexanderweber/stitching_tutorial/blob/master/_notebooks/2022-02-02-Stitching-Tutorial.ipynb) lack any front matter at all and it is no wonder why it doesn't render.  

I would follow the instructions carefully as well as go through the debugging steps as indicated on the READMe
