### ISSUE TITLE
All CI workflow runs are failing and gh pages build and deploy workflow not working.

### ISSUE THREAD

**Issue by sandeshkatakam** [fastai/fastpages#619]
All of my CI workflows are failing and the pages-build-and deployment workflow is not running after my new commits.
This started happening after I added a sample notebook to the notebook folder in the repo: [link to the noteboook](https://github.com/sandeshkatakam/My-Machine_learning-Blog/blob/master/_notebooks/2021-09-30-Python-Basics-Tutorial.ipynb)  
[Link to my github actions page](https://github.com/sandeshkatakam/My-Machine_learning-Blog/actions/workflows/ci.yaml)
<img width="960" alt="Screenshot 2022-02-06 114415" src="https://user-images.githubusercontent.com/88609382/152669854-a681cd76-e59c-44e4-8c69-3f4ee845097b.png">

<img width="960" alt="Screenshot 2022-02-06 114343" src="https://user-images.githubusercontent.com/88609382/152669857-f8d377b9-c7e5-4586-b176-8e86ccb73482.png">  

My last pages-deployment and build workflow ran 13 hours ago and since then the gh pages workflow run also stopped running , I guess it may be because of the failing CI workflow runs.
<img width="960" alt="Screenshot 2022-02-06 114548" src="https://user-images.githubusercontent.com/88609382/152669881-b0fba1b9-13a3-4b96-a528-f3c625edb564.png">
<img width="960" alt="Screenshot 2022-02-06 114742" src="https://user-images.githubusercontent.com/88609382/152669897-9f0ab87b-9b83-492a-8c04-8d6607db949a.png">

**Comment by hamelsmu** [comment]
Looks like your actions are completing now?

**Comment by sandeshkatakam** [comment]
> Looks like your actions are completing now?

Yeah the problem was with one of the jupyter notebooks I uploaded and the jekyll build was failing on that noteboook for some reason. Now it is working good. Thank you
