### ISSUE TITLE
Build fails with latest Minima commit

### ISSUE THREAD

**Issue by papagunit** [fastai/fastpages#625]
## Required information

1. Steps to reproduce the problem
Build fastpages from today's commit

2. A link to the notebook or markdown file where the error is occurring
First got an error with `Liquid syntax error (line 86): Unknown tag 'twitter'`. Fixed that, and then got `Undefined variable: "$grey-color". on line 132`.
Eventually I tracked it down to the minima theme that was remotely being brought in. Suspected a dependency issue and decided to revert it to an earlier commit.

3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.
https://github.com/papagunit/devons-github-blog/runs/5417070815?check_suite_focus=true

I was able to resolve this by adding "@6513ea8b9c1c4909b6aa79926d52a1f7d865c5e7" to the remote-theme property in the config.yml

**Comment by jph00** [comment]
Many thanks - I've made that change in our config
