### ISSUE TITLE
Auto upgrade fails

### ISSUE THREAD

**Issue by castorfou** [fastai/fastpages#634]
## Required information

1. Steps to reproduce the problem

Create an issue of type [fastpages] Automated Upgrade
Open the action

Wait for a new comment in this issue by github-actions:

> An error occurred when attempting to open a PR to update fastpages. See the [Actions tab of your repo](https://github.com/castorfou/guillaume_blog/actions) for more details.

3. A link to the notebook or markdown file where the error is occurring
4. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.

The action [fastpages] Automated Upgrade fails in the upgrade job.
More specifically it fails at the sync baseurl step.

Run import re, os, yaml
Traceback (most recent call last):
  File "/home/runner/work/_temp/5[1](https://github.com/castorfou/guillaume_blog/runs/5865734501?check_suite_focus=true#step:7:1)4acf91-[38](https://github.com/castorfou/guillaume_blog/runs/5865734501?check_suite_focus=true#step:7:38)52-4d68-a20e-62f3ad147b7d.py", line 22, in <module>
    config = yaml.load(cfg)
TypeError: load() missing 1 required positional argument: 'Loader'
Error: Process completed with exit code 1.

6. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

![image](https://user-images.githubusercontent.com/2387408/162191209-810a7020-9eee-4d42-ba04-3f203315c1ee.png)

**Comment by castorfou** [comment]
I think this is due to PyYAML yaml.load(input) Deprecation.
As explained in [https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation), 

> Use of PyYAML's yaml.load function without specifying the Loader=... parameter, has been deprecated. In PyYAML version 5.1+, you will get a warning, but the function will still work. See [How to Disable the Warning](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation#how-to-disable-the-warning) below.

I guess now it is not a warning message, but an error message.

Not sure how to fix it, maybe force a previous yaml version?

**Comment by hamelsmu** [comment]
@castorfou Yes I had to pin this version of pyaml which I fixed.  Is there any chance you can start a new repo and copy all your files over?  I've made some additional changes based on GitHub Actions that won't allow you to upgrade without copying everything over.  

I'll close this issue for now but please feel free to keep the conversation going.

**Comment by castorfou** [comment]
Thank you @hamelsmu 
I have just created a new repo and copied everything. It works but .. is there a way to keep the former baseurl?
I tried by modifying `_config.yml` and `_action_files\settings.ini` without any success.

**Comment by castorfou** [comment]
I have detailed what I did at https://castorfou.github.io/blog/blog/upgrade-fastpages.html

**Comment by hamelsmu** [comment]
@castorfou can your new repo so its the same as the old repo?  That should help.  You may have to rename the old repo first

**Comment by castorfou** [comment]
@hamelsmu so simple ;) will do that
