### ISSUE TITLE
Initial commit Setup #1 [The requested URL returned error: 403]

### ISSUE THREAD

**Issue by Bakar31** [fastai/fastpages#640]
## Required Prerequisites for filing a bug
I have made a couple of repos copying the fast pages templates but getting the same error over and over again.  Error in setup(setup.yaml) job.

I have found several closed issues with nearly the same problem but couldn't fix it.

The error look like this:
![error](https://user-images.githubusercontent.com/61455347/167267897-572610b8-e7a2-4606-bf67-a80b6d24956e.png)

**Comment by sgaseretto** [comment]
I'm having the same issue when trying to generate a blog from this template. The template does not generate the PR

**Comment by szagar** [comment]
Same issue, 403 error and PR not generated.  Repository is public, actions enabled, i'm logged into github.

**Comment by 4923** [comment]
https://forums.fast.ai/t/fastpages-initial-commit-setup-fail/96069/7 would be help

**Comment by hamelsmu** [comment]
Thanks for your patience, I have added detailed instructions in the setup section of the README to show how to resolve this error
