### ISSUE TITLE
Docs/FAQ: why changing theme breaks everything

### ISSUE THREAD

**Issue by drscotthawley** [fastai/fastpages#73]
In _config.yml, if you make the one-line change, 
```
#theme: minima
theme: jekyll-theme-cayman
```
...the blog builds but is reduced to nothing  (...almost nothing. in my case one image remains, nothing else).  

At some point, it would be awesome to have a FAQ topic on changing the theme to another one of the [supported GitHub Pages Jekyll themes](https://pages.github.com/themes/)!   I realize that's probably a low priority.

**Comment by drscotthawley** [comment]
..and the answer would be that there seems to be a lack of standardization of the theme layouts.
`minima` [has 4 layouts](https://github.com/jekyll/minima/tree/master/_layouts) that include the "home" layout referenced in `fastpages/index.md`. 

But themes like `cayman` and `merlot` only have the "default" layout. So with `index.md` only referring to the (now nonexistent) "home" layout, the site builds and empty page.

**Comment by hamelsmu** [comment]
Changing themes is not supported like this.  Its currently not possible and will break many things.  We had to take an opinionated approach to make this automated.

**Comment by drscotthawley** [comment]
@hamelsmu  Ok, in that case, I might suggest that the line in _config.yml  be changed from 

```
# Everything below here can be ignored, unless you want to change the theme entirely
```
to something like
```
# Do not modify anything below this line.
```
The way it reads, it seems like users who want to change the theme can do so. That's why I tried.

**Comment by hamelsmu** [comment]
Good idea!  Please submit a PR 😉

**Comment by drscotthawley** [comment]
Is it possible to change the syntax highlighting?  Currently what's being generated for my pages does not resemble [typical dark-on-light highlighting in FastAI notebook documentation](https://docs.fast.ai/tutorial.data.html): instead of the usual dark-on, white, what I'm seeing by default is some carnival of colors on a dark theme,such as in 
https://drscotthawley.github.io/devblog2/2019/12/21/PCA-From-Scratch.html

**Comment by hamelsmu** [comment]
Yeah you can change the css in assets/main.scss

Proceed at your own risk!

**Comment by drscotthawley** [comment]
@hamelsmu  I think this highlighting issue will merit attention, because for markdown posts, the highlighting scheme renders the code almost unreadable because so much of it is white-on-white. 

 I added some code to the bottom of your sample post in order to illustrate this:
https://drscotthawley.github.io/devblog3/2020/02/20/sample-markdown-post.html

**Comment by hamelsmu** [comment]
Hi Scott can you open a separate issue re:markdown highlighting ?  Again
this thread will become confusing for people reading this issue.
Appreciate your help

**Comment by hamelsmu** [comment]
This will be fixed in https://github.com/fastai/fastpages/pull/81
