### ISSUE TITLE
Code syntax highlighting for Markdown posts

### ISSUE THREAD

**Issue by drscotthawley** [fastai/fastpages#82]
...the current color scheme renders most variable names and libraries in white text, on a background that is very light-colored.  The result is unreadable.   Example: see "More code" in https://drscotthawley.github.io/devblog3/2020/02/20/sample-markdown-post.html.

It's the same highlighting scheme (Dracula) used for the notebooks, but for the notebooks the background is dark, so it's not a problem.

Can someone suggest how to either enforce a darker background for markdown posts, or suggest a different highlighting scheme (and how to install it) that will render well for both notebooks and markdown posts?

**Comment by hamelsmu** [comment]
This has been fixed in the latest version of this repo.   See https://fastpages.fast.ai/2020/01/14/test-markdown-post.html

**Comment by drscotthawley** [comment]
Ok, I see that in your version.  That looks good. 
I would like to reproduce that! ;-)   In mine, after merge from upstream, I got a ton of conflicts in various control files I don't understand, which I've tried to resolve manually... but the result is that the code background is still colored lightly.    The `assets/main.scss` is identical to your new one, so... not sure. :shrug:   Will keep trying.

**Comment by drscotthawley** [comment]
Got it. :+1:   Looks good. Thanks!

**Comment by zqfang** [comment]
here is another bug with bash script. How to improve that? @hamelsmu 

![image](https://user-images.githubusercontent.com/5889336/75617853-92988300-5b19-11ea-8d14-01bec18c2d6d.png)

**Comment by hamelsmu** [comment]
@zqfang this will be fixed by https://github.com/fastai/fastpages/pull/150
