### ISSUE TITLE
Porting from older releases

### ISSUE THREAD

**Issue by cabrajudo** [fastai/fastpages#85]
As per the email generated when I cloned the fastpages repo I set up the SSH public and private keys

I set the cloned github repo to point to my custom domain

I copied the following over from the old repo

1. my _config.yml 
2. index.md
3. about.md
4. _word directory contents

Issue:

The index and about pages render correctly and the example .md post in the _posts directory

But the other posts from the _word directory do not

Main page renders like this

![image](https://user-images.githubusercontent.com/60429503/75022944-e1e21200-548e-11ea-8d95-f7538be1668c.png)

I checked the CI/build site log and it reports a deploy error

ERROR: not found ACTIONS_DEPLOY_KEY, PERSONAL_TOKEN, or GITHUB_TOKEN

![image](https://user-images.githubusercontent.com/60429503/75022831-ae9f8300-548e-11ea-8e4f-609c67654601.png)

I grepped the source files but I'm not sure what I'm missing

![image](https://user-images.githubusercontent.com/60429503/75023139-39807d80-548f-11ea-8944-18ab10dd857f.png)

**Comment by cabrajudo** [comment]
First problem was I hadn't correctly named the SSH private key SSH_DEPLOY_KEY as per 2. in the email

![image](https://user-images.githubusercontent.com/60429503/75036897-d6044900-54aa-11ea-8b6c-ac1ef20073cf.png)

The text in the email is confusing as 2. suggests there's a tickbox for the private key to allow it to be overwritten

There isn't

It's only for the public key 

Also a 4th step is missing in the invitation email, that of creating a gh-pages branch

Step 4. is present in the README.md file however!

https://github.com/fastai/fastpages/blob/master/_manual_setup.md

However I'm still having an issue and the deploy step is still failing, this time for a different reason

![image](https://user-images.githubusercontent.com/60429503/75037149-68a4e800-54ab-11ea-80c0-6555c56b5814.png)

**Comment by hamelsmu** [comment]
@cabrajudo its because you may have setup your keys incorrectly

- make sure you use matching public / private key pairs (they are related to eachother one is used to decrypt the other).
- as you mentioned you must name your secrets correctly

your specific error is because your keys are mismatched, or you forgot to tick the box "allow write access" when saving your private key.  I will fix this in the instructions.  

The `ACTIONS DEPLOY KEY` does not live in your files, so grepping doesn't make sense in this case, it only lives on GitHub.com in a secrets vault.  

hope that helps

**Comment by hamelsmu** [comment]
@cabrajudo you should read my comment directly in this issue as I edited my answer (not through email).  Thanks

**Comment by cabrajudo** [comment]
Hi Hamel

there's no option to allow write access on the private key as you can see
in the screencap below

[image: image.png]

Only the public key allows this option

[image: image.png]

**Comment by hamelsmu** [comment]
@cabrajudo 

> you should read my comment directly in this issue as I edited my answer (not through email). Thanks

**Comment by cabrajudo** [comment]
Not sure what I changed but it now passes the deploy step

Perhaps I had scrambled something while cut & pasting the RSA keys

![image](https://user-images.githubusercontent.com/60429503/75046329-c8f05580-54bc-11ea-9e30-ed4973437bb3.png)

**Comment by hamelsmu** [comment]
That’s great!
