### ISSUE TITLE
The first PR couldn't be generated

### ISSUE THREAD

**Issue by deep-diver** [fastai/fastpages#91]
I have followed the instructions from the `README.md`, 
> - Generate a copy of this repo by clicking on this link.
> - GitHub Actions will automatically open a PR on your new repository ~ 30 seconds after the copy is created. Follow the instructions in that PR to continue.

but I got the following error during the `setup` process.

![Screen Shot 2020-02-22 at 2 59 44 PM](https://user-images.githubusercontent.com/26025527/75087484-4a5eeb00-5584-11ea-8346-8a568078d0a3.png)

**Comment by hamelsmu** [comment]
This was fixed in #92 sorry about that try again
